#+title: Fundamentos de inteligencia artificial
#+startup: latexpreview
#+author: Jordi Amposta Perez
#+startup: latexpreview content

* Aspectos conceptuales de la Inteligencia Artificial y la ingeniería del conocimiento
- Propósito general de la IA es desarrollar
      1. Modelos conceptuales.
      2. Procedimientos de escritura formal de esos procedimientos.
      3. Estratégias de programación y máquinas físicas para reproducir los mecanismos de inteligencia.
- 4 Objetivos de la IA son modelar, formalizar, programar e implementar máquinas soporte capaces de interactuar con el medio de forma no trivial.
- Aproximaciones dominantes.
      - IA simbólica, via descendente y uso de conceptos del lenguaje natural para representar el conocimiento necesario para resolver problemas de decisión.
            - No requiere de un robot.
      - IA conexionismo situado, via ascendente y usos de conceptos de más bajo nivel semántico.
            - IA como forma superior de adaptación al medio (requiere robot).
- Carácter instrumental y objetivos.
      - Ayudar a comoprender los procesos neurofisiológicos, cognitivos y sociales.
      - Prolongar los analizadores humanos y complementar sus deficiencias.

** IA como Ciencia y como IC
*** IA como Ciencia
- Tarea de análisis
- Engloba el conjunto de hechos asociados a la neurología y la cognición.
- Funciones globales de percepción, memoria, lenguaje, decisión, emoción y acción (acciones humanas).
      - Emergen de niveles subcelulares, neurológicos, etc.
- Busca una teoría computable del conocimiento humano.

*** IA como Ingeniería (IC)
- Nuevo objetivo de la IC es el conocimiento.
      - Usa la energía como soporte.
- El mensaje está en la estructura relacional y en el consenso entre los distintos observadores.
      - Deben dotar de significado a los símbolos formales y físicos que constituyen el cálculo.
- El conocimiento debe ser
      - Reutilizable
      - Impersonal
      - Transferible
      - Verificable experimentalmente
      - Con capacidad de predicción (como una ley física).
- No puede apoyarse en una sólida teoría del conoccimiento.
- Tareas que aborda la IC
      1. Tareas básicas como ver, oir, interpretar el medio, moverse, aprender, etc.
      2. Tareas cientifico-técnicas en dominios estrechos
             - Diagnosticar en medicina por ejemplo
- Procedimiento en *SBCs*, sistemas basados en el conocimiento
      1. Descripción en lenguaje natural de las interacciones de un humano con el entorno.
      2. Se modela la descripción con metamodelos (*paradigmas*).
             - Simbólico
             - Conexionista (neurona formal)
             - Situado
             - Híbrido
      3. Escritura formal de las inferencias y los "roles" estáticos y dinámicos de acuerdo con el paradigma elegido.
             - Tipos esenciales de conocimiento
                   - Situado, Interacción con el medio, un robot.
                   - No situado, Interfaz entre el sistema IA y el medio es humana.
      4. Programar los operadores para las interfaces físicas (no humanas).

** Paradigmas actuales en IA
- *Paradigma* : Aproximación metodológica consensuada.

*** Paradigma Simbólico o representacional
- Se parte de una descripción en lenguaje natural que se intenta describir en reglas.
- Descripciones declarativas de un conjunto de conceptos.
- Otro conjunto de reglas de inferencia entre estos conceptos.
      - *Reglas* de manipulación.
- 3 tipos de tareas
      - Análisis
      - Síntesis, diseño y construcción con restricciones.
      - Modificación, ajuste de parámetros.
- Procesos básicos del razonamiento humano según Craik
      - Traslación del medio externo a una representación interna.
      - Derivación de los símbolos anteriores mediante procesos de inferencia (inductiva, deductiva y abductiva).
      - Retraslación de los nuevos símbolos derivados en término de acciones que vuelven al medio externo.
- Apropiada para aplicaciones en las que disponemos de conocimiento suficiente para especificar las reglas inferenciales y en aquellos procesos de aprendizaje inductivo en los que también disponemos de conocimiento para especificar las meta-reglas.

*** Paradigma Situado o reactivo
- También llamado basado en conductas.
- Toda acción y toda percepción están estructuralmente acopladas.
      - El sistema a modelar se encuentra en un medio con el que se realimenta.
            - Sensores y efectores específicos.
            - Para el sistema solo existe lo que puede ser representado por un sensor.
- La percepción en el medio de esquemas son las percepciones
      - Se implementa a bajo nivel.
- Cuando el agente decide la acción o secuencia de acciones a realizar basta con que las active.
      - Los patrones espaciotemporales de acción están precalculados.
- La función de decisión del agente es una asociación (tabla) o autómata finito.
- Se usa esencialmente en robótica y sistemas en tiempo real.

*** Paradigma Conexionista (RNAs)
- *RNAs* : redes de neuronas artificiales.
- Líneas numéricas etiquetadas para la entrada y salida de la red.
- La inferencia se resuelve mediante un clasificador numérico de naturaleza paramétrica.
      - El valor de los parámetros se ajusta mediante aprendizaje.
- Arquitectura modular organizada en capas fuertemente interconectado.
      - Procesadores elementales son las neuronas que evaluan una sencilla función de cálculo.
- Características distintivas
      - Clasificador numérico adaptativo que asocia los valores de un conjunto de observables con los valores de otro conjunto más reducido de clases (salidas de las neuronas de la última capa).
      - Una parte importante del conocimiento disponible se corresponde con la fase de análisis de datos.
            - Selección de variables de entrada y salida.
            - Tipo de cálculo local
            - Inicialización de pesos
      - Balance entre datos y conocimiento disponible y naturaleza de esos datos.
            - Datos etiquetados se usan en el aprendizaje supervisado.
            - Datos no etiquetados se usan para un preproceso y el aprendizaje autoorganizativo.
- Representación de grafo.
      - Nodos son neuronas.
      - Arcos son pesos ajustables.
- Las salidas numéricas de la última capa se interpretan con etiquetas asociadas a las clases.
- Hay otra vertiente más basada en mecanismos inspirados por la biología
      - Conexionismo bioinspirado
        
*** Paradigma Híbrido
- La mayor parte de los problemas son de naturaleza híbrida.
- Muy usado en *Sistemas borrosos*, inferencias en las que se mezclan componentes neuronales y borrosas.
      - Adquirir conocimiento, conjuntos borrosos más etiquetas.
      - Pueden usarse entradas numéricas y tratarlas con neuronas convencionales.
      - Pueden definirse esquemas de cálculo neuroborroso (operadores borrosos(min, max)).
      - Subyace conocimiento simbólico usado para especificar las variables y sus rangos, definir funciones de pertenencia y para diseñar la topología inicial de la red.
- Criterios generales.
      - Analizar exigencias computacionales del problema y los recursos de los que disponemos.
      - Descomponer en subtareas e inferencias primitivas.
      - Operacionalización efectiva del esquema inferencial, con módulos simbólicos y neuronales.

* Lógica y representación del conocimiento
# Creo que son lecturas opcionales

* Introducción a las técnicas de búsqueda
- Tema 8 pag 310
  
** Algunos ejemplos
*** Generación de planes de actuación de robots
- Un entorno de actuación y un robot con un repertorio finito de opciones.
- Programar un robot consiste en.
      - Funciones de percepcion del entorno.
      - Funciones de formulación de planes de actuación.
      - Funciones de seguimientos de los planes.
- Según pag 311 es un problema de optimización casi tipo *Ramificación y poda* o *vuelta atrás*.
      - se usa una función /mueve(x,y)/ para ir avanzando en la solución.

*** Problema de rutas óptimas en grafos        
- pag 312, habla del algoritmo de dijkstra y el del viajante de comercio (travelling salesman problem (TSP)) (ram. y poda).

*** Juegos con contrincante
- pag 313
- Juegos como damas o ajedrez.
- La idea es que cada jugador (ambos IA) eligan la jugada más favorable.

** Formulación de problemas de búsqueda
- Componentes principales de un *sistema de búsqueda*.
      - *Los estados*, todas las situaciones por las que el agente puede eventualmente pasar durante la solución del problema.
            - Implica la elección de el modelo de representación.
      - *Reglas u operadores*, modelan las acciones elementales que es capaz de realizar el agente.
            - La interpretación del coste de cada operador debe hacerse a partir de la función objetivo.
      - *La estratégia de control*, Decide el orden en que se van explorando los estados.
            - La *búsqueda a ciegas* implica visitar más estados.
            - *La búsqueda inteligente* debe implicar visitar menos estados.
- *Estados* y *operadores* definen en *espacio de búsqueda*.
      - Algunos *nodos* (representación de grafo) del espacio de búsqueda representan las soluciones.
- Un *algoritmo de búsqueda es completo* si siempre encuentra solución, en el caso que exista alguna.
- Un *algoritmo de búsqueda es admisible* o exacto si siempre encuentra una solución óptima.

** Métodos de búsqueda sin información
- Búsquedas de forma sistemática sin tener en cuenta nungún tipo de información sobre el dominio del problema.
- Se suele considerar un árbol como espacio de búsqueda.
      - El grafo para espacios de búsqueda más generales.

*** Recorrido de árboles
**** Primero en Anchura
- Es un *algoritmo completo*.
- Si todas las reglas tienen un coste de 1 es *admisible*.
- Tiempo de ejecución y el espacio de memoria crecen de forma exponencial.
- El número de nodos total (que pueden visitarse) de un árbol es una *sucesión geométrica*.
      - $\sum_{i=0}^d b^{i} = \frac{b^{d+1} - 1}{b-1}$
            - $b$ es el número de hijos de cada nodo, que puede ser el caso medio.
            - Se supone que el nivel 0 es de 1 solo nodo.

#+begin_src pseudocode
ABIERTA=(inicial)
mientras NoVacia(ABIERTA) hacer
    n <- ExtraePrimero(ABIERTA)
    
    si EsObjetivo(n) entonces
        dev Camino(inicial,n)
    fsi
    
    S = Sucesores(n)
    
    para cada q en S hacer
        pone q en la TABLA_A con         // TABLA_A almacena los datos de un estado de búsqueda
            Anterior(q) = n,
            Coste(inicial,q) <- Coste(inicial,n) + Coste(n,q)
        ABIERTA <- ABIERTA union {q}
    fpara
fmientras
dev "No encontrado"
#+end_src

**** Primero en profundidad
- No es una estratégia admisible ni completa, puede adentrarse en un rama infinita.
      - Suele establecerse una profundidad límite.
- Si la profundidad límite es $d$, el espacio requerido máximo es.
      - $(b-1)(b-2) + b$ para ABIERTA
      - $1+(d-1)b$ para TABLA_A
- Máximo de nodos visitados $\frac{b^{d+1}-1}{b-1}$

#+begin_src pseudocode
ABIERTA <- (inicial)                 // Es una pila
mientras NoVacia(ABIERTA) hacer
    n <- ExtraePrimero(ABIERTA)
    si EsObjetivo(n) entonces
        devolver Camino(inicial,n)
    fsi
    S <- {}
    si Profundidad(n) < ProdundidadLimite entonces
        S <- Sucesores(n)
    fsi
    si Vacio(S) entonces
        LimpiarTabla_A(n)
    fsi
    para cada q en S hacer
        pone q en la TABLA_A con
            Anterior(q) <- n,
            Coste(inicial,1) <- Coste(inicial,n) + Coste(n,q),
            Profundidad(q) <- Profundidad(n) + 1
        Encola(q, ABIERTA)
    fpara
fmientras

dev "No encontrado"
#+end_src        

**** Coste uniforme
- pag 320
- En vez de usar una pila o una cola pueden insertarse los nodos en una estructura ordenada.
      - Se ordenan por coste el desde el nodo inicial.
- Es un *algoritmo admisible*.

****   Búsquedas en profundidad y en anchura iterativas
- pag 320
- Búsqueda en profunidad que se va ampliando la produndidad límite si no se encuentra ninguna solución.

#+begin_src pseudocode
ProfundidadLimite <- 1
Solucion <- BusquedaPrimeroenProfundidad
mientras Solucion = "No encontrado" hacer
    ProfundidadLimite <- ProfundidadLimite + 1
    Solucion <- BusquedaPrimeroenProfundidad
fmientras
dev Solucion
#+end_src

- Búsqueda en anchura que va ampliando la anchura límite si no se encuentra ninguna solución.

#+begin_src pseudocode
AnchuraLimite <- 0
mientras se pueda aumentar la AnchuraLimite hacer
    AnchuraLimite <- AnchuraLimite + 1
    ABIERTA <- (inicial)
    mientras NoVacia(ABIERTA) hacer
        n <- ExtraePrimero(ABIERTA)
        
        si EsObjetivo(n) entonces
            dev Camino(inicial,n)
        fsi
        
        S <- Sucesores(n,AnchuraLimite)  // AnchuraLimite limita el número
                                         //  de nodos sucesores
        para cada q en S hacer
            poner q en la TABLA_A con
                Anterior(q) <- n,
                Coste(inicial,q) <- Coste(inicial,n) + Coste(n,q)
                
            Encolar(q, ABIERTA)
        fpara
    fmientras
fmientras
dev "No encontrado"
#+end_src

*** Recorrido de grafos
- A veces el ábol no sirve para modelar los estados de una solución.
      - Por ejemplo en el cálculo de actuación de planes de un robot.

**** Algoritmo general de búsqueda en grafos (AGBG)
:PROPERTIES:
:ID:       c2bbf2c1-f380-4078-93f6-8b52f0e78859
:END:
- Grafo dirigido simple a partir de operadores o reglas de producción.
- Número de reglas con un coste $\leq \varepsilon$, $\varepsilon > 0$, debe ser finito.
- Grafo localmente finito, cada nodo tiene un número finito de sucesores.

#+begin_src pseudocode
// TABLA_A contiene el mejor camino encontrado desde inicial a cada nodo.
ABIERTA <- (inicial)
mientras NoVacia(ABIERTA) hacer
    n <- ExtraePrimero(ABIERTA)
    si EsObjetivo(n) entonces
        dev Camino(inicial, n)
    fsi

    S <- Sucesores(n)
    Añade S a la entrada n en TABLA_A
    
    para cada q de S hacer
        si q en TABLA_A entonces
            Rectificar(q,n,Coste(n,q))   // Se comprueba si el nuevo camino es mejor
            Ordenar(ABIERTA)             // Ordenación por coste
            // No se incluye en ABIERTA
        sino
            pone q en la TABLA_A con
                Anterior(q) <- n,
                Coste(inicial,q) <- Coste(inicial,n) + Coste(n,q)
            ABIERTA <- Mezclar(q, ABIERTA)  // Inserta q en abierta
                                            //  Según la posición la búsqueda será
                                            //  en profundidad o en anchura
        fsi
    fpara
fmientras
dev "No solución"
#+end_src

#+begin_src pseudocode
fun Rectificar(n,p,costepn)
    si (Coste(inicial,p) + costepn) < Coste(inicial,n) entonces
        modifica la entrada del nodo n en la TABLA_A con
            Coste(inicial,n) <- Coste(inicial,p) + costepn
            Anterior(n) <- p
        RectificarLista(n)
    fsi
ffun

fun RectificarLista(n)
    LISTA <- Sucesores(n)    // Registrados en la TABLA_A
    para cada q de LISTA hacer
        Rectificar(q,n,Coste(n,q))
    fpara
ffun
#+end_src

**** Búsqueda bidireccional
- Buscar simultáneamente en dos direcciones.
      - De inicio a los objetivos.
      - De los objetivos a inicio.
- La búsqueda se detiene cuando las fronteras (listas ABIERTA) tienen algún nodo en común.
- En lugar de exponencial a $d$ podrían ser dos algoritmos a $d/2$.
- Hay que conocer los estados objetivos.
- Almenos una de las búsquedas debe retener en memoria todos los estados visitados.
      - Por tanto búsqueda en anchura.
      - Por tanto el espacio requerido es exponencial en $d/2$.
- Requiere un método eficiente para comprobar intersecciones de las dos listas.
      - tablas Hash puede valer.

* Técnicas basadas en búsquedas heurística
- Tema 9, pag 340
- *heurístico*, mecanismo que permita dirigir la búsqueda hacia zonas más prometedoras.
      - Ayudan a decidir cual es la mejor alternativa entre varias posibles.
      - A veces fallan en la predicción de la mejor alternativa.
      - Se busca que el tiempo *medio* para llegar a una solución mejore.
            - El caso peor puede llegar aser igual que una búsqueda a ciegas.
- *metareglas*, reglas sobre como utilizar las reglas (pag 342).
      - Indican bajo qué condiciones se aplica cada acción.

** Búsqueda primero el mejor (BF, Best First)
- Una función $f(x)$ indica un valor de lo prometedor que es cada nodo para ser expandido.
      - Los nodos más prometedores están al principio.
- A $f(x)$ se le denomina *función heurística de evaluación*.

** El algoritmo A*
- [[id:IntArt]] pag 344
- Especialización de *BF*.
- Sea $n$ un nodo cualquiera del espacio de búsqueda.
      - $g^*(n)$ : Es el *coste del camino de menor coste* desde el nodo inicial hasta $n$.
      - $h^*(n)$ : *Coste del camino más corto desde* $n$ al objetivo más cercano a $n$ (objetivo = solución).
      - $f^*(n)=g^*(n) + h^*(n)$. Es decir es el coste del camino más corto desde el inicial a los objetivos condicionado a pasar por el nodo $n$.
      - $C^* = f^*(inicial) = h^*(inicial)$, es el coste de la solución óptima.
- Se trabaja con aproximaciones de las anteriores funciones.
      - $g(n)$ : Es el coste del mejor camino desde el inicial a $n$ obtenido hasta el momento durante la búsqueda.
            - $g(n) \geq g^*(n)$.
            - Se almacena en *TABLA_A*, se va rectificando a lo largo del recorrido.
      - $h(n)$ : Estimación positiva de $h^*(n)$, tal que $h(n)=0$ si $n$ es un objetivo.
            - $h(n) \geq 0$.
            - Es la *función heurística* o *heurístico*.
            - Definir $h(n)$ es un problema no trivial.
            - Es *admisible* si $h(n) \leq h^*(n)\ \forall n$
            - Se almacena en *TABLA_A*, se supone que no varía con el tiempo.
      - $f(n) = g(n) + h(n)$
- Se ordenan los nodos candidatos en *ABIERTA* según el valor $f(n)$ de forma ascendente.

*** Descripción del algoritmo A*
- Basado en [[id:c2bbf2c1-f380-4078-93f6-8b52f0e78859][AGBG]]

#+begin_src pseudocode
ABIERTA <- (inicial);
mientras NoVacia(ABIERTA) hacer
    n = ExtraePrimero(ABIERTA)
    si EsObjetivo(n) entonces
        dev Camino(inicial,n)
    fsi
    
    S <- Sucesores(n)

    Añade S a la entrada de n en la TABLA_A

    para cada q de S hacer
        si (q en TABLA_A) entonces
            Rectificar(q,n,Coste(n,q))
            Ordenar(ABIERTA)
        sino
            pone q en la TABLA_A con
                Anterior(q) <- n
                g(q)        <- g(n) + Coste(n,q)
                h(q)        <- Heurístico(q)
            ABIERTA <- Mezclar(q, ABIERTA)
        fsi
    fpara
fmientras
dev "No Solución"
#+end_src

- Función de Rectificación de nodos ya expandidos.

#+begin_src pseudocode
fun Rectificar(n,p,costepn)
    si (g(p) + costepn < g(n) entonces
        Modificar la entrada del nodo n en la TABLA_A con
            g(n)        <- g(p) + costepn
            Anterior(n) <- p
            RectificarLista(n)
    fsi
ffun

fun RectificarLista(n)
    LISTA <- Sucesores(n)        // Registrados en la TABLA_A
    para cada q de LISTA hacer
        Rectificar(q,n,Coste(n,q))
    fpara
ffun
#+end_src

*** Propiedades Formales
- $s$ estado inicial.
- $\Gamma$ conjunto nodos objetivo.
- $\Gamma^* \subseteq \Gamma$  conjunto de objetivos óptimos.
- $P_{n-n'}$ denota un camino simple desde el nodo $n$ al nodo $n'$.
- $P_{n-n'}$ camino óptimo desde $n$ a $n'$.
- *Nodos encontrados* : Aquellos que ya tienen entrada en *TABLA_A*.
- *Nodos expandidos* : Ya tienen registrados sus sucesores en el campo correspondiente de *TABLA_A*.
- $NodosEnAbierta\ \cup \ NodosExpandidos = NodosEncontrados$
      - La unión es disjunta.

**** Terminación y completitud
- $A^*$ es completo en grafos *localmente finitos* (teorema pag 346).
      - *localmente finito*, grafo infinito con un número finito de sucesores por nodo.

**** Admisibilidad del algoritmo A*
- Una función heurística $h$ es *adimisble* si $h(n) \leq h^*(n)\ \forall n$.
- Antes de que $A^*$ termine, existe un nodo $n'$ en ABIERTA tal que $f(n') \leq C^*$ (lema 9.1).
- $A^*$ es admisible (teorema 9.2).

**** Comparación de heurísticos admisibles
- Un heurístico $h_2$ está más informado que $h_1$ si los dos son adimisibles y $h_2(n) > h_1(n)\ \forall n$, $n$ no final.
      - $A_1^*$ usa $h_1$, $A_2^*$ usa $h_2$.
- $A_2^*$ domina a $A_1^*$ si los dos son admisibles y todo nodo expandido por $A_2^*$ también lo es para $A_1^*$.
- Una condición necesaria de expansión de un nodo $n$ es que $f(n) \leq C^*$ (teorema 9.3).
- Una condición suficiente de expansión de un nodo $n$ es que $f(n) < C^*$.
- Un camino $P$ desde el inicial $s$ a un nodo $n$ es *C-acotado*, si para todo $n'$ de $P$ se cumple que $g_P(n') + h(n') \leq C$.
      - Siendo $g_P(n')$ el coste desde $s$ a $n'$ a través del camino $P$.
      - *Estrictamente C-acotado* si $g_P(n') + h(n') < C$.
- Una condición suficiente para que $A^*$ expanda un nodo $n$ es que exista un camino estrictamente C*-acotado desde $s$ a $n$ (teorema 9.5).
- Una condición necesaria de expansión de un nodo $n$ es que exista un camino C*-acotado desde $s$ a $n$ (teorema 9.6).
- Si $A_2^*$ está más informado que $A_1^*$, entonces $A_2^*$ domina $A_1^*$ (teorema 9.7).

**** Heurísticos consistentes o monótonos  
- $h$ es *monótono* si para todo par de nodos $n$ y $n'$ se cumple que.
\begin{equation*}
h(n) \leq k(n,n') + h(n')
\end{equation*}  
- $k(n,n')$ representa el coste mínimo para ir de $n$ a $n'$, $\infty$ si no hay camino.
- $h$ es *consistente* si para todo par de nodos $n$ y $n'$ se cumple que
\begin{equation*}
h(n) \leq c(n,n') + h(n')
\end{equation*}
- $c(n,n')$ represetna el coste de la regla que lleva de $n$ a $n'$, $\infty$ si no existe esta regla.
- *Monotonía* y *consistencia* son propiedades equivalentes.
- Todo heurístico *monótono* es admisible.
- Si $h$ es monótono y $A^*$ elige el nodo $n$ para expansión, entonces se cumple que $g(n)=g^*(n)$. El camino encontrado hasta el momento desde $s$ a $n$ es óptimo.
- Si $h$ es monótono, la condición necesaria de expansión de un nodo $n$ es
\begin{equation*}
g^*(n) + h(n) \leq C^*
\end{equation*}
- Y la condición suficiente
\begin{equation*}
g^*(n) + h(n) < C^*
\end{equation*}
- $A_2^*$ domina *ampliamente* a $A_1^*$ si todo nodo expandido por $A_2^*$ es también expandido por $A_1^*$. Excepto quizás algunos nodos que cumplen $h_2(n)=h1(n)=C^* - g^*(n)$
- Si $h_2(n) \geq h_1(n)$ para todo $n$ y los dos son monótonos, entonces $A_2^*$ domina ampliamente a $A_1^*$.

*** Diseño de heurísticos simples  
- pag 353

*** Relajación de las condiciones de optimalidad
- pag 357
- Se plantea que $A^*$ sea más aficiente aunque pierda admisibilidad.

**** Ajuste de los pesos de g y h
- Ponderación estática.
\begin{equation*}
f_w(n) = (1-w)g(w) + wh(n),\ w \in [0,1]
\end{equation*}
- Se encuentra el mejor valor de $w$ de forma experimental.
      - Si $h$ es admisible el algoritmo es admisible en $0 \leq w \leq 1/2$
      - Si $h$ es admisible en algoritmo puede perder la admisibilidad en $1/2 \leq w \leq 1$

**** Algoritmos E-admisibles
- $\varepsilon -admisibles$
- Sacrifica la obtención de una solución óptima frente a mejoras del rendimiento.
- $\varepsilon$ controla el deterioro de la solución obtenida.
- Un algoritmo es $\varepsilon - admisible$ si siempre encuentra una solución con un coste menor de $(1 + \varepsilon)C^*$.

***** Ponderación dinámica
- Los pesos son dinámicos, cambian a lo largo del proceso.
      - $h$ tiene un mayor peso al inicio de la búsqueda.
      - Al final se reduce para asegurar una búsqueda en anchura.

\begin{equation*}
f(n) = g(n) + h(n) + \varepsilon (1-d(n)/N)h(n)
\end{equation*}

- $d(n)$ es la profundidad del nodo $n$.
- $N$ es una cota superior de la profuncidad de la mejor solución.
- $\varepsilon>0$ indica la desviación que estamos dispuestos a admitir.
- Su $h$ es admisible el algoritmo de ponderación dinámica es $\varepsilon -admisible$.

***** Algoritmo AE*
- Algoritmo $A\varepsilon^*$
- Dentro de ABIERTA se considera una sublista llamada FOCAL formada por nodos cuyo valor de $f$ no se separa más de un factor $(1+\varepsilon)$ del valor mínimo de $f$ en ABIERTA

\begin{equation*}
FOCAL = \{n \in ABIERTA\ |\ f(n) \leq (1+\varepsilon)min( \{ f(n') : \forall n' \in ABIERTA \}) \}
\end{equation*}

- Se desarrollan primero los nodos de la sublista FOCAL.
      - Se usa el heurístico $h'$, que da una estimación del esfuerzo computacional para llegar a una solución.
      - Puede darse el case que $h'=h$.

- Si $h$ es admisible, $A_\varepsilon^*$ es $\varepsilon -admisible$.        

*** Diseño sistemático de heurísticos
- pag 360
- *Método de relajación del problema*, Versiones simplificadas del problema con menos restricciones.
      - Se enuncia el problema con todas sus restricciones.
      - Se suponen versiones relajadas.
            - Se relajan subconjuntos de restricciones.
            - Hasta conseguir una versión suficientemente simple que pueda ser resuelto con un *algoritmo polinomial*.
- Todo heurístico $h$ obtenido por *relajación del problema* es monótono.              

** Búsqueda con memoria limitada  
- Basado en búsqueda en profundidad

*** Algoritmo IDA*
- pag 362
- Se establece una longitud límite para la búsqueda del problema igual a $f(inicial)$.
      - $f(inicial)$ es una cota inferior de la solución óptima.
      - Cada iteración descarta los nodos $n$ que $f(n)$ supere $f(inicial)$.
- Si en una iteración no se encuentra solución se realiza una nueva iteración.
      - Con una nueva longitud límite $f(inicio)$
            - El valor de $f(n)$ menor de los nodos descartados en la iteración anterior.

#+begin_src pseudocode
LongitudLimite <- f(inicial)
Solución <- Primero en Profundidad con Longitud Limitada
mientras Solución = "No encontrado" hacer
    LongitudLimite <- NuevaLongitudLimite
    Solución       <- Primero en Profundidad con Longitud Limitada
fmientras
dev Solución
#+end_src              

#+caption: Algoritmo de búsqueda heurística en profundidad en árboles con longitud limitada
#+begin_src pseudocode
ABIERTA <- (inicial)
mientras NoVacia(ABIERTA) hacer
    n <- ExtraePrimero(ABIERTA)
    si EsObjetivo(n) entonces
        dev Camino(inicial, n)
    fsi
    S <- {}
    si f(n) < LongitudLimite entonces
        LimpiarTABLA_A(n)
    fsi
    para cada q de S hacer
        pone q en la TABLA_A con
            Anterior(q) <- n,
            g(q)        <- Coste(inicial,n) + Coste(n,q),
            h(q)        <- Heurístico(q)
    fpara
    Ordena S según los valores de f de menor a mayor
    ABIERTA <- Concatenar(S, ABIERTA)
fmientras
dev "No encontrado", NuevaLongitudLimite
#+end_src

*** Algoritmo SMA*
- [[id:IntArt]] pag 364
- IDA* tiene el problema de que se vuelven a expandir muchos nodos.
- Cuando necesita expandir un nodo y no tiene espacio en TABLA_A, elimina un nodo de esta tabla y de ABIERTA.
      - Son llamados *nodos olvidados*, y son los menos prometedores (mayor valor de $f$ en ABIERTA).
- El algoritmo recuerda en cada nodo el mejor $f$ de los hijos de ese nodo que han sido olvidados.
      - Para no volver a explorar subárboles que han sido eliminados.
- SMA* mantiene en los nodos ancestros información acerca de la calidad del mejor camino en cada subárbol descartado.
- Cuando se descartan todos los sucesores de un nodo $n$, el algoritmo recuerda la estimación del mejor camino a través de $n$.

#+begin_src pseudocode
Inserta el inicial en ABIERTA y en la TABLA_A
mientras NoVacia(ABIERTA) hacer
    n <- Primero(ABIERTA)
    si EsObjetivo(n) entonces
        dev Camino(inicial,n)
    fsi
    s <- SiguienteSucesor(n)
    si (NoEsObjetivo(s) && Profundidad(s) = Limite) entonces
        f(s) <- infty
    sino
        f(s) <- max(f(n), g(s) + h(s))
    fsi
    si todos los sucesores de n han sido generados entonces
        Actualiza f(n) y el f de los ancestros de n
    fsi
    si todos los sucesores de n están en la TABLA_A entonces
        Elimina n de ABIERTA
    fsi
    si la TABLA_A está llena entonces
        Elimina de ABIERTA y de la TABLA_A el nodo con mayor f en ABIERTA y menor profundidad,
          actualizando la estimación del mejor nodo hijo olvidado en el padre del nodo eliminado
        Inserta el padre del nodo eliminado en ABIERTA si no está
    fsi
    Inserta s en ABIERTA y en la TABLA_A
fmientras
dev "No solución"
#+end_src
        
- Propiedades principales
      - Es capaz de evolucionar utilizando la memoria que tenga disponible.
      - Evita estados repetidos en la medida en que la memoria se lo permita.
      - Es completo si la memoria disponible es suficiente para almacenar el camino a la solución menos profunda.
      - Es admisible si tiene suficiente memoria para almacenar el camino hasta la solución óptima menos profunda.
      - Si la memoria es suficiente para el árbol de búsqueda completo, la eficiencia de la búsqueda es óptima.
- No está resuelta la cuestión de si SMA* tiene una eficiencia mejor o igual que otro algoritmo dada la misma información heurística y la misma cantidad de memoria.

** Algoritmo Voraces
- [[id:IntArt]] pag 366

** Algoritmos de ramificación y poda
- [[id:IntArt]] pag 366

** Algoritmos de mejora iterativa o búsqueda local
- Para algunos problemas el nodo solución contiene toda la información necesaria.
      - El resto del camino es irrelevante (problemas TSP y N-reinas).
- La idea es partir de un estado solución e ir iterando con pequeñas mejoras.
      - Soluciones vecinas

#+caption: Esquema de un algoritmo de búsqueda local
#+begin_src pseudocode
S <- SolucionInicial
mientras ! CriterioDeTerminación hacer
    V <- SolucionesVecinas(S)
    EvaluarSoluciones(V)
    S1 <- Seleccion(V)
    si CriterioDeAceptacion entonces
        S <- S1
    fsi
fmientras
dev S
#+end_src        

*** Algoritmo de escalada o máximo gradiente
- [[id:IntArt]] pag 371

- El criterio de aceptación es que $S_1$ (*solución vecina*) sea mejor o igual a $S$ (*solución actual*).
- Problemas de estancamiento.
      - *Óptimos locales*, en estos puntos todos los vecinos son peores.
      - *Regiones planas*, todos los vecinos tienen el mismo valor que la solución actual y la búsqueda es aleatoria.
      - *Crestas*, Puede ser complicado guiar la solución a través de una cresta hasta la solución global.
- *Multiarranque* Contra los estancamientos se puede reiniciar el algoritmo desde otro punto inicial.

*** Temple Simulado
- Se admite con una cierta probabilidad que $S_1$ sea peor a $S$.
- Se realiza una selección aleatoria entre los vecinos.
      - Si el vecino mejora la solución se acepta.
      - Si el vecino no mejora la solución se acepta con una probabilidad.
            - $T$ temperatura, Alta al inicio del algoritmo
                  - Mayor probabilidad de aceptación.
                  - $T=\alpha(t,T)$, función alpha.
                        - $t$ iteración actual
            - $\Delta E$ incremento de energía
- Requiere un ajuste muy fino de los parámetros.
  
#+begin_src pseudocode
S <- SolucionInicial
t <- 0
T <- T_0
mientras ! CriterioDeTerminación hacer
    S_1 <- SelecciónAleatoria(SolucionesVecinas(S))
    \DeltaE <- Coste(S_1) - Coste(S);
    si \DeltaE < 0 entonces
        S = S_1
    sino
        S <- S_1 con probabilidad e^(- \DeltaE/T)
    fsi
    t <- t + 1
    T <- \alpha(t,T)
fmientras
dev S
#+end_src

*** Búsqueda tabú
- pag 373
- Dispone de un mecanismo de memoria.
- Evita la generación de algunos vecinos dependiendo de la historia reciente.
      - Se registra información de cada movimiento.
- Pueden hacerse excepciones, *criterio de aspiración*,  si un movimiento tabú resulta que mejora la solución actual.
- Resulta complicado establecer los parámetros.
      - Criterio de aspiración.
      - Memoria del histórico.
      - Información que se registra.

* Lógica y representación del conocimiento
- [[id:IntArt]] pag 33, capítulo 2

** Lógica proposicional (LP)
- El más sencillo (orden 0)
  
*** Sintaxis y semántica
- Notación :
      - $(x,y,z,\dots)$ o $(x_1,y_3,z_2,\dots)$ : variables del dominio.
      - $(p,q,r,\dots)$ : variables proposicionales de orden-0.
      - $p(x), q(x,y)$ : predicados.
            - $p^1,q^2$ : aridad del predicado.
      - $(\phi, \psi, \varphi)$ o $(\phi_1, \psi_3, \varphi_2)$ : fórmulas lógicas.
            - con subíndices si es necesario.
      - $(\Delta, \Gamma)$ : Conjunto de fórmulas.
      - $\models$ : Relación de satisfacibilidad o verdad.
            - $\Vdash$ en el caso de fórmulas modales
      - $(M,N,O,\dots)$ : Representan tanto modelos proposicionales y de primer orden clásicos como modales o temporales.
      - *Gramática abstracta* : para representar el conjunto de fórmulas de un lenguaje bien formado.
            - Por ejemplo $\phi ::= A | B | \phi \circ \psi$
- $\mathcal{AP}$ : Atomic propositions.
      - Una proposición solo puede ser falsa o verdadera.
- *LP* : *lógica proposicional clásica*. Basada en un conjunto numerable de proposiciones $\mathcal{AP}$.
- gramática abstracta de la lógica proposicional.
      - $\phi ::= p | \lnot \phi | \phi \land \psi | \phi \lor \psi |\phi \to \psi | \phi \leftrightarrow \psi$
      - $p \in \mathcal{AP}$
      - Reconocer las proposiciones y la conectivas en una frase verdadera permite obtener una formulación sin pérdida de información.
- Un problema importante es distinguir entre una fórmula bien construida para una gramática o mal construida.
- $M=\{p=V, q=F, r=F\}$ es un modelo.
      - $M \models \phi$  significa que el modelo satisface $\phi$.
- $\phi$ es satisfacible si existe almenos un modelo que la satisface.
      - Insatisfacible en caso contrario.
- Reglas para conocer la satisfacibilidad.
      - $M \models p$  si y sólo si $p=V$ en $M$.
      - $M \models \lnot \psi$ si y solo si no es verdad que $M \models \psi$.
      - $M \models \psi \land \varphi$ si y sólo si $M \models \psi$ y $M \models \varphi$.
- $\phi$ y $\psi$ son equivalentes si tienen la misma tabla de verdad.
- *Tautología* : o fórmula válida, es una fórmula que intemendientemente del modelo siempre es verdadera.
- *contradicción* : siempre falso.
- La negación de una *tautología* es una *contradicción*.
- *Razonamiento* : Conjunto de fórmulas $\Gamma = \{\phi_1, \dots, \phi_n\}$ del cual se puede sacar una *conclusión* $\phi$.
      - $\phi_1 \land \dots \land \phi_n \to \phi$.
- *Métodos deductivos*:
      - *Métodos sintácticos* : Demostración formal a través de reglas de deducción.
      - *Metodos semánticos* : Busca un contraejemplo que demuestre que no es satisfacible.

*** Poder expresivo y límites de la Lógica Proposicional
- Necesita conocer con antelación el número de variables.
- No tiene componente temporal.

*** Métodos deductivos semánticos y coste computacional
**** Método del árbol semántico
- [[id:IntArt]] pag 41 y apuntes de lógica [[file:~/.emacs.d/orgroam/20241018185521-uned_logica.org][Logica y Estructuras Discretas]].
- Se usa el *tableau*. también conocido como árbol semántico o tablero semántico.
      - Es un método no determinista. Se elige de forma casual entre varias posibilidades.
      - Si se cierran todas las rammas la fórmula no es satisfacible.

- Algoritmo basado en árboles semánticos
#+begin_src pseudocode
Entrada: phi_1 && ... && phi_n -> phi
Transforma entrada en la fórmula phi_1 && ... && phi_n && !phi
bucle
    si Existe una rama abierta y
       una regla que se puede aplicar a una fórmula phi en esa rama entonces
        Aplica la regla correspondiente a phi y convierte phi en NO ACTIVA
    fsi
    si Existe una rama que contiene una contradicción entonces
        Cierra la rama
    fsi
fbucle
si Existe por lo smenos una rama abierta entonces
    Devuelve SATISFACIBLE
fsi
si Todas las ramas están cerradas entonces
    Devuelve NO SATISFACIBLE
fsi
#+end_src

**** El método de resolución
- método basado en el reconocimiento de pares de (formula, negación).
- $(\phi_1 \lor \dots \lor \phi_n)$ se denomina *cláusula*.
- *forma normal conjuntiva* : fórmula expresada como conjunción de cláusulas.
- Se busca poner $\lnot$ delate de cada símbolo proposicional.
- Se busca que $\land$ sea la conectiva dominante.
- El resto son disyunción de literales separados por $\lor$.
- Se eliminan las clásulas con tautologías.
- Por último se aplica la regla de resolución a dos cláusulas de forma iterativa hasta que obtenermos la cláusula vacía.
      - por ejemplo si $(p \lor q \lor \lnot r)\land (p \lor \lnot q \lor \lnot s)$ entonces se añade.
      - $(q \lor \lnot r \lor \lnot s)$, $q$ no aporta nada al resultado.
      - Si hay una cláusula vacía significa que hemos encontrado una contradicción.
            - tipo $p\land \lnot p$
            - Entiendo que la entrada es una consecuencia.
- Dos fórmulas pueden tener formas muy distintas y significados iguales o opuestos.
      - Puede ser necesario transformarlas en una forma común.
- Reglas de expansión de fórmulas.
      - $\phi \leftrightarrow \psi$ = $\phi \to \psi \land \psi \to \phi$
      - $\phi \to \psi$ = $\lnot \phi \lor \psi$
      - $\lnot(\phi \land \psi)$ = $\lnot \phi \lor \lnot \psi$ (ley de De Morgan)
      - $\lnot(\phi \lor \psi)$ = $\lnot \phi \land \lnot \psi$ (ley de De Morgan)
      - $\lnot \lnot \phi$ = $\phi$
      - $\phi \land (\psi \lor \varphi)$ = $(\phi \land \psi) \lor (\phi \land \varphi)$
      - $\phi \lor (\psi \land \varphi)$ = $(\phi \lor \psi) \land (\phi \lor \varphi)$

#+begin_src pseudocode
Entrada phi_1 && ... && phi_n -> phi
Transforma la entrada en phi_1 && ... && phi_n && !phi
Transforma la fórmula obtenida en el conjunto de cláusulas Gamma_1,..., Gamma_k y elimina las
  cláusulas que contienen p y !p
bucle
    si Existen dos cláusulas Gamma_i, Gamma_j que
      pueden ser utilizadas para aplicar la regla de resolución entonces
        Aplica la regla de resolución obteniendo Gamma' y añade Gamma' al conjunto
    fsi
fbucle
si Si aparece la cláusula vacía en el conjunto entonces
    dev NO SATISFACIBLE
fsi
si Si no aparece la cláusula vacía entonces
    dev SATISFACIBLE
fsi
#+end_src

**** Optimizar la resolución: Cláusulas de Horn
- Si en un conjunto de cláusulas todas tienen una forma llamada de Horn, entonces el problema de la satisfacibilidad tiene una complejidad inferior.
- Cláusula Horn es:
      - un átomo.
      - Una implicación tal que el antecedente es una conjunción de litarales positivos, ye el consecuente es un solo literal positivo.
      - Una implicación tal que el antecedente es una conjunción de litarales negativos, y el consecuente es vacío.
- Ejemplos
      - $p \land q \land r \to s$
      - $p_1 \land \dots \land p_{k-1} \to p_k$
- Tiene un tiempo de evaluación $O(n)$

** Lógica de primer orden (LPO)
- Lógica de predicados.
- [[id:IntArt]] pag 46

*** Sintaxis y semántica
- Se introducen *variables* *cuantificadores* y *predicados* (como propiedades hombre(socrates)).
- Gramática abstracta
      - $t::= a | x | f(t_1, \dots , t_k)$,
      - $\phi ::= p(t_1, \dots, t_n) | \lnot \phi | \phi \land \psi | \exists x \phi (x)$
      - el predicado $p$ es de aridad $n$.
      - $\phi(x_1, \dots , x_n)$ denota una fórmula de $n$ variables libres.
      - $\forall$ es quivalente a $\lnot \exists \lnot$
- Todas las conectivas del LP forman parte del LPO.
- Se interpreta a partir de un dominio $D$, que son los posibles valores de las variables $x$ $y$.
      - $M\models p^n(t_1,\dots,t_n)$ si y solo si $(I(t_1), \dots ,I(t_n)) \in \hat{p}^{n}$
            - $I$ interpretación
                  - relación n aria subconjunto de $D_1\times \dots \times D_n$
            - $\hat{p}^{n}$ interpretación de $p^n$
      - $M \models \not \psi$ si y sólo si no es verdad $M\models \psi$
      - $M\models \psi \land \varphi$ si y sólo si $M\models \psi$ y $M\models \varphi$
      - $M \models \exists x \psi(x)$ si y solo si existe un elemento $d \in D$ tal que $M \models \psi [x/d]$
            - $\psi [x/d]$ : todas las ocurrencias libres de $x$ se han sustituido por $d$.
- El dominio $D$ puede ser infinito.
- [[id:IntArt]] pag 48, ejemplo con dimensión temporal.

*** Poder expresivo y límites de la lógica de primer orden
- La complejidad de las fórmulas es un problema.
- Más poder expresivo = más complejidad computacional = métodos dductivos más complicados

*** Métodos deductivos y coste computacional
**** Método del árbol semántico
- [[id:IntArt]] pag 50, ejemplo de un árbol semántico infinito.
- El problema de satisfactibilidad es indecidible en LPO.
      - No existe ningún algoritmo que cumpla las condiciones:
            1. *Es correcto* : nunca devuelve respuestas equivocadas.
            2. *Es completo* : devuelve todas las respuestas correctas.
            3. *Es terminante* : nunca entra en un bucle infinito.
- Mismas reglas que en el paso de LP más las siguentes.
      - Cuantificador *universal*, $\forall x \phi(x)$ : para todas las constantes $a$ que han sido evaluadas en la rama evaluaremos $\phi(a)$. Además permanece activa.
      - Cuantificador *existencial*, $\exists x \phi(x)$ : es preciso introducir una nueva constante $a$ que no haya sido introducida en ninguna rama abierta, y evaluamos $\phi(a)$

**** El método de resolución
- Más complicado que en el caso de LP, problemas nuevos:
      - Los cuantificadores en la fase de transformación de la fórmula de salida en forma clausal.
      - El reconocimiento de las fórmulas atómicas contradictorias, cuando éstas contengan variables o términos.
- Transformación de $\phi$ en forma clausual.
      - Debemos poner todos los cuantificadores en la parte izquierda de la fórmula.
            - *forma prenexa* : los cuantificadores en la parte izquierda.
            - Siempre existe una equivalencia a *forma prenexa*.
      - Reglas para la *forma prenexa*:
            - $\psi \circ Qx\varphi(x) = Qx(\psi \circ \varphi(x))$, donde $x$ no aparece libre en $\psi$.
            - $\psi \circ Qx\varphi(x) = Qy(\psi \circ \varphi(y))$, donde $x$ aparece libre en $\psi$ y la variable y es nueva.
            - donde $\circ \in \{\land, \lor\}$ y $Q\in\{\forall, \exists\}$.
- Se demuestra que la formula no es satisfacible sobre el dominio *Herbrand*.
- Una vez en forma prenexa se deben aplicar los cuantificadores y pasar a la forma *normal Skolem*.
      - Es satisfacible si y solo sí lo es la fórmula original.
      - Pero no coincide con el mismo conjunto de modelos.
- Forma normal skolem se aplican las siguientes reglas de forma recursiva.
      - Transformar $\forall x \phi(x)$ en $\phi(x)$
      - Transformar $\exists x \phi(x)$ en $\phi(a)$ si no hay cuantificadores $\forall$ a la izquierda.
            - sino en $\phi(f(x_1, \dots, x_n))$ por cada cuantificador $\forall_1, \dots, \forall_n$ a la izquierda del $\exists$
- *problema de la unificación* : en una fórmula en forma normal skolem puede aparecer $p(x)$ y $\lnot p(a)$.
      - Que es una contradición porque $p(x)$ viene de un $\forall$.

- Algorirmo de unificación de términos.
#+begin_src pseudocode
Entrada: dos cláusulas Gamma_1 y Gamma_2, y dos fórmulas atómicas p(t_1,...,t_n) in Gamma_1,
  !p(s_1,...,s_m) in Gamma_2

si n != m entonces
  dev NO y terminal
fsi
Introduce las ecuaciones t_1  = s_1,...t_n=s_n
bucle
    si Existe una ecuación t_i = s_i que no ha sido utilizada todavía entonces
        si (t_i = f(u_1,...,u_k) y s_i = g(v_1,...,v_h) y ((f!=g) o (k!=h))) o (t_i=x y s_i es un término donde aparece x y(s_i != x)) entonces
            dev NO y terminal
        fsi
        si t_i = f(u_1,...,u_k) y s_j = f(v_1,...,v_h) y k=h entonces
            Introduce las equaciones u_1 = v_1, u_k=v_k
        fsi
        si t_i=x u s_i=x, o t_i=a y s_i=a entonces
            Elimina la equación
        fsi
        si t_i = x y s_i es un término donde no aparece x entonces
            Aplica la sustitución x=s_i en la cláusula Gamma, en cualquier literal donde aparece el término t_i
        fsi
        si t_i=x es un término y s_i=y entonces
            Elimina la ecuación y añade el término x=y al conjunto
        fsi
    fsi
fbucle
si hemos considerado todas las ecuaciones, aplicado todas las sustituciones y no hemos contestado negativamente entonces
    Devuelve SI
fsi
#+end_src

- El algoritmo de resolución
#+begin_src pseudocode
Entrada: phi_1 && ... ** phi_n -> phi
Transforma la fórmula de salida en forma prenexa.
Transforma la fórmula en forma Skolem y represéntala en forma clausual. Eliminando las fórmulas que contienen tautologias.
bucle
    si Existen dos cláusulas Gamma_i, Gamma_j tales que contienen dos predicados p(t_1,...,t_n) y !p(t_1,...,t_n), y t_1 y s_1 son términos unificables entonces
        Aplica sustitución correspondiente a Gamma_i Gamma_j
        Obten la nueva cláusula resultante Gamma y añádela al conjunto de cláusulas
    fsi
fbucle
si Una de las cláusulas es vacía entonces
    dev NO SATISFACIBLE
fsi
#+end_src

*** Lógicas de orden superior al primero
- Mucho poder expresivo.
- lógicas de segundo orden permiten aplicar cuantificadores sobre elementos del dominio como sobre conjuntos de elementos.
      - $\forall x \phi(x)$ y $\forall X \phi(X)$
- Permiten comparar los tamaños de conjuntos.
- *lógica no recursivamente enumerable* : las lógicas superiores al 1er orden son tan complejas que en casos no existen algoritmos para averiguar si una fórmula es válida (tautología) o es satisfacible.

*** Fragmentos de LPO
- [[id:IntArt]] pag 56
- $L$ es un subconjunto (fragmento) de $L'$, permite mejorar la computabilidad.
      - Lógicas con un número limitado de variables.
      - Fragmentos con guardia.
      - Fragmentos con aridad máxima.

** Extensiones de las lógicas clásicas
- lógicas modales están entre LP y LPO.

*** Lógicas no monotónicas, razonamiento del sentido común y otras consideraciones
- [[id:IntArt]] pag 58. diferencias lógica monótona (clásica) y no monótona.
      - Interesante que en la lógica clásica una nueva verdad no puede eliminar una verdad anterior.
- *lógica difusa o borrosa* : lógica multievaludada, donde las proposiciones tienen un grado de verdad.

*** Lógicas modales (LM) y mundos posibles
- [[id:IntArt]] pag 59
- Lógica con características del cuantificador de existencia $\exists$.
- Gramática forma extendida de la LP.
      - $\phi ::= p | \lnot \phi | \phi \land \psi | \lozenge \psi$
      - $\Diamond$ : cuantificador existencial $\exists$ que permite desplazarse entre los mundos.
            - $\Diamond \phi$ se lee como $\phi$ es posible.
      - $\square$ expresa que una propiedad es cierta en todos los mundos alcanzables.
            - $\square = \lnot \Diamond \lnot$
            - $\square \phi$ se lee como $\phi$ es necesaria.
- un modelo de lenguaje modal es una terna $M=(W,R,V)$
      - $W$ : es un conjunto de mundos.
      - $R$ : relación binaria $R \subseteq W \times W$
      - $V$ : función de evaluación por cada uno de los mundos, nos dice que símbolos proposicionales se satisfacen.
      - Piénsalo como una máquina de estados.
- Ejemplos de lenguajes modales en el [[id:IntArt]] pag 60.
- La satisfacibilidad depende de:
      - Las propiedades de $R$.
      - El mundo en el que evaluamos la fórmula.
      - Una fórmula $phi$ es satisfacible si y solo si existe un un modelo $M$ y un mundo $w_i$ tal que.
            - $M,w_i \Vdash \phi$
      - $\phi$ válida en un modelo $M$ : $M$ se satisface en todos los mundos $w_i$.
      - $\phi$ válida : si y solo si es válida en todos los modelos modales posibles.

*** Métodos deductivos y coste computacional de la Lógica Modal
**** Árboles semánticos para K
- Reglas de resolución como las de LP más:
      - $\lnot \Diamond \phi = \square \lnot \phi$
      - $\lnot \square \phi = \Diamond \lnot \phi$

#+begin_src pseudocode
Input: phi_1 && ... && phi_n -> phi
Transforma el input en phi_1 && ... && phi_n && !phi

Elimina todo los símbolos de implicación utilizando la correspondiente regla de LP

Transforma la fórmula obtenida en NNF

bucle
    si Hay por lo menos un mundo en el que aparece una fórmula activa phi no expandida aun entonces
        si phi es una fórmula proposicional del Tipo psi || tau entonces
            cambia psi a no activa y pon en el mundo actual psi o tau en estado activo eligiendo de forma no determinista*
        fsi
        si phi es una fórmula proposicional de cualquier otro Tipo entonces
            cambia phi a no activa, aplica la regla correspondiente y expande la fórmula en el mundo actual, poniendo las fórmulas resultantes en estado activo
        fsi
        si hay un mundo en el que aparece una contradicción entonces
            vuelve atrás a la última elección no determinista*, Si hay, o devuelve NO STAISFACIBLE en caso contrario
        fsi
    fsi
fbucle
dev SATISFACIBLE
#+end_src

** Aplicaciones: el ejemplo de las lógicas temporales
- [id:IntArt] pag 64
- lógicas temporales son una variante peculiar de la lógica $k$.

*** Tipos de lógicas temporales
- El tiempo puede verse como un conjunto de *puntos ordenados* o como un *conjunto de intérvalos*.
- *puntos ordenados* puede verse como mundos modales.
- Las estructuras temporales no lineales permiten modelar diferentes futuros o pasados.

*** Lógicas temporales basadas en puntos
- $F$ denota la modalidad unaria sobre puntos para el futuro.
- $P$ su correspondiente para el pasado.
- *LTL*[F,P] : linear time logic, uno de los lenguajes temporales más sencillos.
      - gramática abstracta de LTL[F,P]
            - $\phi ::= p | \lnot \phi | phi \land \psi | F \phi | P \phi$
            - $F$ y $P$ son iversas una de la otra.
      - Semántica, En LTL[F,P] un modelo $M$ y un mundo $w_i$ satisface $\phi$ si y solo si:
            - $M,w_i \Vdash F\phi$ si y solo si existe un mundo $w_j$ en el futuro de $w_i$ tal que $M,w_j \Vdash \phi$.
            - $M,w_i \Vdash P\phi$ si y solo si existe un mundo $w_j$ en el pasado de $w_i$ tal que $M,w_j \Vdash \phi$.
      - $\lnot F \lnot$ se denota como $G$. "en su futuro".
            - $F(p \land \lnot F \lnot q)$ : en el futuro valdrá $p$ y en el futuro de ese momento valdrá $q$.
      - $\lnot P \lnot$ se denota como $H$. "en su pasado$."
- *LTL* : otra lógica temporal, operadores sinze $S$ y until $U$.
      - Gramática abstracta de LTL
            - $\phi ::= p | \lnot \phi | \phi \land \psi | \phi S \psi | \phi U \psi$
      - Semántica:
            - $M,w_i \Vdash \phi U \psi$ si y solo si existe un mundo $w_j$ en el *futuro* tal que $M,w_j \Vdash \psi$, Y en todos los mundos entre $w_i$ y $w_j$ $M,w \Vdash \phi$
            - $M,w_i \Vdash \phi S \psi$ si y solo si existe un mundo $w_j$ en el *pasado* tal que $M,w_j \Vdash \psi$, Y en todos los mundos entre $w_i$ y $w_j$ $M,w \Vdash \phi$
      - Más expresivo que LTL[F,P]
            - $F\phi$ equivale a $\top S \phi$
- *CTL** Tiene en cuenta los diferentes futuros posibles.
      - $A$ operador modal de todos los futuros posibles [cuantificador sobre caminos].
      - $E$ operador modal de que permite elegir un futuro posible [cuantificador sobre caminos].
      - Gramática abstracta
            - $\phi ::= p | \lnot \phi | \phi \land \psi | \phi S \psi | \phi U \psi | A \phi | E \phi$
      - Muy expresiva y con complejidad computacional muy alta.
- *CTL* es una restricción de CTL* para ser usada en el problema de /control de modelo/.
      - Se obliga a los cuantificadores sobre caminos a ser usados al mismo tiempo que los operadores de tiempo  de LTL.
      - Gramática abstracta
            - $\phi ::= p | \lnot \phi | \phi \land \psi | A(\phi U \psi) | E(\phi U \psi)$
      - *model checking* permite automatizar la tarea de verificación de los requisitos de un proyecto.

*** Lógicas temporales basadas en intérvalos
- [id:IntArt] pag 68
- Cuando las propiedades en las que espamos interesados tienen una duración.
      - Ya no es tan importante el punto preciso en el tiempo.
- Las relaciones entre intérvalos son complicadas.
- Relaciones entre intérvalos:
      - ends
      - during
      - begins
      - overlaps
      - meets
      - before
- HS, lógica proposicional de las relaciones Allen.
      - Sintaxis abstracta
            - $\phi ::= p | \lnot \phi | \phi \land \psi | \langle B \rangle \phi | \langle E \rangle\phi | \langle\bar{B}\rangle\phi | \langle\bar{E}\rangle\phi$
      - Viene determinada por un modelo $M$ y un mundo que se suele denotar como un par ordenado de puntos.
            - $M,[d_0,d_1] \Vdash \langle B \rangle \phi$ si $M,[d_0, d_2] \Vdash \phi$ para algún $d_2$ tal que $d_0 \leq d_2 <d_1$;
            - $M,[d_0,d_1] \Vdash \langle E \rangle \phi$ si $M,[d_2, d_1] \Vdash \phi$ para algún $d_2$ tal que $d_0 < d_2 \leq d_1$;
            - $M,[d_0,d_1] \Vdash \langle \bar{B} \rangle \phi$ si $M,[d_0, d_2] \Vdash \phi$ para algún $d_2$ tal que $d_1 < d_2$;
            - $M,[d_0,d_1] \Vdash \langle B \rangle \phi$ si $M,[d_2, d_1] \Vdash \phi$ para algún $d_2$ tal que $d_2 < d_0$;

* Conjuntos Borrosos
- [id:IntArt] pag 264
- predicados precisos: impar o par
- predicados vagos: alto o bajo
      - Protagonizan el lenguaje natural y constituyen un elemento fundamenta de la capacidad de abstracción.
- Teoría de conjuntos borrosos,herramientas formales para el análisis de predicados vagos.
      - Ciencia del razonamiento aproximado.

** Conjuntos borrosos
- [id:IntArt] pag 264
- En un predicado preciso $P$ sobre un conjunto $U$ podemos escribir la siguiente función $\mu_P(u)$

\begin{equation*}
\mu_P(u) = \left\{\begin{array}{lc}{0 & si\ u \notin} P \\ 1 & si\ u\in P}
\end{equation*}

- En un conjunto borroso en cambio un predicado $V$, $V \in U$ mediante la función $\mu_V(u)$.

\begin{equation*}
\mu_V : U \to [0,1]
\end{equation*}

- Algunos elementos son ciertos en un determinado grado $0 < \mu_V(u) < 1$.
- La función de pertenencia $\mu_V$ proporciona una ordenación del conjunto de individuos.
      - Nos permite decir si $u$ es más o menos alto qe $w$.
- La elección de la función de pertenencia es una cuestión de diseño.
- Conjuntos asociados a $\mu_V$
      - *Soporte* : $\{u \in U : \mu_V(u) > 0\}$
      - *Núcleo* : $\{u \in U : \mu_V(u)=1 \}$
            - Los elementos del núcleo se denominan /prototipos/ de V
- Un conjunto $V$ es *convexo* si $\forall u, u', u'' \in U,\ u' \in [u,u''], \mu_V(u') \geq \min\{\mu_V(u), \mu_V(u'')\}$
- Un conjunto $V$ está normalizado si $\exists u \in U$, tal que $\mu_V(u)=1$.
- $\alpha-corte$ , $V_{\alpha}$ se define como $\{u \in U : \mu_V(u) \geq \alpha\}$
      - Son como subconjuntos anidados.
- $A$ está embebido en $B$ ($A \subseteq B$) si $\forall u \in U$ sucede que $\mu_A(u) \leq \mu_B(u)$.

** Semántica de los conjuntos Borrosos
- [id:IntArt] pag 266
- Semánticas:
      - *Similitud* : Sea $V$ un conjunto borroso.
            - $\mu_V(u)$ es el grado de proximidad a los /prototipos/ de $V$
            - De interés para la abstracción de un conjunto de datos mediante alguna medida de proximidad.
            - También caracteriza a los sistemas de control donde la diferencia entre la situación acutal y la deseada (prototipo), determina la realización de acciones de corrección.
      - *Preferencia* : Supongamos que $V$ reúne a un conjunto de elementos entre los cuales existe alguna preferencia.
            - $\mu_V(u)$ representa el grado de preferencia entre dichos elementos.
            - Propio de problemas de decisión,
      - *Incertidumbre* : Dada una variable que toma valores en $U$, el predicado "x toma un valor pequeño" se modela mediante un conjunto borroso $V \in U$.
            - Función de pertenencia $\mu_{V=pequenio}$
            - Si el valor exacto es desconocido entonces $\mu_{V=pequenio}$ funciona como una medida de posibilidad de que $x$ sea $u \in U$.
            - se representa como $\pi_x(u) = \mu_{V=pequenio}(u),\ \forallu \in U$
            - Cuando la reunión de pertenencia modela una distribución de posibilidad.
                  - Los elementos que perteneven al soporte son mutuamente excluyentes.
- Las semánticas no son excluyentes.

** Teoría de conjuntos borrosos
- [id:IntArt] pag 268
- Se quiere dar una representación del significado de sentencias que aparecen en el lenguaje natural.
- Con predicado precisos resulta muy sencillo realizar operaciones sobre conjuntos.
      - unión, intersección, negación
- tabla 7.1 contiene las propiedad de la álgebra de boole. pag 268.
- Operaciones de composición de predicados precisos utilizando funciones de pertenencia.
      - $\mu_{\bar{A}} = 1 - \mu_A(u)$  (complemento a 1)
      - $\mu_{A \cap B} (u) = \min\{\mu_A(u), \mu_B(u)\}$
      - $\mu_{A \cup B} (u) = \max\{\mu_A(u), \mu_B(u)\}$
- $\{0,1\}^U$ es el conjunto de funciones $\mu : U \to \{0,1\}$
      - $(\mathcal{P}(U), \cup, \cap, \bar{ }\ )$ y $(\{0,1\}^u, \max, \min, 1-x)$ son isomorfos.
- Aplicado a conjuntos Borrosos
      - Tanto $A$ como $B$ son conjuntos borrosos de $U$.
      - $n:[0,1] \to [0,1]$ tal que $\mu_{\bar{A}}(u) = n(\mu_A(u))$
            - Debe satisfacer $n(1)=0$ y $n(0)=1$.
            - Debe satisfacer $\forall x,y \in [0,1],\ x \leq y \Rightarrow n(x) \geq n(y)$
            - Se denomina función /negación/.
            - $n(x) = 1-x$ es común y además verifica que $n(n(x))=x$
      - $T:[0,1]^2 \to [0,1]$ tal que $\mu_{A \cap_T B}(u) = T(\mu_a(u), \mu_b(u))$
      - $S:[0,1]^2 \to [0,1]$ tal que $\mu_{A \cup_S B}(u) = S(\mu_A(u), \mu_b(u))$
      - Propiedades de $T$ y $S$.
            1. Ley de identidad: $\forall x \in [0,1]$
                   - $T(x,1) = x\ \ (A \cap U = A)$
                   - $S(x,0) = x\ \ (A \cup \emptyset = A)$
            2. Ley conmutativa: $\forall x,y \in [0,1]$
                   - $T(x,y)=T(y,x)$\ \ (A \cap B = B \cap A)$
                   - $S(x,y)=S(y,x)$\ \ (A \cup B = B \cup A)$
            3. Ley asociativa: $\forall x,y,z \in [0,1]$
                   - $T(x,T(y,z)) = T(T(x,y),z)\ \ (A\cap(B \cap C) = (A \cap B) \cap C)$
                   - $S(x,S(y,z)) = S(S(x,y),z)\ \ (A\cup(B \cup C) = (A \cup B) \cup C)$
            4. Ley de monotonía: $\forall x,y,u,v \in [0,1],\ x \leq u,y\leq v$
                   - $T(x,y) \leq T(u,v)$
                   - $S(x,y) \leq S(u,v)$
      - Funciones *normas triangulares* o *t-normas* : que satisfacen las propiedades de $T$.
      - Funciones *conormas triangulares* o *t-conormas* : que satisfacen las propiedades de $S$.
      - De la ley de identidad y monotonía se deduce.
            - $T(0,x)=0$ y $S(1,x)=1$
- Propuestas para pares t-norma y t-conorma.
      - *Máxima y mínimo*
            - $T_Z(x,y) = \min(x,y)\ \ S_z(x,y) = \max(x,y)$
      - *producto y suma*
            - $T_G(x,y)=xy \ \ S_G(x,y)= x+y-xy$
      - *t-norma y t-conorma de Lukasiewicz*
            - $T_L(x,y) = \max(x+y-1,0)\ \ S_L(x,y)=\min(x+y,i)$
      - Se pueden escoger según sus propiedades.

* Sistemas basados en Reglas (SBR)
- [id:IntArt] pag 83
- *SBR* : son sistemas de deducción en lógica proposicional restringitos a clausulas de Horn.
      - Permiten capturar la experiencia humana en la resolución de problemas, con el fin de alcanzar decisiones consistentes y repetibles.
- Estructuras de representación declarativas.
      - Conocimiento del dominio *Factual* : Conocimiento aceptado y consensuado.
      - Conocimiento del dominio *heurístico* : Menos riguroso basado en experiencias propias.
- *Motores de inferencias* : Mecanismos de deducción utilizados controlan las etapas que se deben llevar a cabo para resolver un problema.

** Componentes básicos de los SBR
- *BC* : base de conocimiento.
- *MI* : mecanismo de inferencia.
- *BH* : Base de hechos, como memoria de hechos establecidos.
      - Pueden ser sensores por ejemplo.

*** Base de Hechos (BH)
- [id:IntArt] pag 84
- Contiene la información actual del problema.
      - Metas a alzanzar e hipótesis.
      - Estado actual del problema en curso de solución.

*** Base de Conocimiento (BC)
- [id:IntArt] pag 85
- Regla:
      - Condición o antecedente -> acción o consecuente.
      - Condición : lista de cláusulas a verificar.
            - Algún tipo de test sobre el BH.
      - Consecuente : lista de acciones a ejecutar.
            - Puede cambiar el contenido del BH.
- Se lée SI <condición> ENTONCES <consecuente>
- El BH también contiene:
      - Conjunto de hechos deducidos por el sistema en un encadenamiento hacia delante.
      - Conjunto de metas que debe alzanzarse e hipótesis avanzadas durante el transcurso de una solución si el encadenamiento es hacia atrás (check de la verificación de las cláusulas).

*** Motor de inferencias (MI)
- [id:IntArt] pag 87
- También estategia de control o intérprete de reglas.
- Examina el BH y decide qué reglas se disparan.
- Algoritmo independiente del BC.
- Motor de inferencias genérico
      - *Búsqueda informada* : Sin ningún conocimiento
            - coste computacional más bajo.
            - Pero mayor coste de aplicación de reglas (peor filtro).
      - *Búsqueda informada* : Con algún conocimiento acerca del problema
            - Mayor coste computacional.
            - Pero menor coste al aplicar las reglas (mejor filtro).
#+begin_src pseudocode
BH <- HechosIniciales;
MIENTRAS !VerificaCondiciónFin(BH) || NoSeEjecutaAcciónParada HACER
    ConjuntoConflicto <- Equiparar(BC,BH);  // Seleccionar reglas compatibles
    R <- Resolver(ConjuntoConflicto);       // Proceso de búsqueda (informada o desinformada)
    NuevosHechos <- Aplicar(R,BH);
    Actualizar(BH, NuevosHechos);
FIN-MIENTRAS
#+end_src

** Inferencia
- [id:IntArt] pag 88
- Red de inferencia : red de notos.
      - antecedente -> (nodo) -> consecuente
      - Se encadenan varios nodos : antecedente -> (nodo) -> consec/ante -> (nodo) -> consecuente2.
      - *Punto de partida* : Antecedente que no es consecuente de otras reglas.
      - *Meta* : Consecuente que no es antecendente de ninguna otra regla.
- *Encadenamiento hacia delante* : Colección de hechos o afirmaciones de partida.
      - Aplica reglas de la BC repetidas veces hasta que no se generen nuevos hechos.
      - Una regla se puede aplicar si las cláusulas del antecedente se verifican.
      - Cada vez que se aplica una regla se almacena el consecuente en el BH.
      - Se recorre la red de inferencia hacia delante (izquierda - derecha).
- *Encadenamiento hacia atrás* : Parte de un conjunto de hipótesis que intenta verificar usando datos de la BH.
      - Se recorre la red de inferencia hacia detrás (derecha - izquierda).

*** Encadenamiento hacia delante
#+begin_src pseudocode
BH <- HechosIniciales;
ConjuntoConflicto <- ExtraeCualquierRegla(BC);

MIENTRAS NoContenida(Meta, BH) && NoVacío(ConjuntoConflicto) HACER
    ConjuntoConflicto <- Equiparar(Antecedente(BC), BH);
    SI NoVacío(ConjuntoConflicto) ENTONCES
        R <- Resolver(ConjuntoConflicto);  // Selección de las reglas
                                           //  Depende de la estratégia de selección.
        NuevosHechos <- Aplicar(R, BH);
        Actualizar(BH, NuevosHechos);
    FIN-SI
FIN-MIENTRAS
SI Contenida(Meta,BH) ENTONCES
    DEV "Éxito";
FIN-SI
#+end_src

- *Principio de refracción* : Solo se permite aplicar una regla una sola vez.

- Ejemplo en [id:IntArt] pag 90.

**** Ciclo de reconocimiento-acción
- Proceso iterativo de aplicación del encadenamiento hacia delante.
- Los inconvenientes vienen de la falta de focalización en la meta.
      - La fase de resolución de conflictos es crítica.
      - El disparo de reglas elegidas favorece la explosión combinatoria.
      - Se necesitar cargar todas las afirmaciones que se poseen en la BH.

*** Encadenamiento hacia atrás
- [id:IntArt] pag 97
- Se trata de determinar si el objetivo se verifica o no.
- Teniendo en cuenta el contenido del BH.
- Tranta de encontrar reglas cuyo consecuente contenga el objetivo a verificar.

#+begin_src pseudocode
BH <- HechosIniciales;
SI Verificar (META,BH) ENTONCES
    DEV "éxito";
SINO
    DEV "fracaso";
FIN-SI
#+end_src

- Procedimiento *Verificar*

#+begin_src pseudocode
Verificado <- Falso;
SI Contenida(Meta, BH) ENTONCES
    DEV true;
SINO
    ConjuntoConflicto <- Equiparar(Consecuentes(BC), Meta);
    MIENTRAS NoVacío(ConjuntoConflicto) && !Verificado HACER
        R <- Resolver(ConjuntoConflicto);
        Eliminar(R, ConjuntoConflicto);
        NuevasMetas <- ExtraerAntecedentes(R);
        Verificado <- true;
        MIENTRAS NoVacío(NuevasMetas) && Verificado HACER
            Meta <- SeleccionarMeta(NuevasMetas);
            Eliminar(Meta,NuevasMetas);
            Verificado <- Verificar(Meta,BH);
            SI Verificado ENTONCES
                Añadir(Meta, BH);
            FIN-SI
        FIN-MIENTRAS
    FIN-MIENTRAS
    DEV Verificado;
FIN-SI
#+end_src

- Ejemplo en [id:IntArt] pag 98

**** Ciclo de encadenamiento hacia atrás
- Ciclo de inferencias
      1. *Etapa de equiparación* : Búsqueda de las reglas cuya conclusión se corresponda con la meta M en curso.
      2. *Etapa de resolución de conflictos* : Selección de una regla entre las dadas en el conjunto conflicto.
      3. *Etapa de acción* : Reemplazamiento de la meta M por la conjunción de las condiciones del antecedente de la regla seleccionada.

- Problemas con bucles infinitos.
- Ventajas:
      - Solo plantea cuestriones al usuario cuando tiene necesidad de hacerlo.
      - Reduce el cúmero de equiparaciones de reglas.
      - Disminuye la dimensión del árbol de búsqueda.

*** Reversibilidad
- Usar encadenamiento hacia delante o hacia atrás depende del problema
- Estrategias basadas en la red de inferencia:
      - Número elevado de reglas con muchas condiciones mejor encadenamiento hacia delante.
      - Muchas reglas cuyo consecuente forma parte del antecedente de otras mejor encadenamiento hacia atrás
      - Claros los datos de entrada pero no tan claros los objetivos mejor hacia delante.
            - *Razonamiento conducido por los datos*.
            - Apropiado para tareas reactivas.
      - Si los objetivos y subojetivos están bien definidos pero no así las estructuras de los datos mejor encadenamiento hacia atrás.
            - *Razonamiento conducido por objetivos*.
            - Apropiado para tareas anaíticas.
      - Los SBR que deban justificar su razonamiento deben adaptar la dirección que mejor se adapte a la forma de pensar del usuario del sistema.
- *Búsqueda bidireccional* : Seguir ambas direcciones hasta que los dos caminos de búsqueda se encuentran.
      - Requiere:
            - Incorporar en BH datos iniciales y metas a alcanzar. 
            - Distinguir entre reglas a aplicar hacia delante (tipo A) y reglas aplicables hacia atrás (tipo B).
            - Diseñar la condición de terminación para que considere tanto la parte de descripción de los datos inferidos como de las metas a alcanzar.
            - Modelar el mecanismo de control para que decida en cada etapa si aplica una regla tipo A o tipo B
      - Adecuada si el número de nodos en cada paso crece exponencialmente.
      - Para búsquedas totalmente desinformadas basadas en divide y vencerás es efectiva.
      - Corre el peligro que la búsqueda hacia delante explore una rama diferente a la de la solución.
            - Hay que diseñar el sistema cuidadosamente.

** Técnicas de equiparación
- [id:IntArt] pag 104

*** Equiparación con variables
- El antecedente de la regla contiene variables.

**** Sintaxis de reglas con variables
- Sintaxis:
      - Cada elemento de condición en el antecedente debe ir entre parénesis y empezar por una constante.
      - Todos los elementos de condición del antecedente deben ir unidor por Y.
      - Elementos de condición formador por átomos.
            - Constante o variable.
            - Variables con un prefijo ?, por ejemplo ?p.
      - Elementos de condición pueden expresar alguna prueba.
            - Por ejemplo (test (< ?e 10)) es comprobar que e tienen menos de 10 años.
      - El consecuente también puede contener variables.
      - Acciones del consecuente puede contener predicados.
      - Ejemplo:
            - SI (paciente ?p) $\land$ (edad ?p ?e) $\land$ (síntoma ?p fiebte) $\land$ (síntoma ?p manchas-rojas) ENTONCES Añadir(enfermedad ?p varicela)
            - Paciente menor de 10 años con manchas rojas y fiebre $\to$ Paciente con varicela

***** Equiparación de reglas utilizando variables con los contenidos de la BH
- [id:IntArt] pag 106
- Un ejemplo de regla para que se entienda, es muy prolog
      - SI (caballo ?x) $\land$ (rápido ?x) ENTONCES (candidato-competición ?x)
- Variables distintas pueden tener el mismo valor.
      - SI (caballo ?x) $\land$ (padre ?x ?y) $\land$ (rápido ?y) ENTONCES ...
- Pueden haber condiciones negadas en una regla.
      - SI (caballo ?x) $\land$ $\lnot$(rápido ?x) ENTONCES (candidato-reserva ?x)

- *Instanciación* : par formado por una regla y los elementos del BH que equiparan dicha regla.
      - En la fase de acción se ejecuta una instanciación de la regla.
            - Añade nuevos hechos al BH.

**** El algoritmo RETE
- [id:IntArt] pag 109
- Evita examinar todas las reglas del BC con los datos del BH.
- Aprovecha dos propiedades
      - Agrupa las reglas según los patrones en sus condiciones.
            - *Red RETE* : Realizado por un compilador.
                  - Clasificación estructurada en forma de árbol.
                  - Cada nodo indica operaciones durante la equiparación.
                  - Cada arco indica el camino por donde fluyen los datos.
                  - Elimina reglas redundantes.
      - Guarda el resultado de la equiparación durante 1 ciclo.
            - Guarda *instanciaciones*, resultado de equiparaciones, de ciclo a ciclo.
            - Actualiza esta información con los cambios que se producen en la BH después de la ejecución de cada ciclo.
                  - Almacena las instanciaciones de ciclos anteriores que generaron nuevos datos en la BH.
                  - Para cada dato que se borra de la BH se eliminan las instanciaciones almacenadas a las que dio lugar ese dato.

** Técnicas de resolución de conflictos
- [id:IntArt] pag 111
- Selecciona a partir del conjunto de conflictos la instanciación a aplicar.
- Principales técnicas:
      1. Seleccionar la primera regla que se equipara con los condenidos de la BH.
             - Bajo coste de control.
             - Mayor coste de aplicación (Se prueban más reglas).
             - Se puede ordenar con técnicas de ordenación del BC:
                   - Ordenar las reglas en la BC, sin más misterio.
                         - Primero la que deba probarse antes.
                   - Ordenación de las condiciones dentro de cada regla.
                         - Primero las condiciones menor probables.
      2. Seleccionar la regla de prioridad más alta.
      3. Seleccionar las instancias más específicas.
      4. Seleccionar arbitrariamente una regla.
      5. Seleccionar las instanciaciones que tienen elementos más recientemente añadidos a la BH.
      6. Seleccionar una instanciación que no se haya ejecutado previamente.
             - Principio de refracción.
             - Dos instanciaciones de la misma regla con los mismos elementos se consideran diferentes si.
                   1. Una de ellas está en el conjunto conflicto algunos ciclos,
                   2. Desaparece del conjunto conflicto.
                   3. Vuelve a aparecer en el conjunto conflicto.
- Se suelen combinar las principales técnicas estableciendo una prioridad.
      - Ante la misma prioridad se hace la intersección de las dos técnicas.
            - Ambas evaluadas sobre el mismo conjunto.

** Ventajas e inconvenientes
- [id:IntArt] pag 116
- Las reglas del BC deben ser independientes entre sí.
- SBR con un BC muy grande incluir nuevas reglas puede provocar efector colaterales.
- Representación declarativa del concocimiento.
- Un SBR puede seguir el rastro facilmente del conjunto de reglas que aplicó.
      - Proporciona poder de autoexplicación.
- Un SBR puro no posee estructuras de control.

** Dominios de aplicación
- [id:IntArt] pag 118
- Dos clases de problemas:
      - Los que se pueden modelar como un conjunto de múltiples estados.
      - Los que vienen descritos por medio de una teoría concisa y unificada.

* Redes Semánticas y Marcos
- [id:IntArt] pag 132

** Introducción
- Representación del conocimiento:
      - Modelo conceptual : Representación del conocimiento de un dominio. Estructuras no computables modelizan el problema y la solución de un dominio concreto.
      - Modelo formal : Representación semicomputable.
      - Modelo computable : modelo formal totalmente operativo. formado por:
            - Base de conocimientos.
            - Motor de inferencias.
            - Estrategias de control.
- *formalizar* : representar simbólicamente el conocimiento.
      - Organizar de acuerdo a algún modelo de diseño.
      - Determinar métodos de inferencia.
- *Clasificación de los formalismos*:
      - *Formalismos bassados en conceptos* : Representan las principales entidades o clases del dominio.
            - Objeto-Atributo_Valor
            - Marcos
      - *Formalismos basados en relaciones* : Centran la atención entre las relaciones que existen entre los conceptos.
            - Lógica.
            - Redes semánticas.
            - Teoría de la dependencia conceptual.
      - *Formalismos basados en acciones* : Describen en conocimiento como un conjunto de acciones básicas.
            - Sistemas de producción
            - Guiones
- *Redes semánticas* : Grafo orientado por nodos y arcos unidireccionales, ambos etiquetados.
      - Nodos son conceptos.
      - Arcos son relaciones.
- *Marcos* : Estructura de datos para representar estereotipos.
      - Cada Marco : 1 nombre + conjunto de propiedades.
      - Los Marcos se unen mediante relaciones.
      - Hay herencia.

** Redes semánticas
- [id:IntArt] pag 133
- Paradigma basaso en relaciones.
- Grafo orientado:
      - Nodos etiquetados son conceptos.
      - Arcos unidireccionales etiquetados son relaciones.

*** Representación del conocimiento
- El signidicado de un cocepto de la red depende de la forma en la que se relaciona con otros conceptos.
- Problemas:
      - Falta de terminología adecuada.
      - Falta de semántica uniforme y precisa.
- En un grafo:
      - Nodo origen es el objeto
      - Arcos representan atributos
      - Nodos destino valores
- Tipos de arcos:
      - *Arcos descriptivos* : Describen entidades y conceptos.
            - Arcos que relacionan dos entidades independientes ya existentes.
            - Arcos utilizados para definir una nueva entidad.
      - *Arcos estructurales* : Enlazan las entidades o conceptos formando la arquitectura o estructura de la red.
            - La semántica de los arcos estructurales es independiente de los conocimientos del dominio.
            - Arcos estructurales básicos:
                  - *generalización* : herencia
                  - *instancia* : Liga un nodo genérico con un objeto concreto.
                        - un objeto
                  - *agregación* : Liga un objeto con sus componentes.
- Los conocimientos en una red semántica pueden expresarse usando *lógica proposicional* y *cálculo de predicados*.
      - predicados n-arios (superior a 2) no pueden ser representados en estas redes.

*** Representación de predicados no binarios
- [id:IntArt] pag 136
- Un nuevo objeto representa al predicado con de aridad mayor que dos.
      - Nuevos predicados binarios representan las relaciones binarias entre los atributos y los valores del nuevo objeto.

*** Representación de acciones
- [id:IntArt] pag 136
- Toda proposición contenida en una sentencia tiene una estructura formada por un verbo.
      - Y una o más frases nominales.
      - Cada frase nominal se relaciona con el verbo mediante un conjunto de *casos*:
            - Agente
            - Contra-agente
            - Objeto
            - Resultado
            - Instrumento
            - Origen
            - Propósito
            - Lugar
            - Tiempo
            - Sujeto
      - *modalidad* : Características del *verbo*
            - Tiempo : presente pasado o futuro.
            - voz : Activa o pasiva.
- diagrama en [id:IntArt] pag 138

*** Representación de conocimiento disjunto
- Se usa la etiqueta *disjunto* [id:IntArt] pag 138 F4.5.
- También existen unos arcos especiales para representar este tipo de conocimiento (Hendrix).
  Las etiquetas que usan estos arcos son:
      - S : Subconjunto
      - SD : Subconjunto
      - E : Elemento
      - ED : Elemento disjunto

** Inferencia de conocimiento en redes semánticas
*** Equiparación
- Una consulta, apunte o fragmento de red se quipara con una red, si el apunte se puede asociar con un fragmento de la red semántica.
- Pasos del proceso de equiparación:
      1. Se construye un apunte que responda a la pregunta
             - Apunto formado por un conjunto de :
                   - Nodos constantes : Nodos conocidos en la pregunta.
                   - Nodos variables : Los valores que se requieren.
                   - Arcos etiquetados : Unen nodos constantes y variables.
      2. Se coteja el apunte sobre la red semántica en la base de conocimiento.
      3. Los nodos variables se ligan a los nodos constantes de la red hasta encontrar una equiparación perfecta.
      4. La respuesta a la consulta es el fragmento de red semántica con los valores con los que se rellenan los nodos variables.

*** Herencia de propiedades
- [id:IntArt] pag 140
- Arcos *instancia* y *Subclase-de*.
- Se puede usar en sistemas que razonan dirigidos por la meta o por los datos.
- Pasos de consulta de propiedades
      - Consulta arcos que salen del nodo
      - Consulta arcos que salen del nodo conectado por la etiqueta instancia
      - Recursivamente consulta arcos que salen del nodo conectado como Subclase-de 
- Trabaja bien con propiedades que presentan excepciones en sus valores.

- Principales errores que se suelen cometer en la herencia:
      - No distinguir los nodos que son instancias de aquellos que son conceptos.
      - La etiqueta que da nombre al nodo o al arco tiene una semántica diferente al conocimiento que se quiere expresar.
      - Arco en sentido contrario.
      - No se han representado situaciones o acciones utilizando nodos situación.

** Marcos
- Técnica de representación de conocimientos más utilizada en IA cuando los conocimientos están organizados sobre conceptos.
- *Marcos* según Minsky : Estructura de datos que representa situaciones esteorotipadas construidas sobre situaciones similares ocurridas anteriormente.
      - Permite aplicar a situaciones nuevas conocimiento previo.
      - Se aplican conocimientos declarativos del dominio.
      - Conocimientos Procedimentales : Como usar el marco.
- Se organizan en árboles o grafos, llamados jerarquías.
- Técnicas de inferencia:
      - Equiparación
      - Herencia simple y múltiple
      - Valores activos y métodos : representan la conducta del sistema.

*** Representación de conocimiento
- *Marcos* : representar conceptos.
- *Relaciones* : dependencias entre conceptos.
- *Propiedades* : describir cada concepto.
- *facetas* : para expreser de múltiples formas los valores con los que se puede rellenar cada propiedad.

**** Representación de conceptos e instancias
- *Marcos clase* : Representan conceptos, clases o situaciones genéricas.
      - Descritos por propiedades con o sin valor.
- *Marcos instancia* : Representación en el dominio real de una clase determinada.
      - Deben estar relacionados como mínimo con un marco clase.
      - Se debe rellenar la información concreta de cada objeto.

**** Representación de relaciones entre conceptos
- *SBM* : sistema basado en marcos.
- Relaciones más usadas en el paradigma de marcos:
      - *Subclase-de* y su inversa *superclase-de*
      - *Instancia* y su inversa *representa*
      - *Fraternal*
      - *Disjunto*
      - *No disjunto*
      - *Ad-hoc* o "a medida"
- *Relaciones estándar* : independientes del dominio (subclase-de o instancia).
      - Permiten construir jerarquías de conocimientos estáticosdel dominio que se quiere modelar.
- *Relaciones no estándar* : Representan dependencias entre conceptos (fraternal, disjunto y no-disjunto).
      - *fraternal* : Marcos origen y destino son marcos clase, unidos mediante subclase-de a un mismo nodo padre.
      - *disjunto* :
      - *no disjunto* : pueden tener instancias comunes.
      - *ad-hoc* : Hay que definirlas entre marcos clase. Son como atributos concretos de una clase.
            - Los marcos instancia que se quieren conectar deben ser instancias de las clases con la relación ad-hoc.
            - Una relación ad-hoc es una instancia de la relación ad-hoc definida a nivel clase.
            - Muchas herramientas SBM no las implementan.

**** Representación de las propiedades de los conceptos
- *Propiedades de clase* : atributos genéricos de un concepto o clase.
      - Toman siempre el mismo valor en todos los elementos o instancias de la clase.
- *Propiedades de instancia* : Se rellenan en cada instancia.
      - Las propiedades precedidas de "*" son propiedades de instancia.
- Al definir propiedades de clase y propiedades de instancias hay que tener en cuenta:
      - Se debe favorecer que unos marcos compartan datos con otros marcos.
            - Evitar conocimiento redundante.
      - Proporcionar la suficiente información como para determinar la entidad que el marco clase está representando.
      - El nombre de cada propiedad refleja su semántica
      - Propiedades tienen caracter local.
      - Un marco clase rellena las propiedades de clase.
      - Se puede definir una propiedad de instancia utilizando otros marcos clase.
      - Un marco instancia puede rellenar o no todas las propiedades de instancia definidas en el marco clase.

**** Representación de facetas de propiedades        
- *facetas* : Permiten modelar características de las propiedades y relaciones en los marcos clase.
      - Declarativamente se especifica un puntero o un tipo de datos.
      - Procedimentalmente se define utilizando un procedimiento o una regla.
- categorías:
      - Facetas que definen Propiedades de clase, propiedades de instancia y relaciones.
            - Tipo ranura : Tipo de datos con el que se rellena la propiedad o relación.
                  - Si es de clase o de instancia se rellena con valores.
            - Cardinalidad mínima
            - Cardinalidad máxima
            - Multivaluada
      - Facetas que definen propiedades de clase y relaciones.
      - Facetas que definen propiedades de instancia.
            - valores permitidos
            - Valores por omisión
            - Si necesito : Procedimiento al solicitar el valor y ser desconocido dicho valor.
            - Si modifico : Procedimiento ...
            - Si añado : Procedimiento ...
            - Si borro : Procedimiento ...
- El motor de inferencias usa a las facetas para mantener la integridad semántica de los datos.

*** Criterios de diseño
- Se debe favorecer la compartición de propiedades de clase y de instancia entre marcos.
- Se debe evitar representar conocimientos redundantes.
- En cada marco de clase debe haber una propiedad de clase que identifique a los elementos de dicha clase.
- Las propiedades deben tener o aportar significado a la representación.
- Carácter local de las propiedades.
- Si es necesario se puede redefinir las propiedades en marcos de clase más específicos.
- Propiedades de las propiedades deben ser definidas como marcos.
- No mezclar conceptos.
- Tener en cuenta que en un marco instancia se puede rellenar o no todas las propiedades.
- Recordar que las propiedades instancia se rellenan con valores concretos.
- No se pueden usar propiedades no definidas en marcos clase.

** Inferencia de conocimiento en SBM
*** Equiparación
1. Selección de marcos candidatos :
       - Si el tipo de la nueva entidad es conocido se puede seleccionar el marco clase del tipo.
             - Y todos los marcos clase especializados.
       - Si el tipo de la nueva entidad es desconocido se selecciona arbitrariamente la selección del marco clase o que almenos contenga algúna propiedad conocida en el marco pregunta.
2. Calcular el valor de equiparación (VE) en cada una de las clases seleccionadas.
3. Calculados los VE se decide con qué marcos clase se equiparará la nueva entidad.

*** Herencia de propiedades
- Permite compartir valores y definiciones de propiedades entre marcos de una BC.
      - Usa relaciones de instancia y subclase-de.
- *Herencia Simple* : Existe un único camino que une el marco instancia con el nodo raiz.
      - Algoritmo para encontrar valores de una cierta propiedad.
            - Se busca la propiedad en el marco instancia. Si se encuentra se devuelve.
            - Se busca en el marco clase. Si se encuenra se devuelve.
            - Recursivamente se busca la propiedad en el marco de clase raiz. Si se encuentra se devuelve.
            - Si no se encuentra se responde que es imposible proporcionar una respuesta.
- *Herencia Múltiple* : Varios caminos que unen los marcos instancia con el nodo raiz de la jerarquía
      - Dificultad en determinar el orden de las clases a explorar.
      - Existen conflictos si los padres tienen propiedades con los mismos nombres.
      - Algoritmos que recorren el grafo de herencia.
            - Profundidad:
                  - Un procedimiento de ordenación topológica cumple:
                        - Criterios de orden como de izquierda a derecha.
                        - Evitar búsqueda reiterada.
                        - Criterio de espificidad, En una propiedad unas clases tienen preferencia sobre otras.
            - Anchura:
                  - Longitud del camino
                        - Recorre el grafo por niveles.
            - Distancia Inferencial:
                  - Condición necesaria y suficiente para que la clase1 esté más cercana a la clas2 que a la clase3.

*** Valores activos
- [id:IntArt] pag 161
- Aspecto dinámico o procedimental.
- demonios, valores activos o disparadores : Procedimientos que recuperan almacenan y borran información en los SBN.
- Se definen en las facetas *Si Necesito*, *Si Añado*, *Si modifico* y *Si borro*.
- Características de la ejecución:
      - Procedimientos se definen en el marco clase y permanecen latentes.
      - Se despiertan al recibir una solicitud de ejecución.
      - Los procedimientos pueden simular encadenamiento hacia delante y encadenamiento hacia detrás.
      - Los procedimientos se ejecutan en stack.

* Glosario
- *Inferencia*, Razonamiento, proceso mediante el cual partiendo de unos hechos se deducen otros hechos.
      - *Inferencia deductiva*, A implica B, C implica B, etc.
      - *Inferencia abductiva*, aspiramos a obtener hipótesis.
            - Inferencia de hipótesis que pueden explicar un hecho.
            - Hechos con un cierto grado de certeza asociado.
      - *Inferencia inductiva*, A si y solo si (B o C o D).
            - A partir de la experiencia constatada.
- *Agente racional*, Agente que actúa con la intención de alcanzar el mejor resultado. Cuando hay incertidumbre el mejor resultado esperado.
- *Problemas NP-Duros* : Problemas en los que no se conoce un algoritmo polinomial que los resuelva.
- *RNN*, Redes neuronales recurrentes
- *CNN*, Redes neuronales convolucionales
- *GAN*, Redes generativas adversarias.
      - Redes neuronales no supervisadas pero basadas en auto-entrenamiento supervisado.
      - Indicadas para IA Generativa.
      - Juego de suma 0 entre.
            - Generador Genera instancias a partir de lo que aprende del dominio
            - Discriminador, trata de valorar si la instancia es del mundo real o generada.
- *VAE*, Autocodificadores variacionales.
- *GPT*, Generative pretained trasformer
- *Interpretabilidad*, propiedad de entender la relación entre los datos procesados y la solución propuesta.
- *Explicabilidad*, Capacidad de entender el razonamiento efectuado por la máquina.
- *Frugalidad*, Propiedad de los algoritmos de aprendizaje de necesitar pocos recursos para mostrar unas prestaciones aceptables.
      - Tanto en el uso como en el entrenamiento.

- *Expandir un nodo* : En un grafo obtener los nodos descendientes (que derivan del nodo) y añadirlo a la lista de pendientes por visitar.
- *conjunto* : reunión de elementos que comparten alguna propiedad.

* Bibliografía

** Inteligencia Artificial
:PROPERTIES:
:TYPE: book
:TITLE: Inteligencia Artificial, técnicas métodos y aplicaciones
:AUTHOR: José T.Palma Méndez, Roque Marín Morales
:ID: IntArt
:EDITORIAL: Mc Graw Hill
:END:
