#+title: Bases De Datos
#+author: Jordi Amposta Pérez
#+startup: latexpreview overview

* Introducción
- *SGBD*, Sistema gestor de bases de datos, colección de datos interrelacionados y un conjunto de programas par acceder a dichos datos.
      - *Base de datos*, colección de datos que contienen información relevante.
        
** Aplicaciones de los sistemas de bases de datos
- Aplicaciones representativas
      - Información empresarial
            - ventas
            - Recursos humanos
            - Fabricación
            - Comercio en línea
      - Banca finanzas
            - Banca
            - Transacciones de tarjetas de crédito
            - Finanzas
      - Universidades
      - Líneas aéreas
      - Telecomunicaciones

** Propósitos de los sistemas de bases de datos
- Problemas de guardar la información en archivos convencionales.
      - *Redundancia e inconsistencia de los datos*
      - *Dificultad en el acceso a los datos*
      - *Aislamiento de los datos*, Se refiere a que los datos estén dispersos o incluso en diferentes formatos.
      - *Problemas de integridad*
      - *Problemas de atomicidad*, la operación ocurre o no ocurre.
      - *Anomalías en el acceso concurrente*, race conditions.
      - *Problemas de seguridad*, evitar usuarios con acceso a la totalidad de los datos.

** Visión de los datos
- El sistema oculta ciertos detalles del modo en que se almacenan y mantienen los datos.

*** Abstracción de datos
- *Nivel físico*, nivel más bajo de abstracción.
      - Describe en detalle las estructuras de datos complejas a bajo nivel.
- *Nivel lógico*, Describe qué datos se almacenan en la base de datos y que relaciones existen entre ellos.
      - *Independencia de los datos físicos*, no es necesario conocer la implementación física.
- *Nivel vistas*, Usuarios con acceso a una parte de los datos.
      - Simplifica la interacción con el sistema.
      - El sistema puede proporcionar muchas vistas de los datos.

*** Ejemplares y esquemas
- *Ejemplar*, colección de información alamcenada en la base de datos en un momento dado.
- *Esquema*, diseño general de la base de datos.
      - *Esquema físico*, describe el diseño a nivel físico.
      - *Esquema lógico*, describe el diseño a nivel lógico.
            - Usado en tareas de programación.
      - *Subesquemas*, esquemas de nivel vista.
- *Independencia física respecto de los datos*, Pueden efectuarse cambios en el nivel físico sin comprometer los datos.

*** Modelos de datos
- Bajo la estructura de las bases de datos se encuentra el *modelo de datos*, se trata de una colección de herramientas conceptuales para describir los datos, sus relaciones, su semántica y las restricciones de consistencia.
- *Modelo relacional*
      - Uso de tablas para representar datos y relaciones.
      - Más ampliamente utilizado.
- *El modelo entidad-relación* (E-R)
      - Se basa en los objetos básicos *entidades* y la relaciones entre ellos.
      - Se usa mucho en el diseño de base de datos.
- *Modelo de datos basado en objetos*
      - Extensión de E-R con encapsulación.
      - Influenciado por la programación orientada a objetos.
- *Modelo de datos semiestructurados*
      - Permite definir tipos en los que elementos individuales del tipo tengan diferentes atributos.
      - tipo XML.
- *Modelo de datos de red* y *modelo de datos jerárquico* casi no se usan.

** Lenguajes de bases de datos
*** Lenguaje de manipulación de datos (LDM)
- Permite acceder y manipular los datos.
- Tipos de acceso
      - Recuperación de información almacenada.
      - Inserción de información nueva.
      - Borrado de información de la base de datos.
      - Modificación de la información almacenada.
- Tipos de LDM
      - *LDM procedimentales*, Necesita que el usuario especifique qué datos y como obtener los datos.
      - *LDM declarativos*, El usuario especifica qué datos sin definir como obtenerlos.
- *Consulta*, instrucción que solicita recuperar información.
      - *Lenguaje de consultas*, parte del LDM para realizar consultas.

*** Lenguaje de definición de datos (LDD)
- Define los esquemas de la base de datos.
- *Lenguaje de almacenamiento y definición de datos*, subconjunto del LDD.
      - Estas instrucciones define los detalles de implementación de los esquemas.
- *Restricciones de consistencia*, Los valores almacenados deben satisfacer ciertas restricciones.
      - *Restricciones de dominio*, dominio de valores posibles a cada atributo.
      - *Integridad referencial*, valor de un atributo exista en un atributo de una entidad relacionada (creo que como el id).
      - *Asertos*, condiciones que la base de datos debe satisfacer siempre.
      - *Autorización*, diferenciación de acceso entre los ususarios.
            - Autorización de lectura.
            - Autorización de inserción.
            - Autorización de actualización.
            - Autorización de eliminación.
- El output del LDD suele almacenarse como metadatos en el *Diccionario de datos*.
      - Normamelte colo accesible por el propio sistema.

** Base de datos relacionales
- Representan los datos y la relaciones usando tablas.
- Incluyen un *LMD* y un *LDD*.
- Uso de *SQL*
- Modelo basado en registros.

*** Tablas
- Columnas son atributos y las filas los registros (las entradas).

*** Ejemplos SQL

Una consulta usando el LDM de SQL

#+begin_src sql
select profesor.nombre from profesor where profesor.nombre_depth="Historia"
#+end_src

Definir una tabla usando el LDD de SQL

#+begin_src sql
create table departamento (
  nombre_depth  char(20),
  edificio      char(15),
  presupuesto   numeric(12.2));
#+end_src

*** Acceso a las bases de datos desde programas de aplicación
- Operaciones complejas las efectuan los programas anfitrión (C/C++).
- Los programas de aplicación facilitan a los usuarios la interacción con la base de datos.
  
** Diseño de base de datos
*** Proceso de diseño
- Caracterizar completamente los requisitos de datos de los hipotéticos usuarios de la base de datos.
- Diseño conceptual, definir los datos y sus relaciones.
- Fase de diseño lógico, serelaciona el esquema conceptual con el modelo de implementación de datos.
- Fase de diseño físico, se especifican las características físicas de la base de datos.

*** El modelo entidad-relacion
- las entidades son un esquema de el conjunto de atributos que tendrá la entidad
      - Conjunto de entidades, conjunto entidades del mismo tipo
- La relación es un objeto que asocia varias entidades.
      - Conjunto de relaciones del mismo tipo
- Se usa notación UML ampliamente para describir el E-R

*** Normalización
- El objetivo es generar un conjunto de esquemas de relaciones que permita almacenar información sin redundancias innecesarias.
      - También debe permitir recuperar la información con facilidad.
- Se usa el enfoque de *Dependencias funcionales*.

** Almacenamiento de datos y consultas

*** Gestor de almacenamiento        
- Importante la estructura de los datos para que las consultas sean rápidas incluso en bases de datos muy grandes (terabytes).
- Traduce instrucciones LMD a comandos de bajo nivel del sistema de archivos del OS.
- Componentes
      - *Gestor de autorizaciones e integridad*
      - *Gestor de transacciones*
            - Garantiza que la base de datos queda en un estado consistente.
      - *Gestor de archivos*, gestiona la asignación de espacio de almacenamiento de disco.
            - También las estructuras de datos usadas.
      - *Gestor de memoria intermedia*, responsable de traer datos desde el memoria secundaria a memoria principal.
- Implementa varias estructuras de datos.
      - *Archivos de datos*, La base de datos en si misma.
      - *Diccionario de datos*, metadatos acerca de la estructura de la base de datos.
      - *Índices*, que pueden proporcionar acceso rápido a los datos.

*** Procesador de consultas
- Contiene
      - *Intérprete de LDD*.
      - *Compilador LMD*, para que lo entienda el motor de evaluación de consultas.
            - Se aplican optimizaciones, elige el plan de evaluación de menor coste.
      - *Motor de evaluación de consultas*, Ejecuta las instrucciones de bajo nivel generadas por el compilador LMD.

** Gestión de transacciones
- *Transacción*, Varias operaciones forman una unidad lógica de forma atómica.
- *Atomicidad*, ocurre o no ocurre, sin punto medio.
- *Recuperación de fallos*, detectar inconsistencias y restaurar el sistema a antes de los fallos.
- *El gestor de control de concurrencia* debe gestionar la interacción entre transacciones concurrentes.

** Arquitectura de bases de datos
- Pueden ser tipo cliente-servidor.
      - Servidores ejecutan los sistemas de bases de datos.
- Las bases de datos distribuidas se extienden por varias máquinas geográficament separadas.
- *Arquitectura dos capas*, el cliente invoca la funcionalidad del sistema que está en un servidor.
      - Usa instrucciones del lenguaje de consultas.
- *Arquitectura de tres capas*, El cliente no alberga llamadas a la base de datos
      - El cliente se comunica con un servidor de aplicaciones.
            - Aquí reside la lógica de negocio de la aplicación.
      - El servidor de aplicaciones se comunica con el sistema de base de datos.
      - Más adecuado par aplicaciones de gran tamaño.

** Minería y análisis de datos
- Análisis semiautomático de grandes bases de datos para descubrir patrones útiles.
- El conocimiento descubierto se represetna mediante un conjunto de reglas.
- Suele haber un preprocesado de los datos, preparación para los algoritmos.
- Suele haber un postprocesado de los patrones descubiertos.
- *Almacenes de datos*, Datos de distintas fuentes bajo un esquema unificado en un punto.
- *Recuperación de la información*, consulta de datos textuales no estructurados. 

** Bases de datos específicas
*** Modelos de datos basados en objetos
- E-R con nociones de encapsulación, métodos e identidad de objetos.

*** Modelos de datos semiestructurados
- Cada elemento de datos del mismo tipo puede tener atributos diferentes.
- XML, puede representar datos con estructura anidada.

** Usuarios y administradores de bases de datos
*** Usuarios de bases de datos e interfaces
- *Usuarios normales*, Interactuan con el sistema invocando algunos de los programas de aplicación.
- *Programas de aplicaciones*, Profesionales informáticos que escriben programas de aplicación.
- *Usuarios sofisticados*, Formulan consultas con un lenguaje de consultas o con herramientas software de análisis de datos.
- *Usuarios especializados*, Son usuarios sofisticados que escriben aplicaciones de bases de datos especializadas que no encajan en el marco tradicional del procesamiento de datos.

*** Administrador de bases de datos
- *ABD*, administrados de bases de datos, tiene el control central del sistema.
- Funciones del ABD
      - *Definición del esquema*, Crea el esquema central mediante instrucciones LDD.
      - *Definición de la estructura y del método de acceso*.
      - *Concesión de autorización para el acceso a los datos*.
      - *Mantenimiento rutinario*, Importante que el rendimiento no se degrade.
            - Copia de seguridad periodica.
            - Asegurarse de que se dispone de suficiente espacio en disco.
            - Supervisar los trabajos que se ejecutan en la base de datos y asegurarse de que el rendimiento no se degrade a causa de tareas muy costosas.

* Introducción al modelo relacional
** Estructura de las bases de datos relacionales
- Consiste en un conjunto de tablas.
- *Relación* es una tabla.
      - Corresponde al concepto *variable* en lenguajes de programación (pag 20 - 2.2).
- *Tupla* es una fila.
- *Atributo* es una columna.
      - *Dominio*, Conjunto de valores permitidos en un atributo.
      - Un *Dominio* es atómico si los elementos del dominio se consideran indivisibles.
            - por ejemplo 1 número de teléfono y no una lista de teléfonos.
      - Valor *null (nulo)* es especial. Significa valor desconocido o no existe.
- *Ejemplar de relación*, instancia específica de una relación.

** Esquema de la base de datos
- *Esquema de la base de datos*, es el diseño lógico.
      - *Esquema de la relación*, corresponde al concepto de definición de tipo.
- *Ejemplar de la base de datos*, instantánea de los datos de la base de datos en un momento dado.

** Claves
- No se permite que dos tuplas de una misma relación tengan exactamente los mismos valores en todos los atributos.
- *Superclave*, conjunto de uno o varios atributos que permiten identificar de manera unívoca una tupla de la relación.
      - Por ejemplo un atributo *ID*.
      - Si *K* es una superclave también lo es cualquier superconjunto que contenga a *K*.
      - *Claves candidatas*, superclaves mínimas.
      - *Clave primaria*, *clave candidata* elegida por el diseñador como media principal para identificar las tuplas de una relación.
            - Sus valores no deberían cambiarse nunca.
            - En un esquema de relación aparecen los primeros y subrallados.
- *Clave externa*, una *relación* puede incluir la *clave primaria* de otra *relación*.
      - *relación referenciante*, que incluye la clave primaria de otra relación.
      - *relación referenciada*, su clave primaria ha sido usada como *clave externa*
- *Restricción de integridad referencial*, requiere que los valores que aparecen en una *relacion referenciante* también aparezcan en almenos una tupla de la *relación referenciada*.

** Diagramas de esquema
- Representación gráfica del esquema de una base de datos.
      - Esquema de la base de datos junto con las dependencias de clave primaria y externa.
      - Solo se muestran las restricciones de clave externa.

** Lenguajes de consulta relacional
- *lenguaje de consulta*, lenguaje con el que los usuarios solicitan información de la base de datos.
      - *Lenguajes procedimentales*, el usuario indica al sistema una seria de operaciones para calcular el resultado deseado.
            - Algebra relacional
      - *Lenguajes no procedimentales*, el usuario describe la información deseada sin detallas el procedimiento para obtener información.
            - Cálcula relacional de tuplas
            - Cálculo relacional de dominios

** Operaciones relacionales
- Propio de los *lenguajes procedimentales*.
- Operaciones sobre una o dos relaciones que dan como resultado una nueva relación.
      - Así se pueden volver aplicar operaciones sobre la nueva relación.
      - Una operación común es la selección de tuplas concretas de una relación.
      - Otra es seleccionar algunos atributos de una relación.
      - La relación resultante podría contener tuplas duplicadas.
            - Caso común despues de una selección.
            - Algunos lenguajes de consultas eliminan las duplicidades.
      - *join* es una operación para combinar pares de tuplas de dos relaciones distintas.
            - *reunión natural*, La relación resultante contiene los pares de tuplas que coinciden el valor de uno de sus atributos, eligiendo qué atributo claro.
            - *producto cartesiano*, La relación resultante contiene todos los pares de tuplas posibles entre dos relaciones.
            - Las relaciones son conjuntos, por eso se puede aplicar *union*, *intersección* y *diferencia*.

* Introducción a SQL
** Componentes de SQL
- *LDD*, lenguaje de definición de datos.
- *LMD*, lenguaje interactivo de manipulación de datos.
- *Integridad*, el LDD puede especificar las restricciones de integridad. Las actualizaciones que violan la integridad se rechazan.
- *Definición de vistas*
- *Control de transacciones*, Se puede especificar el inicio y final de una transacción.
      - Creo que es que la transacción sea atómica.
- *SQL incorporado* y *SQL dinámico*, definen cómo se pueden incorporar instrucciones SQL en lenguajes de programación.
- *Autorización*
- Pueden haber diferencias entre distintas implementaciones del lenguaje SQL (MySql, PostgrSQL).

** Definición de datos de SQL
*** Tipos básicos (dominios)
- Tipos
      - *char(n)*, cadena de carácteres de longitud fija n.
            - Puede incluir espacios en blancos para completar la longitud de la cadena n.
      - *varchar(n)*, cadena de carácteres de longitud variable como máximo hasta n.
            - Se recomienda este tipo sobre *char*.
            - Las comparaciones char = varchar no tiene un comportamiento asegurado.
      - *int*
      - *smallint*
      - *numeric(p,d)*, Número de coma fija, cuya precisión la especifica el usuario.
            - *P* dígitos (con signo) de ellos *d* son decimales.
      - *real, double precision*, la precisión depende de la máquina.
      - *float(n)*, Número de coma flotante con precisión de almenos n dígitos.
- Todos los tipo incluyen *null*.

*** Definición básica de esquemas
- *create table* Creación de relaciones.
  
#+begin_example
create table r
  (A1 D1,                         // A: atributo, D: dominio(tipo)
   A2 D2,
   ...
   An Dn,
   <restricción integridad 1>,
   ...
   <restricción integridad k>
   );
#+end_example

- Algunas restricciones de integridad
      - *primary key (Aj1, Aj2, ..., Ajm)*, Determina la clave primaria de la relación.
      - *foreign key (Ak1,..,Akn) references s*, (Ak1,...,Akn) debe coincidir con los atributos clave primarios de la relación *s*.
      - *not null*, no se permite el valor nulo para este parámetro.

- Manipulaciones de relaciones
      - *delete from r*; : Elimina todas las tuplas de r.
      - *drop table r*; : Elimina una relación de la base de datos.
      - *alter table r add A D;* : Añade atributos a una relación que ya existe.
      - *alter table r drop A;* : Elimina atributos de una relación que ya existe.
            - Algunas implementaciones no permiten esta operación.

#+caption: Ejemplo definición de datos
#+begin_src sql
create table departamento
(
nombre_dept varchar(20),
edificio    varchar(15),
presupuesto numeric(12,2),
primary key (nombre_depth)
);

create table asignatura
(
asignatura_id varchar(7),
nombre        varchar(50),
nombre_depth  varchar(20),
creditos      numeric(2,0),
primary key (asignatura_id),
foreign key (nombre_depth) references departamento
);
#+end_src              

** Estructura básica de consultas
*** Consultas sobre una relación única
#+begin_example
select [distinct | all] A1,...,An from r [where <predicados>];
#+end_example

- *distinct*, fuerza que no hayan valores duplicados en la consulta.

#+begin_src sql
select distinct nombre_dept from profesor;
#+end_src

- *all*, indica explícitamente que los duplicados no se eliminen.

#+begin_src sql
select all nombre_depth from profesor;
#+end_src  

- Puede contener expresiones aritméticas

#+begin_src sql
select ID, nombre, sueldo*1.1 from profesor;  -- Los valores de sueldo aparecerán
                                              --  multiplicados por 1.1
#+end_src  

- *where* permite seleccionar aquellas tuplas que cumplan cierto predicado.

#+begin_src sql
select nombre from profesor where nombre_depht='Informática' and sueldo > 70000;
#+end_src  

*** Consultas sobre varias relaciones
#+begin_example
select A1,...,An from r1,..,rm where P
#+end_example

#+begin_src sql
select nombre, profesor.nombre_depth, edificio  -- profesor.nombre_depth identifica
                                                --  el atributo nombre_depth de forma unívoca.
from profesor, departamento
where profesor.nombre_depth = departamento.nombre_depth;
#+end_src

- *from* se defina a si misma como el producto cartesiano de las relaciones indicadas (pag31).
- Pasos generales de una Consulta
      1) Genere el producto cartesiano de la cáusula *from*.
      2) Aplique los predicados indicados en la cláusula *where*.
      3) Para cada tupla del paso 2 estraiga los atributos indicados en la cláusula *select*.
- Las implementaciones reales optimizan los pasos teóricos anteriores.

*** La union natural
#+begin_example
select A1,..,An from r1 natural join r2 ... natural join rm where P;
#+end_example

- *La unión natural* opera sobre dos relaciones y genera como resultado una relación.
      - Concatena tuplas en función si comparten mismos valores en atributos comunes.
            - No se realiza el producto cartesiano.

#+begin_src sql
select nombre, asignatura_id from profesor natural join enseña;
#+end_src

- *join r using (A1,...,An)*, permite comparar los valores de solo algunos atributos en común.

#+begin_src sql
select nombre,nombre_asig
from (profesor natural join enseña)
join asignatura using (asignatura_id); -- solo se tendrá en cuenta los valores
                                       --  del atributo en común asignatura_id
                                       --  enseña.asignatura_id = asignatura.asignatura_id
#+end_src  

** Operaciones básicas adicionales
*** Operación de renombrado
- pag 34

#+begin_src sql
select T.nombre as nombre_profesor, asignatura_id
from profesor as T, enseña as S
where T.ID = S.ID
#+end_src  

- Para hacer el producto cartesiano sobre la misma relación.

#+begin_src sql
-- Profesores con el sueldo mayor que el sueldo
--  de almenos un profesor de biología.
select distinct T.nombre
from profesor as T, profesor as S
where T.sueldo > S.sueldo and s.nombre_depth = 'Biología';
#+end_src

*** Operaciones con cadenas de carácteres
- La norma SQL es case sensitive, 'a' = 'A' se evalua falso.
      - Algunas implementaciones no siguen esta norma por defecto, es el caso de MySql.
- Operaciones obre cadenas
      - upper
      - lower
      - trim
      - || : concatenación
      - *like* : comparaciones usando patrones
            - % : coincide con cualquier subcadena.
            - _ : coincide con cualquier carácter.
            - \ : para escapar carácteres especiales.
      - *not like* : comparaciones usando patrones pero negadas.
      - *similar to* : comparaciones pero con expresiones regulares.

#+begin_src sql
select nombre_depth
from departamento
where edificio like '%Watson%'
#+end_src

*** Especificación de atributos en la cláusula Select

- *** : se puede usar en la cláusula *select* para indicar todos los atibutos.

#+begin_src sql
select profesor.*
from profesor,enseña
where profesor.ID = enseña.ID;
#+end_src

*** Orden en la presentación de las tuplas
- *order by* : hace que las tuplas se presenten con un criterio de orden.
  
#+begin_src sql
select nombre
from profesor
where nombre_depth = 'Fisica'
order by nombre;                -- alfabetico
#+end_src

- Se puede especificar *asc* o *desc*.
  
#+begin_src sql
slect *
from profesor
order by sueldo desc, nombre asc;  -- primero por sueldo descendente y ante las colisiones
                                   --  por nombre ascendente
#+end_src

*** Predicados de la cláusula where
- *between* : dentro de un rango.
#+begin_src sql
select nombre
from profesor
where sueldo between 90000 and 100000;
#+end_src

- *not between* : between negado.

- Comparación con listas de forma lexicográfica
  
#+begin_src sql
select nombre,asignatura_id
from profesor,enseña
where (profesor.ID, nombre_depth) = (enseña.ID, 'Biología');
-- equivale a profesor.ID = enseña.ID and nombre_depth = 'Biología'
#+end_src

** Operaciones sobre conjuntos
- *union* $\cup$, *intersect* $\cap$ y *except* -.

*** Operación union  
- *union* : unión entre dos relaciones.
      - Elimina duplicados automáticamente.
      - *union all* mantiene duplicados.
  
#+begin_src sql
(select asignatura_id
from sección
where semestre = 'Otoño' and año=2009)
union
(select asignatura_id
from sección
where semestre = 'Primavera' and año=2010);
#+end_src

*** Operación Intersección
- *intersect* : intersección entre dos relaciones.
      - Elimina duplicados.
      - *intersect all* para mantener duplicados.

#+begin_src sql
(select asignatura_id
from sección
where semestre='Otoño' and año=2009)
intersect
(select asignatura_id
from sección
where semestre='Primavera' and año=2010);
#+end_src

*** Operación except
- *except* : la substracción.
      - Elimina duplicados.
      - *except all* mantiene duplicados.

#+begin_src sql
(select asignatura_id
from sección
where semestre = 'Otoño' and año=2009)
except
(select asignatura_id
from sección
where semestre = 'Primavera' and año=2010)
#+end_src

** Valores nulos (null)
- El resultado de las operaciones aritméticas es nulo si cualquiera de los valores de entrada es nulo.
- *unknown* : tercer valor lógico (junto a true false) para comparaciones con null.
      - 1 < null  -->  unknown.
      - true and unknown  --> unknown
      - false and unknown --> false
      - unknown and unknown --> unknown
      - true or unknown  -->  true
      - false or unknown  -->  unknown
      - unknown or unknown  -->  unknown
      - not unknown  -->  unknown        
- *is null* y *is not null* : Operacion booleana para identificar valores null.

#+begin_src sql
select nombre
from profesor
where sueldo is null;
#+end_src

- En *select distinct* ('A',null)=('A',null) (solo se mantiene una copia) aunque null=null --> unknown.

** Funciones de agregación
- *avg* : Media (numérico)
- *min* : minimo
- *max* : máximo
- *sum* : total suma (numérico)
- *count* : recuento
  
*** Agregación básica

- Resultados con una única tupla

#+begin_src sql
select avg (sueldo) as med_sueldo
from profesor
where nombre_dept = 'Informática';
#+end_src

#+begin_src sql
select count(distinct ID)
from enseña
where semestre='Primavera' and año=2010;
#+end_src

*** Agregación con agrupamiento
- pag 39
- *group by*

#+caption: El sueldo medio de cada departamento  
#+begin_src sql
select nombre_dept, avg(sueldo) as med_sueldo
from profesor
group by nombre_depth;
#+end_src  

#+caption: Número de Profesores de cada departamento que enseño algo
#+begin_src sql
select nombre_dept, count(distinct ID) as prof_cuenta
from profesor natural join enseña
where semestre='Primavera' and año=2010
group by nombre_depth;  -- Deben estar presentes los atributos
                        --  que aparecen fuera de la agregación
#+end_src

*** Cláusula having
- pag 39
- *having* : Predicados que se aplican a grupos.

#+begin_src sql
select nombre_dep, avg(sueldo) as med_sueldo
from profesor
group by nombre_dept
having avg(sueldo) > 42000;
#+end_src  

- Combinado con *where*.

#+begin_src sql
select asignatura_id, semestre, año, secc_id, avg(tot_créditos)
from matricula natural join student
where año=2009
group by asignatura_id, semestre, año, secc_id
having count(ID) >= 2;
#+end_src

*** Agregación con valores nulos y valores booleanos
- todas excepto *count* ignoran los null.

** Subconsultas anidadas
*** Pertenencia a conjuntos
- *in* : pertenencia a un conjunto.
      - También existe *not in*.
  
#+begin_src sql
select distinct asignatura_id
from sección
where semestre='Otoño' and año=1009 and
  asignatura_id in (select asignatura_id
                    from sección
                    where semestre='Primavera' and año=2010);
#+end_src

#+begin_src sql
select count(distinct ID)
from matricula
where (asignatura_id,secc_id,semestre,año)
  in (select asignatura_id,secc_id,semestre,año
    from enseña
    where enseña.ID=1010);
#+end_src

*** Comparación de conjuntos
- *some*, superar condición con almenos uno.
- válido para >, >=, <, <=, =, y <>
  
#+begin_src sql
select nombre
from profesor
where sueldo > some (select sueldo
                     from profesor
                     where nombre_depth = 'Biologia');
#+end_src

- *all*, superar condición con todos.

#+begin_src sql
select nombre
from profesor
where sueldo > all (select sueldo
                    from profesor
                    where nombre_dept = 'Biologia');
#+end_src

- Usando agregación y agrupamiento.

#+begin_src sql
select nombre_dept
from profesor
group by nombre_dept
having avg (sueldo) >= all (select avg (sueldo)
                            from profesor
                            group by numpre_dept);
#+end_src

*** Comprobación de relaciones vacías
- pag 41
- *exists* -> booleano : Posibilidad de comprobar si las consultas tienen alguna tupla en su resultado.
      - *no exists* : el opuesto a exists.

#+begin_src sql
select asignatura_id
from sección as S
where semestre = 'Otoño' and año=2000 and
  exists (select *                                    -- y además también en Primavera 2010
          from sección as T
          where semestre = 'Primavera' and año=2010
            and S.asignatura_id = T.asignatura_id)    -- Comprobación de los ids para que
                                                      --  la comprobación sea sobre la
                                                      --  misma asignatura
#+end_src

- *Subconsulta correlación*, subconsulta que usa un nombre de correlación de una consulta externa.

*** Comprobación de la ausencia de tuplas duplicadas
- pag 42
- *unique* -> booleano : true si la subconsulta no contiene tuplas duplicadas.
      - la consulta es flase si contiene algunas tuplas $t_1$ y $t_2$ tal que $t_1 = t_2$.
      - *not unique* : el contrario

#+begin_src sql
select T.asignatura_id
from asignatura as T
where unique (select R.asignatura_id
              from sección as R
              where T.asignatura_id = R.asignatura_id and
                R.año = 2009);
#+end_src

*** Subconsultas en la clausula from
- pag 43
- La idea es que *from* puede referirse a una relación generada.

#+begin_src sql
select nombre_dept,med_sueldo                       -- Selecciona el departamento y el
                                                    --  salario promedio
from (select nomre_dept, avg(sueldo) as med_sueldo  -- Relación de salarios promedio
      from profesor
      group by nombre_dept)
where med_sueldo > 42000;                           -- Promedios superiores a 42000
#+end_src

- Renombrando con *as*
      - Algunas implementaciones de SQL no permiten este renombramiento.

#+begin_src sql
select nombre_dept, sueldo_medio
from (select nombre_dept, avg(sueldo)
      from profesor
      group by nombre_dept)
      as dept_medio(nombre_dept, sueldo_medio)
where sueldo_medio > 42000
#+end_src  

#+begin_src sql
-- El departamento con la máxima suma de sueldos
select max(tot_sueldo)
from (select nombre_dept,sum(sueldo)
      from profesor
      group by nombre_dept)
        as dept_total(nombre_dept,tot_sueldo)
#+end_src

- Por defecto desde la subconsulta anidada en *from* no se puede acceder a variables de correlació externas. 
- *lateral* : permite el acceso a relaciones externas, pero pocas implementaciones la permiten.

#+begin_src sql
-- Con la clausula lateral no parece ser necesario usar as
select nombre,sueldo,sueldo_medio
from profesor I1, lateral(select avg(sueldo) as sueldo_medio
                             from profesor I2
                             where I2.nombre_dept = I1.nombre_dept);
#+end_src

*** La cláusula with
- *with* : Permite definir vistas temporales solo disponibles para la consulta en la que aparece.
- Permite consultas más claras y mejor acceso en diferentes partes de la consulta.

#+begin_src sql
with max_presupuesto (valor) as     -- Vista temporal
     (select max(presupuesto)
      from departamento)
select presupuesto
from departamento, max_presupuesto
where departamento.presupuesto = max_presupuesto.valor;
#+end_src  

#+begin_src sql
with dept_total(nombre_dept, valor) as
  (select nombre_dept, sum(sueldo)
   from profesor
   group by nombre_dept),
dept_total_medio(valor) as
  (select avg(valor)
   from dept_total)
select nombre_dept
from dept_total,dept_total_media
where dept_total.valor >= dept_total_medio.valor;
#+end_src

*** Subconsultas escalares
- *subconsultas escalares* : subconsultas en cualquier punto en el que una expresión devuelve un valor

#+begin_src sql
select nombre_dept,
       (select count(*)    -- agregación, número de tuplas
                           --  SQL extrae el único valor esperado
                           --  de forma implícita
        from profesor
        where departamento.nombre_dept = profesor.nombre_dept)
        as num_profesores
from departamento;        
#+end_src

** Modificación de la base de datos
*** Borrado
- Borrado de tuplas.
- Solo puede borrarse tuplas de una relación a la vez.
  
#+begin_src sql
delete from r where P;
#+end_src

- Borrar todas las tuplas de una relación.

#+begin_src sql
delete from profesor;
#+end_src

- Usando *where*

#+begin_src sql
delete from profesor where nombre_depth='Finanzas';
#+end_src  

#+begin_src sql
delete from profesor
where nombre_dept in (select nombre_dept
                      from departamento
                      where edificio = 'Watson');
#+end_src

- Borrado combinado con agregación.
      - Primero se realizan las comprobaciones y luego el borrado.

#+begin_src sql
delete from profesor
where sueldo < (select avg(sueldo) from profesor);
#+end_src

*** Inserción
- Se especifica la tupla que se quiere insertar.

#+begin_src sql
insert into asignatura
values ('CS-437', 'Base de datos', 'Informatica', 4);
#+end_src

- Especificando los atributos.

#+begin_src sql
insert into asignatura(asignatura_id, nombre, nombre_dept, créditos)
values ('CS-437', 'Base de datos', 'Informatica', 4);
#+end_src  

- Insertar en un relación el resultado de una consulta.
      - *select* se evalua antes de cualquier inserción.

#+begin_src sql
insert into profesor
            select ID, nombre, nomber_dept, 18000
            from estudiante
            where nombre_dept = 'Música' andtot_cred > 144;
#+end_src

- Normalmente las bases de datos tienen utilidades especiales para agregar muchas entradas desde archivos de texto.

*** Actualizaciones
- pag 44
- Modificar el valor dentro de una tupla sin modificar toda la tupla.

#+begin_src sql
update profesor
set sueldo = sueldo * 1.05;  -- aquí igual es asignación
#+end_src  

- Usando *where*.
      - Primero se comprueban las condiciones.

#+begin_src sql
update profesor
set sueldo = sueldo * 1.05
where sueldo < 70000;
#+end_src

- Con agregaciones.

#+begin_src sql
update profesor
set sueldo = sueldo * 1.05
where sueldo < (select avg(sueldo) from profesor);
#+end_src

- *case* : Multiples actualizaciones en una instrucción.
      - Para evitar problemas de actualizaciones fuera de orden.
      - Se pueden usar en cualquier lugar donde se espere un valor.

#+begin_src sql
update profesor
set sueldo = case
             when sueldo <= 100000 then sueldo * 1.05
             when <pred2> then <resultado>             -- Ejemplo de la estructura
             ...
             else sueldo * 1.03
             end
#+end_src        

- *set* : permite subconsultas escalares.

#+begin_src sql
update estudiante S set tot_créditos = (
  select sum(créditos)
  from matricula natural join asignatura
  where S.ID = matricula.ID and
               matricula.nota <> 'F' and
               matricula.nota is not null
);
#+end_src

- *set* y *case* :

#+begin_src sql
update estudiante S set tot_créditos = (
  select case
    when sum(créditos) is not null then    -- Suma de los créditos de las asignaturas not null
      sum(créditos)
    else 0                                 -- Un estudiante que no ha aprobado ninguna asignatura
    end
  from matricula natural join asignatura   -- Atributos de la asignatura
  where S.ID = matricula.ID and            -- Matricula del estudiante
               matricula.nota <> 'F' and
               matricula.nota is not null
);
#+end_src   

* SQL intermedio
** Expresiones de reunión (join)
*** Condiciones de reunión (join ... on)
- pag 52
- *join ... on* : permite un predicado general sobre relaciones.
      - puede expresar cualquier predicado sql.
- Se suele usar para las condiciones de reunión sobre la cláusula where.

#+begin_src sql
... join <relación> on <predicados>
#+end_src

#+begin_src sql
select *
from estudiante join matricula on estudiante.ID = matricula.ID;  -- reune si estudiante.ID = matricula.ID
#+end_src

*** Reunión externa (outer join)
- Permite valores null en la reunión, y por tanto conserva más tuplas.
      - Por ejemplo que la tabla from no contenga una equivalencia con la tabla join.
- Cuano no se conservan tuplas que no tienen coincidencias se llama *reunión interna*.
      - *join* es igual a *inner join*.
- Tres formas de reunión externa.
      - *left outer join* : reunión externa izquierda.
      - *right outer join* : reunión externa derecha.
      - *full outer join* : reunión externa completa.
            - Efectua ambas reuniones.
- Funcionamiento de la reunión externa, (reunión externa derecha y completa funcionan de forma análoga).
      - Para cada tupla de la parte izquierda $t$ que no casa con ninguna tupla de la parte derecha en una reunión interna.
      - Se añade una tupla $r$ que se construye de la siguiente forma.
            - $r$ deriva de $t$ con sus atributos.
            - El resto de atributos de $r$ son null.

#+begin_src sql
select *
from estudiante natural left outer join matricula;
#+end_src

- combinación con *on*.

#+begin_src sql
select *
from estudiante left outer join matricula on estudiante.ID = matricula.ID;
#+end_src

** Vistas
- pag 55
- Relación virtual que no forma parte del modelo lógico.
      - Permite mostrar (y ocultar) cierta información a grupos de usuarios.
      - Las vistas no se precalculan, se crean bajo demanda.

*** Definición de vistas
- *create_view* : Crea una vista.

#+begin_src sql
create view v as <expresión de consulta>;
#+end_src  

#+begin_src sql
create view facultad as
select ID,nombre,nombre_dept  -- Esta vista oculta el atributo sueldo
from profesor;
#+end_src

#+begin_src sql
create view fisica_otoño_2009 as
select asignatura.asignatura_id, sec_id, edificio,número_aula
from asignatura,sección
where asignatura.asignatura_id=sección.asignatura_id
    and asignatura.nombre_dept = 'Física'
    and sección.semestre = 'Otoño'
    and sección.año = '2009';
#+end_src

*** Uso de vistas en consultas
- pag 55
- Se pueden hacer consultas como si fuera una relación.
- La evaluación de una consulta que incluye vistas sustituye cada vista por la expresión que representa.
- Se pueden definir vistas usando otras vistas.

#+begin_src sql
select asignatura_id
from física_otoño_2009
where edificio = 'Watson';
#+end_src

- Ejemplo de espicificación de los atributos con grupos.

#+begin_src sql
create view departamentos_total_sueldos(nombre_dept, total_sueldo) as
select nombre_dept, sum(sueldo)  -- el nombre del atributo relativo a sum(sueldo) es total_sueldo
from profesor
group by nombre_dept;
#+end_src  

*** Vistas materializadas
- *Vistas materializadas* : Son vistas almacenadas.
- *mantenimiento de vistas materializadas* : Ante cualquier modificación de alguna de las relaciones a las que hace referencia la *vista materializada* de recalcula.
- Depende del sistema de base de datos.
      - SQL no define ninguna forma estándar de especificar *vistas materializadas*.

*** Actualización de vistas
- pag 56
- Las vistas suponen dificultades en las inserciones, actualizaciones y borrados.
- Se suele decir que una *vista* es actualizable si cumple:
      - La cláusula *from* solo tiene una relación de base de datos.
      - *select* solo contiene nombre de atributos (sin expresiones).
      - Cualquier atributo que no aparezca en la tabla select puede definirse como null.
      - La consulta no tiene cláusulas *group by* ni *having*.
- Aún así puede que la inserción de una nueva tupla no aparezca en la vista.
      - Puede no satisfacer los critérios de pertenencia a la vista.
      - *with check option* : esta cláusula se usa para comprobar que la tupla que se quiere insertar cumpla las condiciones where de la vista para ser insertada.

*** Transacciones
- pag 57
- Secuencia de instrucciones de consulta o de actualización.
- Se inicia de forma implícita.
- Una de las siguientes sentencias debe finalizar la transacción.
      - *commit [work]* : Compromete la transacción, las actualizaciones pasan a ser permanentes.
            - Una vez hecho el *commit* no puede hacerse el *rollback*.
            - En caso de algún fallo se garantiza el *rollback*.
      - *rollback [work]* : retrocede la transacción actual.
- Si no se especifica *commit* o *rollback* al final de unas instrucciones el comportamiento queda definido por la implementación de sql.
      - *commit* o *rollback* automático.
- Muchas implementaciones consideran cada instrucción una transacción independiente.
      - Se puede desactivar pero depende de cada caso.
- *begin atomic ... end* : Todas las instrucciones contenidas forma una transacción.

** Restricciones de integridad
- Garantiza que las modificaciones no den como resultado pérdida de consistencia.
- Parte del proceso de diseño de la base de datos.
- Se declaran como parte del *create table*.
- Pueden añadirse con :
      - *alter table <nombre-tabla> add <nombre-restricción>*.
- Si el sistema cumple la restricción declarada esta se añade a la base de datos.
      - Si el sistema ni puede cumplir la restricción esta se rechaza.

*** Restricción not null
- No permite valores null.
      - los valores null están presentes en todos los dominios por defecto.
- Las claves primarios tienen la restricción *not null* por defecto.

#+begin_src sql
nombre varchar(20) not null
presupuesto numeric(12,2) not null
#+end_src

*** Restricción unique
- Ningún par de tuplas puede ser igual en todos los atributos indicados.
      - Es una clave candidata.
      - Permite que los valores sean null.

#+begin_src sql
unique (A1, A2, ..., An)
#+end_src

*** Cláusula check
- *check(P)* especifica un predicado que deben satisfacer todas las tuplas de la relación.
- Algunas implementaciones permiten realizar consultas en el predicado.
      - Realmente casi ninguna

#+begin_src sql
create table sección
(asignatura_id varchar(8),
 secc_id       varchar(8),
 semestre      varchar(6),
 año           numeric(6),
 edificio      varchar(15),
 número_aula   varchar(7),
 franja_horaria_id varchar(4),
 primary key (asignatura_id, secc_id, semestre, año),
 check (semestre in ('Otoño', 'Invierno', 'Primavera', 'Verano')));
#+end_src

*** Integridad Referencial
- pag 59
- El valor de un conjunto de atributos de una relación aparezca también en otro conjunto de atributos de otra relación.
      - Ejemplo Una *clave externa* usando *foreign key*.
- Estas restricciones se llaman *restricciones de integridad referencial*.
      - No requiere que se haga referencias a claves primarias exclusivamente.

- *foreign key* : Puede especificar acciones ante borrados y actualizaciones.

#+begin_src sql
create table asignatura
(...
 foreign key (nombre_dept) references departamento
              on delete cascade    -- si se produce una violación de integridad por borrado, borra en cascada.
              on update cascade,   -- Si se produce una violación por actualización, actualiza en cascada.
 ...);              
#+end_src

- Si una operación en cascada viola alguna restricción se aborta la transacción entera.
- En las claves externas se permiten valores null.

*** Violación de la restricción de integridad durante una transacción
- En una transacción puede que se viole una restricción de integridad durante los pasos intermedios.
- *initially deferred* : Cláusula que permite que se comprueba la integridad al final de una transacción.
- *deferrable* : de manera predeterminada se comprubea inmediatamente.
      - Pero puede diferirse si se desea.

*** Condiciones de comprobación complejas y asertos
- *aserto* : una condición que la base de datos debe satisfacer siempre.
- Pueden introducer mucha sobrecarga.
- Pocas implementaciones lo soportan.

#+begin_src sql
create assertion <nombre_aserto> check <predicado>;
#+end_src

** Tipos de datos y esquemas de SQL

*** Tipos fecha y hora en SQL
- pag 61
- *date* : '<YYYY>-<MM>-<DD>' : Fecha del calendario
- *time* : '<hh>-<mm>-<ss>' : Hora del día en horas minutos y segundos.
- *timestamp* : '<YYYY>-<MM>-<DD> <hh>-<mm>-<ss>' : Combinación de *date* y *time*
  
- *cast e as type* : convierte una cadena e de carácteres al tipo type.
- *extract(campo from d)* : extrar campos concretos de *date* o *time*. campos son.
      - year, month, day, hour, minuto o second.
- funciones para obtener fecha y hora actuales.
      - current_date, current_time, localtime, current_timestamp y localtimestamp.
- *interval* : tipo que permite realizar cálculos con fechas, horas e intérvalos.

*** Valores predeterminados

#+begin_src sql
create table estudiante
(ID           varchar(5),
 nombre       varchar(20) not null,
 nombre_dept  varchar(20),
 tot_creditos numeric(3,0) default 0,  -- valor por defecto.
 primary key (ID));
#+end_src

*** Creación de índices
- *índice* : Estructura de datos que permite al sistema accelerar las consultas.

#+begin_src sql
create index estudianteID_indice on estudiante(ID);
#+end_src

*** Tipos de datos para objetos grandes
- pag 62
- Tipo grandes como por ejemplo imágenes.
- *clob* : tipo para carácteres.
- *blob* : tipo para binarios.

#+begin_src sql
revista clob(10KB)
imagen blob(10MB)
pelicula blob(2GB)
#+end_src

- Se suele implementar en forma de localizador.

*** Tipos definidos por los usuarios
- pag 62
- *tipos de datos estructurados* : Tipos de datos complejos.
- *alias de tipos* : *create type ...*
      - *drop type* : eliminar el tipo.
      - *alter type* : modificar el tipo.

#+begin_src sql
create type Euros as numeric(12,2) final;
create type Libras as numeric(12,2) final;
#+end_src




* Notes
** mysql Service
- Done using podman, documented in ORG ROAM.
- password de la base de datos en el libro de la asignatura.
  



* Tools
** Create podman container
#+begin_src sh
podman pull docker.io/library/mysql:8.0
#+end_src
