#+title: Sistemas De Bases De Datos

#+startup: overview

* Tema 1 : Procesamiento de consultas
- Capitulo 12 [[#fundts]] pag249

** Descripción General

- Traducción de consultas en alto nivel a expresiones implementadas en el nivel físico.
- *primitivas de evaluación* : primitivas de álgebra relacional anotadas con instrucciones sobre su evaluación.
- *plan de evaluación de la consulta* : Secuencia de operaciones primitivas para evaluar una consulta.
- *Optimización de consultas* : El sistema es el responsable de construir un plan de evaluación óptimo a partir de la consulta de un usuario.
      - El optimizador estima el coste de cada operación.

** Medidas del coste de una consulta

- Solo tenemos en cuenta el coste de acceso en disco.
- $T_T$ tiempo transferencia
- $T_S$ tiempo búsqueda (search)
- operación que transfiere $b$ bloques y realiza $S$ búsquedas es $bT_T + ST_S$
- *Tiempo de respuesta* de ejecutar un plan es el tiempo de reloj que lleva ejecutar el plan.
      - Muy dificil de estimar, la computadora realiza otras actividades.
            - Depende del contenido en memoria.
            - En sistemas de varios discos depende de como se distribuyan los datos.

- El acceso a los recursos es un problema con sistemaas con muchas consultas concurrenes.
- Por ello los optimizadores tratan sobretodo de minimizar el uso de recursos.

** Operación Selección

- *Explorador de archivos* : operador de más bajo nivel para acceder a los datos.

*** Selecciones usando exploración de archivos e índices

- *A1 (búsqueda lineal)* : Se comprueban cada bloque del archivo y todos los registros.
      - Si los registros están almacenados de forma continua se evitan búsquedas adicionales.
      - Es aplicable en todos los casos.

- Las estructuras de índices se denominan *caminos de acceso*.

*Exploración con índice* algoritmos que usan índices:
- *A2 (índice primario, igualdad basada en la clave)*
- *A3( índice primario, igualdad basada en atributo NO clave)* :
  Puede ser necesario recuperar varios registros.
- *A4(indice secundario, igualdad)* :
  Selecciones con condición de igualdad.

[[#fundts]]  pag 252 tabla con costes de los algoritmos.

*** Selecciones con condiciones de comparación

- *A5(índice primario, comparación)* :
  índice ordenado primario. caso $A \geq v$, se busca el primer registro en el índice ($A=v$).
  el esplorador recorre desde el registro que cumple $A=V$ hasta el final el archivo y devuelve las tuplas que cumplen la condición.
- $A6(índice secundario, comparación)* :
  índice secundario ordenado. Le penaliza mucho tener que estar accediando a bloques de disco para obtener los registros reales.
      - en el índice secundario almacenamos los punteros en DISCO a los registros.

*** Implementación de selecciones complejas

- *Selección conjuntiva* : $\sigma_{\theta_1 \land \dots \land \theta_n}(r)$
- *Selección disyuntiva* : $\sigma_{\theta_1 \lor \dots \lor \theta_n}(r)$ :
  unión de todos lo registros que cmplen alguna condición
- *Negación* : $\sigma_{\lnot \theta}(r)$ :
  Complemento a todos los registros que cumplen $\theta$.


- *A7(selección conjuntiva utilizando un índice)*
  Se determina si para algún atributo hay algún camino de acceso para alguna de las condiciones simples.
  Si lo hay se recuperan estos archivos con algoritmos A2-A6.
  Se comprueban el resto de condiciones en memoria intermedia.
- *A8(Selección conjuntiva utilizando un índice compuesto)*
  indice compuesto por ejemplo igualdades entre atributos.
- *A9(Selección conjuntiva mediante la intersección de identificadores)*
  La intersección de todos los punteros recuperados.
  Se recuperan con un índices de cada atributo involucrado.
  Si todos los atributos involucrados tienen índice, no se recuperan registros innecesarios.
- *A10(Selección disyuntiva mediante la unión de identificadores)*
  Si se tienen caminos de acceso de todos los atributos involucrados en alguna de las condiciones, la unión de todos los punteros resultado es la disyunción.

** Ordenación

*** Algoritmo ordenación por mezcla externa
*ordenación externa* : ordenación de relaciones que no caben en memoria.

*Algoritmo de ordenación por mezcla externa*: Sea $M$ el número de bloques en la memoria intermedia.
1. Se crean varias *secuencias* ordenadas.
   #+begin_src pseudocode
   i <- 0
   REPEAT
     leer M bloqies, ordenar la parte de la relación que está en memoria;
     escribir los datos ordenados para archivo de secuencias Ri;
     i <- i+1
   UNTIL final de la relación  
   #+end_src
2. Las secuencias se mezclan. El número total de secuencias $N$ es menor que $M$.
   Se reserva un marco de página para cada secuencia.
   
   #+begin_src pseudocode
   leer un bloque de cada uno de los N archivos de Ri en un bloqu de memoria intermedia;
   REPEAT
     elegit la primera tupla;
     escribir la tupla y suplrimirla de la página de mem intermedia;
     IF página de memoria intermedia de alguna secuencia Ri está vacia AND NOT fin-archivo(Ri)
     THEN
       leer siguiente bloque Ri en el bloque de la memoria intermedia;
   UNTIL todas páginas de memoria intermedia estén vacías       
   #+end_src

*** Analisis del coste de la ordenación po rmezcla externa

*** Operación reunión

*equirreunión* : tipo $r \Join_{r.A=s.B} s$

**** Reunión en bucle anidado

$r \Join_{\theta} s$

#+begin_src pseudocode
FOR EACH tupla tr IN r DO BEGIN
  FOR EACH tupla ts IN s DO BEGIN
    comprobar si el par (tr.ts) satisface la condición \theta;
    si la cumple añadir (tr.ts) al resultado
  END
END  
#+end_src

Es costoso.

La relación más pequeña mejor en el bucle interno, mejor si cabe en memoria.

**** Reunión en bucle anidado por bloques

Ambas relaciones son más grandes que la memoria principal.

Se busca procesar por bloques.

#+begin_src pseudocode
FOR EACH bloque Br OF r DO
  FOR EACH bloque Bs of s DO
    FOR EACH tupla tr in Br DO
      FOR EACH tupla ts in Bs DO
        comprobar si el par (tr.ts) satisface \theta;
        si la cumple añadir (tr.ts);
#+end_src

*Costes*:
- $b_r * b_s] + b_r$ transferencias.

*Optimización*: si mem tiene $M$ bloques, leer $M-2$ bloques de $r$
- $[b_r/(M-2)]*b_s + b_r$ transferencias de bloque
- $[b_r/(M-2)]*b_s$ búsquedas (posicionamiento del cabezal de lectura de disco)

**** Reunión por asociación
pag 258

$h$ es una función hash, se usa sobre el atributo de la reunión.
asigna valores de $\{0,\dots, n_h\}$

$r_0, \dots, r_i$ particiones de la relación $r$, $i$ es el valor de $h(t_s[\text{attrib reunión}])$ para cada $t_s \in s$.
análogo para $s_i$.

Solo se compara las tuplas de $r_i$ con las de $s_i$.
e.g con una reunión por bucle anidado indexada.

*División recursiva*
# TODO

*Costes*:
Sin división recursiva.
- $3(b_r + b_s) + 4n_h$ transferencias de bloques.
- $2*([b_r/b_b] + [b_s/b_b]) + 2n_h$ búsquedas.

Require división recursiva.
- $2(b_r + b_s) [log_{M-1}(b_s) - 1] + b_r + b_s$ transferencias de bloques.
- $2([b_r/b_s] + [b_s/b_r])[log_{M_1}(b_s) - 1]$ búsquedas.


* Tema 2 : Optimización de consultas

* Tema 3 : Transacciones

* Tema 4 : Control de concurrencia 

* Tema 6 : Arquitecturas de sistemas de bases de datos

* Tema 7 : Bases de datos distribuidas

* Tema 8 : Modelos de bases de datos no relacionales
- hay tipo *SQL* y tipo *NO SQL*

* Bibliografía
** Fundamentos de bases de datos
:PROPERTIES:
:CUSTOM_ID: fundts
:AUTHOR: Silberschatz, Korth, Sudarshan
:EDITORIAL: Mc Graw Hill Education
:EDITION: 6
:END:

