#+title: Ingeniería Computadores III
#+startup: latexpreview content

* Fundamentos del diseño del hardware digital
- *HDL (hardware description languaje)*, lenguaje para la descripción del Hardware.
- *VHDL*, VHSIC Hardware Description Language
      - Very High Speed Description Langage

** Pasos del diseño de un circuito integrado
# TODO gráfico

** HDL más usados
- *Verilog* HDL, 
- *VHDL*
- SystemC, basado en C++

** Tecnologías de circuitos integrados
- ASIC, particularizadas en fábrica
- non-ASIC particularizadas en el campo (PLD)

*** Clasificación  

**** Full-custom ASIC
- Todos los elementos del circuito diseñados para una determinada aplicación.
- Se usa en pequeños dircuitos básicos (un sumador por ejemplo).

**** Standard-cell ASIC
- Trabajo a nivel de puertas lógicas combinando celdas estándar predefinidas.

**** Gate array ASIC
- Circuito construido a partir de un array de celdas base.
- Macroceldas, librerías de componentes prediseñados para realizar funciones básicas.
      - Puede realizarse el diseño conectando macrozeldas.

**** Dispositivos complejos programables en campo
- Un array de celdas lógicas e interconexión genérica entre ellas.
      - Fusibles que permiten programar.
- Tipos según la estructura circuital de sus celdas.
      - *CPLD*, Complex programable logic device
      - *FPGA*, Field programable Gate Array

**** Dispositivos sencillos programables en campo
- Conocidos como PLDs.
- Estructura interna más sencilla que los CPLD y FPGAs.
- Dos arrays, una array de puertas AND y otra de puertas OR
- tipos
      - *PROM*, programable read only, se programa la matriz OR.
      - *PAL*, Programable array logic, se programa la matriz AND.
      - *PLA*, Programable logic array, pueden programarse ambas matrices.
- Son usados raramente.

**** Circuitos estándar de pequeña y mediana integración
- Circuitos integrados prefabricados (SSI/MSI, Small/Medium-Scaled Integrated circuits).
- Se seleccionaban los circuitos y se aplicaban sobre una placa impresa para la aplicación.
- Ya no se usa.

*** Comparación entre tecnologías
- Se compara FPGS, Gate array y standar cell.

**** Área
- Circuitos más pequeños requieren menos recursos, tienen mejor rendimiento en fabricación y los tests son más sencillos.
- Circuitos con mayor área son más complejos y rápidos.
- En *standar cell*, el chip está optimizado con desperdicio mínimo,
- En *Gate Array*, La posición de las celda base está predeterminada.
      - El aprovechamiento no es óptimo.
      - Requiere de mayor área, entre 20% y 100% más que standar cell.
- *FPGA* son unas 2 y 5 veces mayor que con tecnología ASIC.

**** Velocidad
- Tiempo para realizar una función.
- Hace falta usar arquitecturas más complejas que ocupan mayor área.
- En idénticas arquitecturas normalmente el circuito de mayor área es más lento.
- *Standar cell* permite mayor velocidad (menores retardos de propagación).
- *FPGA*, la de menor velocidad.

**** Potencia consumida
- Menor consumo mejor.
- *Standar cell* es la que menos consume.
- *FPGA* consume la mayor cantidad de potencia.

**** Coste
- *Coste de producción*
      - $C_{prod} = C_{fab} + \frac{C_{ing}}{Unidades\ producidas}$
      - $C_{ing}$, coste de ingeniería, prototipos, máscaras de fotolitografía, dearrollo de tests.
      - $C_{fab}$, Coste de fabricar encapsular y testear un dispositivo.
            - FPGA > gate array > standar cell
            - Standar cell aprovecha mejor el área en la oblea de silicio.
- *Coste de desarrollo* de standar cell > gate array
      - Coste de diseñar el circuito
- *Coste del tiempo de llegada al mercado*
      - Influenciado por el ciclo de vida de los dispositivos.
      - Standar Cell necesita más tiempo de validaciones lo que retrasa su llegada al mercado (1,2 años).
      - Gate array unos meses.
      - FPGA la particularización del circuito a la aplicación puede hacerse en minutos.
        
** Propiedades de los circuitos digitales
*** Retardo de los dispositivos
- *glitch*, cambio temporal, pico de subida o bajada, en el voltaje.
- *Retardo inercial*, Si el tiempo de propagación es mayor que el glitch, este no afecta al funcionamiento.
      - hay que mantener el estado en un dispositivo para que el cambio se propague.
- *Retardo de transporte o retardo puro*. Los glitches de entrada se manifiestan en los pines de salida.
      - adecuado para modelar dispositivos de poca inercia.
- La síntesis determina el retardo de un circuito.

#+begin_src vhlc
y1 <= x after 100 ns;
y2 <= transport x after 100 ns;
#+end_src

*** Ejecución Concurrente
- Los módulos lógicos se ejecutan concurrentemente.

*** Diseños marginales
- Existen diferencias de retardos entre chips dependiendo de las condiciones de fabricación.
      - Incluso dentro de una misma oblea.
- Por eso no es buena idea tomas un diseño que dependa de la propagación mínima.

*** Fortaleza de las señales
- La salida de un módulo puede ser conectada como máximo a un determinado número de entradas de otros módulos.
      - La señal eléctrica se debilita.
- *árbol de buffers*, permite conectar a más entradas una salida sin que se debilite la señal.
      - Además iguala los retardos de propagación a todas las entradas.
      - útil para tener sincronizados circuitos flip-flop.

# gráfico pag 51

** Test de los circuitos
- Ayuda al diseño en el proceso de diseño de un chip.
- Tamiza los chips defectuosos.
- Procedimiento básico
      - Se establecen valores en las entradas de un circuito.
      - Se comprueban las salidas con el valor esperado.
- *Vector de test*, todos los valores que se asignan a las entradas de un circuito.

*** Test en manufactura
- Detectar problemas en el proceso de fabricación
- Causas comunes
      - *Abiertos*, conexiones que han quedado abiertas.
      - *Cortos*, conexiones establecidas que no deberían estar.
      - *Acoplos*, Valores lógicos que inadvertidamente cambian el calor lógico de otra parte del circuito.
- La forma de modelar un error es suponer que un aparte del circuito siempre da el valor 1 o 0 independientemente del valor de entrada.
      - Se diseñan tests para detectar este comportamiento (tests que predicen cual sería la salida si una parte del circuito siempre da 1 o 0).]
      - Si los tests predicen un error se dice que el error esta cubierto por el vector de test.
- El test de circuitos secuenciales es más dificil porque se tiene en cuenta el estado del circuito.
      - Se puede diseñar una secuencia inicial para poner el circuito en el estado deseado antes de ejecutar los tests.
      - Usar *Scan flip-flops* en el diseño, flip-flops que se pueden configurar desde las entradas al circuito.
- Mayor número de tests mejor cobertura de erroes.
- Menor número de tests se pueden comprobar más circuitos.

*** Test funcional
- Se emplea en todas las fases de diseño de un circuito.
- Tanto a las partes individuales de bajo nivel como a las combinaciones de estas de más alto nivel.
- Los primero prototipos suelen tener errores de diseño.

*** Programa de test funcional
- Se tiende a probar todas las posibles entradas posibles para un circuito.
- Métodos heurísticos para seleccionar vectores de test.
      - Conocimiento sobre el circuito puede descartar las combinaciones imposibles.
      - Test exhaustivo de los subcircuitos, menod exhaustivo del circuito completo.
      - Escoger conjuntos representativos de vectores de entrada. Relacionadas con la aplicación imagino.
- Comprobar tests        
      - Es importante comparar los resultados obtenidos con un conjunto de soluciones correctas comprovadas.
      - Calcular la salida esperada con otro procedimiento y compararlo con el resultado del test.

*** Banco de pruebas
- *Banco de pruebas* Codificar en HDL los tests en un módulo (subcircuito generador).
- Partes de un banco de pruebas
      - Subcircuito generador.
      - *UUT*, el circuito siendo probado
      - Subcircuito de comprobación de los resultados.
- Importante recalcar que deben testearse también los subcircuitos de un diseño jerárquico.

** Representaciones y niveles de abstracción
*** Representación del sistema
**** Representación del comportamiento
- Describe la funcionalidad del sistema.
- Se ignora su implementación interna.
- Se definan las entradas y las salidas que deben obtenerse.

**** Representación de la estructura
- Describe la implementación interna del sistema.
- Qué componentes y como están conectados entre si.
- net, conjunto de cables conectados a un mismo nodo.
- netlist, Descripción esquemática del sistema.

**** Representación física
- Características físicas del sistema.
- Tamaño de los componentes, disposición física, cableado físico.
- Es la especificación final para la fabricación del sistema.

*** Niveles de abstracción
- No se enfoca la atención en el transistor en concreto, los niveles de abstracción permiten dividir el enfoque a la hora de tratar el diseño.

**** Nivel de transistor
- Nivel bás bajo
- resistencias, transistores, capacitores.
- Sistema descrito por ecuaciones diferenciales y algebraicas que pueden simularse en entornos como Spice.
- Sistema analógico

**** Nivel de puertas lógicas
- Bloques constitutivos básicos son AND, OR, XOR, MUX 2:1, memorias o flip-flops entre otros.
- Se considera si las señales están por encima de un umbral (0 o 1 digital).
- Sistema descrito por operaciones discretas.
- Retardo de la propagación, tiempo que precisa un sistema para proporcionar una señal estable.
- La representación física consiste en la situación espacial de los componentes y del routing.
- Se usa el área de la puerta NAND como medida básica de medida.

**** Nivel de transferencia entre registros (RTL)
- Módulos funcionales
- Las señales pueden intrepetarse como dato.
- Se usan máquinas de estados finitos para describir el sistema.
- Si está bien diseñado podemos hablar en términos de ciclos de reloj.

**** Nivel de procesador
- Mayor nivel de abstracción.
- procesadores, módulos de memoria, etc

** Desarrollo en VHDL  
*** Banco de pruebas
- Ejemplo de código VHDL en un banco de pruebas.

#+begin_src vhdl
-- Banco de pruebas del detector de paridad.
-- fichero bp_detectorPar.vhd

library IEEE;
use IEEE.std_logic_1164.all;

entity bp_detectorPar is
end entity bp_detectorPar;

architecture bp_arch of bp_detectorPar is
  component detectorPar is
    port (par : out std_logic;
          a   : in std_logic_vector(2 downto 0));
  end component detectorPar;
  signal test_in : std_logic_vector(2 downto 0);
  signal test_out : std_logic;
begin
  UUT: detectorPar port map ( par => test_out, a => test_in);
  
  vect_test: process
  begin
    test_in <= "000";  wait for 200 ns;
    test_in <= "001";  wait for 200 ns;
    test_in <= "010";  wait for 200 ns;
    test_in <= "011";  wait for 200 ns;
    test_in <= "100";  wait for 200 ns;
    test_in <= "101";  wait for 200 ns;
    test_in <= "110";  wait for 200 ns;
    test_in <= "111";  wait for 200 ns;
  end process vect_test;

  verif: process
    variable error_status : boolean;
    begin
      if ((test_in = "000" and test_out = '1') or
          (test_in = "001" and test_out = '0') or
          (test_in = "010" and test_out = '0') or
          (test_in = "011" and test_out = '1') or
          (test_in = "100" and test_out = '0') or
          (test_in = "101" and test_out = '1') or
          (test_in = "110" and test_out = '1') or
          (test_in = "111" and test_out = '0') or
          )
      then
        error_status := false;
      else
        error_status := true;
      end if
      assert not error_status report "Test Fallado." severity note;
  end process verif;
end architecture bp_arch;
#+end_src

*** Buffer triestado
#+begin_src vhdl
-- Modelo del buffer triestado
-- bufferTriestado.vhd
library IEEE;
use IEEE.std_logic_1164.all;

entity Buffer_TriEstado is port
                             (
                               y: out std_logic;
                               E: in  std_logic;
                               d: in  std_logic
                               );
end entity Buffer_TriEstado;

architecture Behavioral of Buffer_TriEstado is
begin
  process (E,d)
  begin
    if (E = '1') then
      y <= d;
    else
      y <='Z';  -- Z debe ser alta impedancia
    end if;
  end process;
end architecture Behavioral;
#+end_src

#+begin_src vhdl
-- Banco de pruebas
-- bp_bufferTriestado.vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity bp_Buffer_TriEstado is
end entity bp_Buffer_TriEstado;

architecture bp_Buffer_TriEstado of bp_Buffer_TriEstado is
  signal y : std_logic;
  signal d,E : std_logic;

  component Buffer_TriEstado is port
                                  (
                                    y : out std_logic;
                                    E,d : in std_logic;
                                    );
  end component Buffer_TriEstado
begin
  -- Instanciar y conectar UUT
  uut : component Buffer_TriEstado port map
    (y => y, E => E, d => d);

  gen_vec_test : process
  begin
    E <= '0'; d<= '0';
    wait for 10 ns;
    d <= '1';
    wait for 10 ns;
    E <= '1';
    wait for 10 ns;
    d <= '0';
    wait for 10 ns;
    report "Final de la simulación";
    wait;
  end process gen_vec_test;
end architecture bp_Buffer_TriEstado;
#+end_src

* Conceptos Básicos de VHDL
** Unidades de diseño
- *Entity*, Definición de la interfaz entre el diseño y el entorno que la usa.
      - Define *puertos de conexión* (señales entrada salida).
      - Lo que es visible desde el mundo exterior.
- *Architecture*, Define el comportamiento y la estructura de la entidad de diseño.
      - Permite varias *architecture* para una *entity*.
- *Package*, agrupa una colección de tipos de datos, subprogramas y componentes.
      - Lo veo como una librería.
- *Configuration*, Permite relacioner en tiempo de compilación la entity con la architecture.
      - Está fuera del temario (ver en la documentación del ghdl).

** Entity
*** Cláusula port
- Señales de la interfaz

#+begin_src vhdl
entity nombre is
  port(
    nombrePtSalida1 : (out|inout) tipo_dato;
    ...
    nombrePtEntreda1 : (in) tipo_dato;
    ...
);
end entity nombre;
#+end_src  

- Señales de salida no pueden usarse nunca para alimentar otro puerto.
      - Conviene definir señales intermedias. Por ejemplo.

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity modoPuertos is
  port(
    x,y : out std_logic;
    a,b : in std_logic
    );
end entity modoPuertos;

architecture arch_correcta of modoPuertos is
  signal ab : std_logic;             -- Señal intermedia del valor a and b
begin
  ab <= a and b;
  x <= ab;
  y <= not ab;                       -- y <= x está mal
                                     --  x es modo out
end architecture arch_correcta  
#+end_src

*** Cláusula generic
- Se declara en la *entity*
- Declara constantes que necesitan ser modificadas para adaptar el diseño a diferentes aplicaciones.
- Valores típicos son los bits de un bus o el valor de los retardos

#+begin_src vhdl
entity and2 is
  generic (Tpd : time);    -- Cláusula generic, puede ser usado
                           --  en el cuerpo de cualquier
                           --  architecture asociado
  port    (y0 : out std_logic;
           x0, x1 : in std_logic);
end entity and2;
#+end_src

*** Declaraciones
- subprogramas, atributos tipos de datos, etc que son visibles desde la propia *entity* y las *architectures* asociadas.

#+begin_src vhdl
entity bp is
  constant WORD_SZ : integer := 16;
  constant DELAY   : timer   := 10 ns;
end entity bp;
#+end_src

*** Sentencias
- sentencias assert.
- llamadas concurrentes a procedimientos.
- bloques process.
- No deben producirse asignaciones a señales.
- Se incluyen después de la asignación de puertos.

** Architecture
- Define el comportamiento y la estructura de la entidad de diseno.
      - *Descripción estructural*, conexión de componentes de más bajo nivel.
      - *Descripción de su comportamiento*.
      - *Descripción mixta*, estructural y de comportamiento.

#+begin_src vhdl
architecture nombre_architecture of nombre_entity is
  -- Declaración de señales y constantes locales
  -- Declaración de componentes
  -- Declaración de subprogramas
begin
  -- Instanciación de los componentes
  -- Asignaciones concurrentes a señales y bloques process
end architecture nombre_architecture;  
#+end_src        

** Asignaciones concurrentes
- *Asignaciones concurrentes*, asignaciones contenidas entre el *begin* y el *end* de un *architecture*.
- Se evaluan de forma concurrente.

*** Asignación concurrentes simples
Sintaxis:
#+begin_src vhdl
señal <= forma_de_onda;
#+end_src

La ejecución de una señal de asignación concurrente simple se produce en el instante en que cambia el valor de alguna de las señales que aparecen en la expresión a la derecha de <=.

Se puede especificar el valor de retardo.

#+begin_src vhdl
y0 <= x1 + x2 after 10 ns;               -- 10 ns de retardo inercial
y1 <= transport x3 + x4 after 10 ns;     -- 10 ns de retardo de transporte
#+end_src

Si no se indica el retardo es infinitesimal $\delta$.

*** Asignación concurrentes condicionales
Sintaxis:
#+begin_src vhdl
señal <= expr_nuevo_valor_señal_1 when expr_booleana_1 else
         expr_nuevo_valor_señal_2 when expr_booleana_2 else
         expr_nuevo_valor_señal_3 when expr_booleana_3 else
         ...
         expr_nuevo_valor_señal_n;
#+end_src

- Se evalua por orden, el nuevo valor calculado se asigna trascurrido un retardo, por defecto $\delta$.

Ejemplo MUX 8:1
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity mux4 is
  port (
    x : out std_logic_vector(7 downto 0);       -- de 7 a 0, 8 bits
    a,b,c,d : in std_logic_vector(7 downto 0);
    s       : in std_logic_vector(1 downto 0));
end entity mux4;

architecture arch_cond of mux4 is
begin
  x <= a when (s="00") else
       b when (s="01") else
       c when (s="10") else
       d;
end architecture arch_cond;  
#+end_src

- La sintesis en hardware de las sentencias condicionales involucran.
      - Circuitos para expresiones booleanas.
      - Circuito que implementa la red de prioridad (red MUX 2:1).

*** Asignaciones concurrentes de selección
:PROPERTIES:
:ID:       3138112f-bc3c-469b-97bf-aad8115fac95
:END:

#+begin_src vhdl
with expresion_seleccion select
  señal <= expr_nuevo_valor_señal_1 when valor_seleccion_1,
           expr_nuevo_valor_señal_2 when valor_seleccion_2,
           ...
           expr_nuevo_valor_señal_n when valor_seleccion_n;
#+end_src

- *expresion_seleccion* puede ser un entero o un vector unidimensional.
- Puede definirse explicitamente los retardos o usar el valor ínfimo $\delta$.
- valor_selección_# deben cumplir algunas restricciones.
      - Deben ser mutuamente excluyentes.
      - Deben incluir todos los posibles valores de *expresión_selección*.

Ejemplo MUX 4:1

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity mux4 is
  port( x : out std_logic_vector(7 downto 0);
        a,b,c,d : in std_logic_vector(7 downto 0);
        s : in std_logic_vector(1 downto 0));
end entity mux4;

architecture arch_selec of mux4 is
begin
  with s select
    x <= a when "00",
         b when "01",
         c when "10",
         d when others;       -- others para el resto
end architecture arch_selec;
#+end_src

Ejemplo Prioridad 4 a 2

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity codificadorPrioridad4a2 is
  port ( codigo : out std_logic_vector(1 downto 0);
         activo : out std_logic;
         x      : in  std_logic_vector(3 downto 0));
end entity codificadorPrioridad4a2;

architecture codPrior4a2_selec of codificadorPrioridad4a2 is
begin
  with x select
    codigo <= "11" when "1000" | "1001" | "1010" | "1011" |
                        "1100" | "1101" | "1110" | "1111",
              "10" when "0100" | "0101" | "0110" | "0111",
              "01" when "0010" | "0011",
              "00" when others;
    activo <= x(3) or x(2) or x(1) or x(0);
end architecture codPrior4a2_selec;
#+end_src

*** Sensibilidad de las sentencias concurrentes
- Una asignación concurrente es /sensible/ a todas las señales que intervienen en el cálculo del valor.
- Una sentencia condicional es /sensible/ a todas las señales que intervienen en el cálculo del nuevo valor y de las condiciones booleanas.
- Una sentencia de selección concurrente es /sensible/ a todas las señales que intervienen en el nuevo valor y las condiciones booleanas.

** Sentencia Generate
Facilita la ejecución iterativa o condicional de una porción de código concurrente.

*** Sentencia generate iterativa
Sintaxis
#+begin_src vhdl
etiqueta: for indice in rango_bucle generate
  -- Declaración de señales locales y constantes locales
begin  -- Puede omitirse si no se declaran señales o constantes locales
  -- sentencias_concurrentes
end generate etiqueta;
#+end_src

- Sólo es sintetizable si los límites del rango son estáticos.

Ejemplo
#+begin_src vhdl
signal z : std_logic_vector(7 downto 0);
signal x : std_logic_vector(7 downto 0);
signal y : std_logic_vector(15 downto 0);
E1 : for i in x'range generate   -- x'range para iterar por los índices de x
  z(i) <= x(i) AND y(i+8);
end generate E1;
#+end_src

*** Sentencia generate condicional
#+begin_src vhdl
etiqueta : if expresion_booleana generate
  -- Declaración de señales y constantes locales
begin
  -- Sentencias Condicionales
  etiqueta2 : if expresion_booleana2 generate  -- generate anidado
    -- ...
  end generate etiqueta2;
end generate etiqueta;
#+end_src

*** Bloque process
#+begin_src vhdl
-- la etiqueta es opcional pero recomendable
etiqueta : process(lista_de_sensibilidad)          -- Se ejecuta cada vez que cambia el valor
                                                   --  de algún elemento de la lista de sensibilidad
  -- Declaración de variables locales
  variable nombre_variable tipo rango := valor_inicial;  -- valor_inicial no es sintetizable
  -- Declaración de subprogramas (funciones y procedimientos)
begin
  -- Código secuencial
end process etiqueta;
#+end_src

- Se ejecutan en orden secuencial.
- No puede declararse señales.
- Los bloques process son concurrente entre ellos.
- El bloque se ejecuta indefenidamente, para controlar la ejecución de un bloque process usamos.
      - *lista de sensibilidad*
      - sentencias *wait*

*** Sentencias wait
**** Wait on
Sintaxis
#+begin_src vhdl
wait on señal1, señal2, ..., señalN;
#+end_src

- Suspende la ejecución de código secuencial hasta que cambia el valor de alguna señal.

**** Waint until
Sintaxis
#+begin_src vhdl
wait until expresion_booleana;

wait on señal1, ..., señalN  -- Puede especificarse la lista de sensibilidad
  until expresión_booleana;
#+end_src

- Se suspende la ejecución hasta que se evalue la expresión booleana y esta sea *true*.
      - Solo se tienen en cuenta el cambio de valor de las señales para evaluar la expresión.

**** Wait for
Sintaxis
#+begin_src vhdl
wait for expresion_temporal;
#+end_src

- Suspende la ejecución hasta que transcurra determinado intérvalo de tiempo.

Se puede combinar con otros wait
#+begin_src vhdl
wait until clk='1' and enable and v<30 for 50 ns;
#+end_src

- Suspende la ejecución secuencial hasta una de las dos condiciones.
      - Cambia el valor de alguna señal y además se satisface `clk='1' and enable and v<30`.
      - han pasado 50 ns.

*** Lista de sensibilidad
- El bloque process se es ejecutado en el instante que una o varias señales de la lista cambian de valor.
- Tan solo pueden incluirse puertos de entrada (pueden ser leídos).
- No se permite emplear sentencias *wait* y lista de sensibilidad en un mismo bloque *process*.

#+begin_src vhdl
-- Biestable D con reset asíncrono activado en LOW
library IEEE;
use IEEE.std_logic_1164.all;

entity flipflop_D is port (
  q, q_n : out std_logic;
  d, clk, reset_n : in std_logic);
end entity flipflop_D;

architecture flipflop_D of flipflop_D is
begin
  process (reset_n, clk) is       -- Lista de sendibilidad con reset_n y clk
  begin
    if reset_n = '0' then
      q <= '0';
      q_n <= '1';
    elsif rising_edge(clk) then   -- flanco de subida?
      q <= d;
      q_n <= not d;
    end if
  end process
end architecture flipflop_D
#+end_src

** Código Secuencial
*** Asignación secuencial a una señal
#+begin_src vhdl
señal <= expr_nuevo_valor_señal
#+end_src

- Imlícitamente se entiende un retardo $\delta$.
- Si el bloque *process* tiene lista de sensibilidad, se asigna a cada señal el nuevo valor cuando han finalizado todas las sentencias del bloque.
- Las señales nunca adquieren valores intermedios.

#+begin_src vhdl
x1, x2, x3, x4, y: std_logic;
-- ...
process (x1, x2, x3, x4)
  begin
    y <= x1 and x3;
    y <= x1 or x2;
    y <= x3 and x4;
  end process
#+end_src  

Equivale a

#+begin_src vhdl
x1, x2, x3, x4, y: std_logic;
-- ...
process (x1, x2, x3, x4)
  begin
    y <= x3 and x4;
  end process
#+end_src

Si fuera código concurrente habría riesgo de conflicto.

*** Asignación secuencial a una variable
- Dentro de un bloque *process* pueden asignarse variables.
  
#+begin_src vhdl
variable := expr_nuevo_valor_variable;
#+end_src

- En asignación a variables no se produce *retardo* $\delta$.

#+begin_src vhdl
signal x1, x2, y : std_logic;
process (x1, x2)
  variable aux : std_logic;
begin
  aux := '0';         -- aux asume su valor inmediatamente en cada sentencia
  aux := aux or x1;
  aux := aux or x2;
  y <= aux;           -- aquí si que hay un retardo $\delta$
end process;
#+end_src

*** Sentencia if
#+begin_src vhdl
if expresion_boolana_1 then
  -- sentencias_secuenciales
elsif expresion_booleana_2 then
  -- sentencias_secuenciales
-- ...
else
  -- sentencias_secuenciales
end if;
#+end_src

- Las expresiones booleanas se evaluan secuencialmente.

#+caption: Codificador prioridad 4 a 2
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity codificadorPrioridad4a2 is
  port (codigo : out std_logic_vector(1 downto 0);
        activo : out std_logic;
        x      : in  std_logic_vector(3 downto 0));
end entity codificadorPrioridad4a2;

architecture codPrior4a2_procIf of codificadorPrioridad4a2 is
begin
  process (x)
    if (x(3)='1') then
      codigo <= "11";
    elsif (x(2)='1') then
      codigo <= "10";
    elsif (x(1)='1') then
      codigo <= "01";
    else
      codigo <= "00";
    end if;

    activo <= x(3) or x(2) or x(1) or x(0);
  end process;
end architecture codPrior4a2_procIf;
#+end_src  

**** Introducción accidental de memoria
:PROPERTIES:
:ID:       bf513822-0bc9-4fc5-b590-7b183cefb87a
:END:
- Cuando se asigna valor a una señal en alguna de las ramas de una sentencia *if*, pero no en todas, entonces se está introduciendo "memoria" (diseño no combinacinal) en el circuito.
      - Se debe a que se definen estados y por tanto el uso de biestables.
      - Implica que todas las señales deben asignarse en cada bloque.
      - Implica el uso obligatorio de else.
      - Puede asignarse un valor por defecto a las señales para evitar este comportamiento.
            - Ante varias asignaciones a una señal con retardo $\delta$ solo se tiene en cuenta la última asignación.

#+begin_src vhdl
-- Este código se sintentiza de forma Combinacional
process(a,b)
begin
  mayor <= '0';        -- valores por defecto a cada variable,
  menor <= '0';        --  es una buena prácica.
  igual <= '0';
  if (a > b) then      -- Asignación a cada señal
    mayor <= '1';
  elsif (a < b) then
    menor <= '1';
  else
    igual <= '1';
  end if;
end process;
#+end_src        

*** Sentencia case
#+begin_src vhdl
case expresion_case if
  when valor_1 =>
    sentencias_secuenciales;
  -- ...
  when valor_n =>
    sentencias_secuenciales;
end case;
#+end_src

- Puede emplearse *others* como último valor para cubrir el resto de casos.

#+caption: Decodificador Binario 2 a 4
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity decodificador4 is
  port (x : out std_logic_vector(3 downto 0);
        x : in  std_lofic_vector(1 downto 0));
end entity decodificador4;

architecture arch_decProcCase of decodificador4 is
begin
  process (s)
    case s is
      when "00" =>
        x <= "0001";
      when "01" =>
        x <= "0010";
      when "10" =>
        x <= "0100";
      when others =>
        x <= "1000";
    end case;
  end process;
end architecture arch_decProcCase;
#+end_src  

- Análogo secuencial a [[id:3138112f-bc3c-469b-97bf-aad8115fac95][select]].
- Si se asigna un valor a una señal en un bloque case, pero no en los demás se está introduciendo [[id:bf513822-0bc9-4fc5-b590-7b183cefb87a][memoria]]. pag 132.

*** Bucle for
#+begin_src vhdl
for índice in rango_bucle loop   -- indice no necesita ser declarado
  sentencias_secuenciales
end loop;
#+end_src

- Para que el bucle for pueda ser *sinteizado* es precido que el rango_bucle quede fijado en la síntesis.

#+caption: XOR de los bits de una señal de 4 bit
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity xor_1señal_4bits is
  port (y : out std_logic;
        a : in  std_logic_vector(3 downto 0));
end entity xor_1señal_4bits;

architecture xor_1señal_4bits_bucleFor of xor_1señal_4bits is
  constant WIDTH : integer := 4;
  signal   tmp   : std_logic_vector(WIDTH-1 downto 0);
begin
  process(a, tmp)
  begin
    tmp(0) <= a(0);
    for i in 1 to (WIDTH-1) loop
      tmp(i) <= a(i) xor tmp(i-1);
    end loop;
  end process;
  y <= tmp(WIDTH-1);
end architecture xor_1señal_4bits_bucleFor;
#+end_src  

- La síntesis de un bucle for lo convierte en una secuencia plana de sentencias.

** Descripción de la estructura
- Describir un circuito mediante instanciación y conexión de otros circuitos.

*** Declarar los componentes
- un *component* representa una pareja entity/architecture.
- Define un determinado circuito.
- Si hay varias *architecture* asociadas deben especificarse definiendo una *configuration*.

#+begin_src vhdl
component nombre_componnete is   -- nombre_componente es el nombre del entity.
  clausula_generic;              -- Mismas que las que aparecen en el entity
                                 --  del circuito que se está instanciando.
  clausula_port;                 -- Mismas que las que aparecen en el entity
                                 --  del circuito que se está instanciando.
end component nombre_componnete;
#+end_src  

*** Instancias los componentes e indicar su conexión
#+begin_src vhdl
nombre_instancia : component nombre_componente  -- {component} es opcional
                   port map (asociación_puertos_señales);
#+end_src

- Para conectar puertos entre componentes se usan señales intermedias.
      - Asociadas a una misma señal del modelo compuesto.
      - *Asociación posicional*, mediante la posición en que el puerto se declara en la cláusula port de la *entity*.
      - *Asociación nominal*, tipo puerto => señal.

*** Ejemplos declaración e instanciación de componentes
#+caption: MUX 2:1 de 1 bit
#+begin_src vhdl
-- diagrama en página 137
library IEEE;
use IEEE.std_logic_1164.all;

entity Mux2_1bit is
  port (d      : out std_logic;
        i0, i1 : in std_logic;
        s0     : in std_logic);
end entity;

architecture Mux2_1bit of Mux2_1bit is
  component not1 is
    port(y0 : out std_logic;
         x0 : in  std_logic);
  end component not1;
  component or2 is
    port(y0     : out std_logic;
         x0, x1 : in std_logic);
  end component or2;
  component and2 is
    port(y0 : out std_logic;
         x0, x1 : in std_logic);
  end component and2;
  signal n1, n2, n3 : std_logic;                         -- señales intermedias
begin
  Inv_1  : not1 port map (x0 => s0, y0 => n1);           -- asociación nominal
  And2_1 : and2 port map (x0 => i0, x1 => n1, y0 => n2);
  And2_2 : and2 port map (x0 => i1, x1 => s0, y0 => n3);
  Or_1   : or2  port map (x0 => n2, x1 => n3, y0 => d);
end architecture Mux2_1bit;
#+end_src

#+caption: MUX 2:1 de 4 bit.
#+begin_src vhdl
-- diagrama en página 138
library IEEE;
use IEEE.std_logic_1164.all;

entity Mux2_4bit is
  port (d0, d1, d2, d3 : out std_logic;
        a0, a1, a2, a3 : in  std_logic;
        b0, b1, b2, b3 : in  std_logic;
        s0             : in  std_logic);
end entity Mux2_4bit;

architecture Mux2_4bit of Mux2_4bit is
  component Mux2_1bit is
    port (d      : out std_logic;
          i0, i1 : in  std_logic;
          s0     : in  std_logic);
  end component Mux2_1bit;
begin
  Mux2_0 : Mux2_1bit port map (d => d0, i0 => a0, i1 => b0, s0 => s0);
  Mux2_1 : Mux2_1bit port map (d => d1, i0 => a1, i1 => b1, s0 => s0);
  Mux2_2 : Mux2_1bit port map (d => d2, i0 => a2, i1 => b2, s0 => s0);
  Mux2_3 : Mux2_1bit port map (d => d3, i0 => a3, i1 => b3, s0 => s0);
end architecture Mux2_4bit;
#+end_src

*** Diseños con estructura regular
- pag 140
- La sentencia generate puede usarse para describir circuitos con estructura regular (estructura repetitiva).

#+caption: Array de puertas AND usando GENERATE  
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity arrayAND is
  port ( y     : out std_logic_vector(7 downto 0);
         i1,i0 : in  std_logic_vector(7 downto 0));
end entity arrayAND;

architecture arrayAND of arrayAND is
  component and2 is
    port (y0     : out std_logic;
          x0, x1 : in  std_logic);
  end component and2;
begin
  gen_array : for I in 7 downto 0 generate
  begin
    and_array: and2
      port map (y(I), i1(I), i0(I));
  end generate gen_array;
end architecture arrayAND;
#+end_src

#+caption: Detector de paridad usando sentencia GENERATE condicional
#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity paridad is
  port (parity : out std_logic;
        parity_IN : in std_logic_vector(7 downto 0));
end entity paridad;

architecture paridad of paridad is
  signal temp : std_logic_vector(6 downto 0);

  component xor2 is
    port (y0 : out std_logic;
          x0, x1 : in std_logic);
  end component xor2;

begin
  parity <= temp(6); -- no lo entiendo
  gen_array : for I in 0 to 6 generate
    inicial : if I=0 generate
      xor_0 : xor2
        port map (temp(0), temp(0), parity_IN(1));
    end generate inicial;

    intermedio : if I /= 0 generate
      resto_xor : xor2
        port map (temp(I), temp(I-1), parity_IN(I+1));
    end generate intermedio;

  end generate gen_array;
end architecture paridad;
#+end_src

** Parametrización
*** Parametrización del comportamiento

#+begin_src vhdl
entity and2 is
  generic ( Tdp : time);     -- Define el tiempo de retardo
  port    ( y0  : out std_logic;
            x0, x1 : in std_logic);
end entity and2;

architecture and2D of and2 is
begin
  y0 <= x0 and x1 after Tdp; -- Aquí se usa el parámetro Tdp
end architecture and2D;
#+end_src

*** Parametrización de la estructura
- Cuando se instancia un componente puede asignarse un calor a sus constantes generic.

#+caption: Sintaxis para asignar valores generic  
#+begin_src vhdl
nombre_instancia : component nombre_componente  -- component es opcional
  generic map (valores_constantes_generic)      -- asignación de valores generic
  port    map (asociación_puertos_señales);
#+end_src  

- Por ejemplo

#+begin_src vhdl
puertaAND1 : component and2
  generic map (Tdp => 3ns)
  port    map (y0 => sig_out, x0 => sig0, x1 => sig1);
#+end_src  

** Señales, Variables y Constantes
#+caption: Declaraciones  
#+begin_src vhdl
signal nombre_señal       : tipo_dato := valor_inicial;  -- valor inicial no es sintetizable
variable nombre_variable  : tipo_dato := valor_inicial;  -- valor inicial no es sintetizable
constant nombre_constante : tipo_dato := expresión;
#+end_src

- *Señales* : corresponden con las señales lógicas reales existentes en el circuito.
      - Los puertos solo pueden ser señales.
      - Son declaradas en *packages*, *entity* o *architecture*.
      - Asginaciones a *señales* pueden ser tanto concurrentes como secuenciales.
      - Siempre existe un retardo como mínimo $\delta$.
      - Tienen dirección.
            - No puede leerse una señal *out*.
            - No puede asignarse valor a una señal *in*.
      - Se emplea <=

#+begin_src vhdl
nombre_señal <= forma_de_onda;
#+end_src        
        
- *Variables* : Pueden o no corresponder con señales físicas.
      - Se definen variables para realizar cálculos que luego se asignan a las señales.
      - Como elemento intermedio antes de ser escrito en un puerto *out* (los puertos out no pueden ser leídos).
      - Son declaradas dentro de *process*, *function* y *procedure* (código secuencial).
      - Asignar valores a *variables* se realiza inmediatamente (no hay retardos).
      - Solo en bloques secuenciales.
      - Se emplea :=

#+begin_src vhdl
nombre_variable := expresión;
#+end_src        

- *Constantes* : El valor no cambia durante la simulación.
      - La asignación de valor se realiza en la declaración.
      - En las unidades *entity* y *architecture* deben definirse constantes antes del bloque *begin*.
      - Dentro de la definición de un *package* pueden definirse constantes.

#+begin_src vhdl
constant nombre_constante : tipo_dato := expresión;
#+end_src        

** Tipos de datos y operadores
- Un tipo de dato está definido por conjunto de valores y conjunto de operaciones posibles.
      - Es fuertemente tipado.

*** Tipos predefinidos en VHDL
- *integer* : rango mínimo 32 bits, incluye negativos positivos y el 0.
      - *natural* : 0 más números positivos.
      - *positive* : números positivos.
- *boolean* : true o false.
- *bit* : '0' o '1'
- *bit_vector* : vector unidimensional del tipo *bit*.
      - Los literales se escriben entre "", se omiten los símbolos "_"
      - X"FFF", hexadecimal
      - 0"7777", octal
      - B"1111_1111_1111", binario
      - "1111_1111_1111", por defecto binario

**** Operadores
- pag 148
      - Tabla de operadores
      - Tabla de precedencias
- Ante misma precedencia se evalua primero el de la izquierda.

*** Tipos del paquete IEEE.std_logic_1164
**** std_logic
- Posible valores:
      - '0'
      - '1'
      - 'U' : Valor sin inicializar.
      - 'X' : No puede determinarse el valor de la señal.
      - 'Z' : Alta impedancia.
      - 'W' : Desconocida débil.
      - 'L' : Cero débil.
      - 'H' : uno débil.
      - '-' : Don't care (no importa).

**** std_logic_vector
- vector de elementos *std_logic*.
- Según la declaración el bit más significativo estará a la derecha o a al izquerda.
      - Cuidado, el bit más significativo a la derecha puede dar errores con buses que representan números binarios.

#+begin_src vhdl
signal a : std_logic_vector(7 downto 0);  -- a7,...,a0
signal b : std_logic_vectir (o to 7);     -- a0,...,a7, puede dar errores con número binarios
#+end_src

**** Operadores
- Hay sobrecarga de operadores.
- El paquete IEEE.std_logic_1164 implementa los operadores necesarios.

*** Conversión de tipos  
- El paquete IEEE.std_logic_1164 incluye funciones para conversión de tipos.
  
| Conversión de:   | a:               | Función                |
|------------------+------------------+------------------------|
| std_logic        | bit              | to_bit(arg)            |
| bit              | std_logic        | to_stdulogic(arg)      |
| std_logic_vector | bit_vector       | to_bitvector(arg)      |
| bit_vector       | std_logic_vector | to_stdlogicvector(arg) |
|                  |                  |                        |

*** Operadores relacionales
- Comparaciones.
- Pueden comparar datos tipo vector.
      - Los operandos pueden tener diferente número de elementos.
      - Se compara elemento a elemento de izquierda a derecha.
      - Aún así es mejor evitar comparaciones de elementos de tamaños diferentes.
- = /= < <= > >=

*** Operador concatenación
- &
- Permite concatenar elementos, segmentos de vectores y vectores completos.

#+caption: Ejemplo de concatenación
#+begin_src vhdl
-- Desplazamiento de dos bits a la derecha
y <= "00" & a(7 downto 2);

-- Rotación de dos posiciones
y <= a(1 downto 0) & a(7 downto 2);
#+end_src  

*** Agregación de vectores

- Permite la asignación de valores a vectores

#+begin_src vhdl
x1 <= "101111";  -- asigna 47
x2 <= O"57";     -- asigna 47, octal
x3 <= X"2F";     -- asigna 47, hexadecimal
#+end_src  

- Asignación mediante asociación posicional

#+begin_src vhdl
y <= ('1', '0', '1', '0', '1', '0', '1', '0');
#+end_src  

- Asignación índice => valor, puede hacerse en cualquier orden

#+begin_src vhdl
y <= (7=>'1', 6=>'0', 5=>'1', 4=>'0', 3=>'1', 2=>'0', 1=>'1', 0=>'0');
#+end_src  

- Con combinación de índices

#+begin_src vhdl
y <= (7 | 5 | 3 | 1 => '1',
      6 | 4 | 2 | 0 => '0');
#+end_src

- O usando la palabra reservada *others*

#+begin_src vhdl
y <= (7 | 5 | 3 | 1 => '1',
      others        => '0');
#+end_src  

*** Tipos del paquete IEEE.numeric_std
- Pueden realizarse operaciones aritméticas sobre los datos del tipo *integer*.
      - Pero se dificulta el trabajo de síntesis aunque valga para simular.
      - IEEE.numeric_std intenta solucionar ese aspecto.

**** unsigned y signed
- Definidos en IEEE.numeric_std
- Son vectores del tipo *std_logic*.
- *unsigned* : número binario sin signo.
      - bit más significativo a la izquierda.
- *signed* : número binario con signo en formato complemento a 2.
      - bit más significativo a la izquierda.
- Declaraciones similares a std_logic_vector.

#+begin_src vhdl
signal a : signed (15 downto 0);
#+end_src

- uso del paquete IEEE.numeric_std

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
#+end_src  

**** Operadores
- Están sobrecargados abs, *, /, mod, rem, + y -.
- Puede producirse rebosamiento.

#+begin_src vhdl
signal a,b,c,d : unsigned (7 downto 0);
-- ...
a <= b+c;
d <= b+1;
#+end_src

- Están sobrecargados *=, /=, <, <=, >, >=*.
      - Asegura la comprobación con tipo signed y unsigned por el valor que representan.

**** Funciones
- *shift_left(a,b)*, *shift_right(a,b)*, *rotate_left(a,b)*, *rotate_right(a,b)*.
  Operaciones de desplazamiento y rotación.
      - a : signed o unsigned
      - b : natural
      - return : signed o unsigned
- *resize(a,b)* : Modifica el número de bits.
      - a : signed o unsigned
      - b : natural
      - return : signed o unsigned
- *std_match(a,b)* : Se emplea para comparar vectores con el valor '-'.
      - a : signed o unsigned
      - b : mismo tipo que a
      - return : boolean

#+begin_src vhdl
-- Ejemplo de std_match
código <= "11" when std_match(x, "1---") else
          "10" when std_match(x, "01--") else
          "01" when std_match(x, "001-") else
          "00";
#+end_src        

**** Conversión entre tipos
- pag 160
- *to_unsigned*, *to_signed*, *to_integer*.
      - Conversiones hacia integer.
- *std_logic_vector*, *unsigned* y *signed* tienen casting directo.

#+begin_src vhdl
signal u1, u2 : unsigned         (7 downto 0);
signal x1, x2 : std_logic_vector (7 downto 0);
-- ...
u1 <= unsigned(x1);
x2 <= std_logic_vector(u2);
#+end_src

*** Tipos time y string
- Útiles para depuración.
- *time* : representa el tiempo simulado.
      - Unidad femtosegunfo = $10^{-15}s$
- *string* : sirve para mostrar mensajes por  pantalla.
      - *report* : es el print de vhdl, solo acepta *string*.

*** Tipos definidos por el usuario
- Se permite al usuario definir sus propios tipos.

**** Tipo enteros definidos por el usuario
#+begin_src vhdl
type miEntero     is range -32 to 32;
type miPalabraMem is range 0 to 1024                 
#+end_src

**** Tipos enumerados
#+begin_src vhdl
typo opcode_type is (SUMA, RESTA, SALTO, PARAR);
#+end_src

- El problema es que no se define el código binario de cada opción.

**** Tipos vectoriales definidos por el usuario  
#+begin_src vhdl
type nombre_tipo is array especificacion_dimension of tipo_dato;
#+end_src

- Ejemplo de una matriz

#+begin_src vhdl
type regFile_type is array (0 to 3) of std_logic_vector(7 downto 0);
constant data : regFile_type :=
  (('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'));
signal reg_File : regFile_type;
-- ...
-- acceso tal que reg_File(2)(3)
#+end_src

- Ejemplo de matriz std_logic

#+begin_src vhdl
type matriz2D is array (0 to 3, 7 downto 0) of std_logic;
constant data : matriz2D :=
  (('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'),
   ('0', '0', '1', '1', '0', '0', '1', '0'));
signal mem_data : matriz2D;
#+end_src  

** Atributos
- pag 166
- Propiedades de los tipos de datos.
      - No todos lo satributos son soportados para síntesis.
- Se puede definir atributos propios.

#+begin_src vhdl
signal d : std_logic_vector(7 downto 0);
-- d'low=0   d'high=7   d'left=7   d'right=0
-- d'length=8   d'range=(7 downto 0)   d'reverse_range=(0 to 7)
#+end_src

- Son útiles para preparar bancos de pruebas.
      - No es necesario que se puedan sintetizar.
- *<tipo>'image(señal)* : convierte la señal a string.

** Librerías
- pag 167
- Contiene la definición de un conjunto de tipos, definición de operadores y funciones que pueden aplicarse a esos tipos.
- *packages* : sublibrerías que estructuran el contenido de una librería.
- *IEEE* es la librería, algunos paquetes son:
      - IEEE.std_logic_1164
      - IEEE.numeric_std
      - IEEE.math_real

** ASSERT
- pag 169
- Comprobaciones lógicas que dado el valor esperado en un punto del estado del programa debería valer true.
- Bueno para evitar errores.

#+begin_src vhdl
assert condicion_booleana report mensaje_a_mostrar severity nivel_severity;
#+end_src

- Si la condición vale false se muestra el mensaje.
- *nivel_severity* son:
      - note
      - warning
      - error
      - failure

** Subprogramas
- Fragmentos de código secuencial.

*** Funciones
- pag 171
- Rutina que devuelve un valor.
- Devuelve el resultado de aplicar un Código secuencial a partir de los parámetros formales.
- Puede ser invocado en sentencias concurrentes y secuenciales.
- Los parámetros de entrada son todos constantes (*in*).
- No puede emplearse *wait* dentro de una función.

#+begin_src vhdl
function nombre_función lista_param_formales return tipo_dato is
  declaración de variables locales y constantes locales
begin
  sentencias secuenciales
end function nombre_funcion;
#+end_src

#+begin_src vhdl
function f (c1,c2 : integer; signal s : std_logic_vector) return boolean is
-- ...
end function f;  
#+end_src

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity conv_int is
  port(y : out integer range 0 to 15;
       h : in std_logic_vector(3 downto 0));
end entity conv_int;

architecture conv_int of conv_int is
  function conv_integer(signal vector : std_logic_vector) return integer is
    variable resultado,pot: integer range 0 to 2**vector'length-1;
  begin
    pot := 1;
    if(vector(vector'low)='1') then
      resultado := 1;
    else
      resultado :=0;
    end if;
    for i in (vector'low+1) to (vector'high) loop
      port := pot*2;
      if(vector(i)='1') then
        resultado := resultado + pot;
      end if;
    end loops;
    return resultado;
  end function conv_integer;

begin
  y <= conv_integer(a);
end architecture conv_int;
#+end_src

*** Procedimientos
- Puede devolve más de un valor
- Puede declararse en la parte declarativa del *architecture* y de los bloques *process*.
- Puede invocarse en código concurrente o secuencial.
      - En código concurrente es como si los parámetros *in* e *inout* fueran la lista de sensibilidad con un *wait* implícito al final.
- Se permite el uso de *wait*, aunque no es sintetizable.

#+begin_src vhdl
procedure nombre_procedimiento lista_param_formales is
  declaracione de variables locales y constantes locales
begin
  sentencias secuenciales
end procedure nombre_procedimiento;
#+end_src  

- Existen parámetos formales de entrada y salida.
      - *in*, *out* o *inout*.
      - *in* no puede modificarse.
      - Por defecto se asume *in* si no se especifica.
      - *out* *inout* por defecto son *variables* si no se especifica.
- Sintaxis declaración de parámetros formales
  
#+begin_src vhdl
constant nombre_constante : modo tipo_dato;
signal   nomre_señal      : modo tipo_dato;
variable nombre_variable  : modo tipo_dato;
#+end_src

#+begin_src vhdl
procedure proc (a          : in std_logic;
                signal b,c : in std_logic;
                signal x   : out std_logic_vector(7 downto 0);
                signal y   : inout integer range 0 to 99) is
-- ...
end procedure proc;  
#+end_src

- La asignación de los valores o parámetros actuales a los parámetros formales pueden ser:
      - Asociación posicional
      - Asociación del tipo : param_formal => (valor_actual | param_actual)

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

entity minMax is
  generic(limite : integer := 255);
  port (min_out, max_out : out integer range 0 to limite;
        ena : in std_logic;
        d1_in, d2_in : in integer range 0 to limite);
end entity minMax;

architecture minMax of minMax is
  procedure ordena(signal in1, in2 : in integer range 0 to limite;
                   signam min,max : out integer range 0 to limite) is
    begin
      if (in1 > in2) then
        max <= in1;
        min <= in2;
      else
        max <= in2;
        min <= in1;
      end if;
    end procedure ordena;
    
  begin

    process(ena)
    begin
      if(ena='1') then
        ordena(d1_in, d2_in, min_out, max_out);
      end if
    end process;
end architecture minMax;
#+end_src

*** Diferencias entre funciones y procedimientos
- pag 176

** Paquetes
- Contiene:
      - subprogramas para pode ser reutilizados en diferentes proyectos.
      - Tipos de datos.
      - componentes.
      - constantes.
- Sintaxis

#+begin_src vhdl
package nombre_paquete is
  declaraciones   -- Contiene todas las declaraciones de
                  --  componentes, tipos y subprogramas
end package nombre_paquete;

package body nombre_paquete is
  descripción de funciones y procedimientos  -- Necesario para subprogramas
end package body nombre_paquete;
#+end_src

- Imagina que se compila en la librería *work*, para usar ese paquete hay que hacer:

#+begin_src vhdl
use work.ejemplo1.all;
#+end_src

- Ejemplos

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;

package pack1 is
  function conv_integer (signal vector : std_logic_vector) return integer;
end package pack1;

package body pack1 is
  function conv_integer (signal vector : std_logic_vector) return integer is
    variable resultado, pot : integer range 0 to 2**vector'length - 1;
  begin
    pot := 1;
    if (vector(vector'low)='1') then
      resultado :=1;
    else
      resultado := 0;
    end if
    for i in (vector'low - 1 + 1) to (vector'high) loop
      pot := pot * 2;
      if (vector(i)='1') then
        resultado := resultado + pot;
      end if;
    end loop;
    return resultado;
  end function conv_integer;
end package body pack1;
#+end_src

#+begin_src vhdl
library IEEE;
use IEEE.std_logic_1164.all;
use work.pack1.all;

entity conv_int1 is
  port (y : out integer range 0 to 15;
        a : in std_logic_vector(3 downto 0));
end entity conv_int1;

architecture conv_int1 of conv_int1 is
begin
  y <= conv_integer(a);
end architecture conv_int1;
#+end_src

* Simulación del código VHDL
- Comparación entre *signal* y *variable*

|                | signal                                                 | variable                   |
| Asignación     | <=                                                     | :=                         |
| Qué representa | Interconexiones en el circuito                         | Información local          |
| Visinilidad    | Puede ser global (visible desde todo el código)        | Local                      |
| Comportamiento | El nuevo valor es asignado transturrido un retardo     | No existe retardo          |
| Uso            | package, entity, architecture. los puertos son señales | Sólo en código secuencial. |

** Procesamiento del código VHDL
- Normalmente se procesa usando una herramienta CAD, etapas:
      1. *Análisis* : Se comprueba la sintáxis y la semántica.
             - El análisis ocurre sobre cadaunidad de diseño.
                   - Si existen dependencias entre ellas debe seguirse un determinado orden.
      2. *Elaboración* : Empieza por la unidad de diseño de nivel superior y enlaza el *entity* con su *architecture*.
             - En la *architecture* se van reemplazando los componentes por su definición.
                   - Recursivamente hasta aplanar el sistema.
      3. *Ejecución* : La descripción plana del sistema sirve como entrada al software de simulación o de síntesis.
             - Se resuelve la *inicialización* (cálculo del valor inicial de las señales *explícitas* e *implícitas*).
             - Los bloques *process* son ejecutados hasta que son suspendidos.

** Orden de complicación
- Orden:
      1. Declaraciones de los *package* teniendo en cuenta las interdependencias.
      2. *entity* que hacen uso de los *package* anteriores.
             - Las entity representan dependencias para otros componentes.
      3. Las *architecture*, una architecture no representa una dependencia para otro componente.
      4. Unidades de diseño *configuration*.
      5. *package body* en cualquier orden.
             - No representan dependencias para otros componentes.

- Las dependencias pueden obligar a recompilar varias unidades de diseño ante una modificación de código:
      1. Si la declaración de un *package* cambia deben recompilarse las *entity*, *architecture* y *configuration* que hace uso del *package*.
      2. Si cambia el *package body* solo afecta al package body.
      3. Si se modifiva una *entity* se deben recompilar las *architecture* que utilizan es entity.
             - También las architecturas que instancian components con esa entity.
      4. Si una *architecture* se modifica no afecta a otros elementos.
      5. Si cambia una *configuration* es preciso recompilar dicha configuration.

** Drivers
- Empleado por el simulador VHDL a fin de realizar la simulación.
- Se crean automáticamente en la fase de *elaboración*.
- Cada señal tiene uno o varios drivers asociados.
      - El valor de la señal se determina por el valor de sus drivers.
      - Si solo tiene un driver entonces el valor de la señal y del driver coinciden en todo momento.
- Reglas de asociación:
      - Un driver para la señal por cada asignación concurrente.
      - Si dentro de un bloque process se asigna un valor a la señal, entonces se asocia un driver al bloque process.
            - Si hay varias asignaciones a la señal se sigue asociando un único driver.
            - Un driver por cada bloque process diferente.
- El *driver* contiene una cola donde almacena las transacciones futuras.
      - Creo que la cola se ordena en orden no descendente te tiempo.
      - La transacción consta del nuevo valor dela señal y del instante de tiempo (tiempo total).
      - El valor del driver va cambiando de acuerdo se consumen las transacciones, que van siendo eliminadas.
- Si hay varios drivers asociados a una señal con valores diferentes se produce un conflico.
      - Se recurre a la *función de resolución* para resolverlo.
            - Depende del tipo de la señal, *std_logic* tiene función de resolución definida en *std_logic_1164*.
      - Si no existe función de resolución puede producirse un error.

** Inicialización
- Cálculos para obtener los valores en el instante $t=0$.
- Según el valor inicial:
      - Si una señal declara su valor inicial, los driver de la señal tienen dicho valor.
            - Las herramientas de síntesis ignoran este valor.
      - Si no se especifica el valor inicial que adquieren los derivers depende del tipo.
            - en std_logic el valor inicial es 'U'.
- A continuación se ejecutan las sentencias concurrentes y los bloques process una vez.
- En los bloques *process*:
      - Si el bloque *process* tiene lista de sensibilidad, se ejecuta el código secuencial completo.
      - Si no se ejecutan las instrucciones hasta enconrar una sentencia *wait*.
      - Se añaden las transacciones a la cola del driver, si no se especifica retardo se asume $t=\delta$.

*** Ejemplo con un driver
- [[id:DACircDig][DACircDig]] pag 212.
#+begin_src vhdl
architecture drivers2 of srivers2 is
  signal a : std_logic := 'Z';  -- valor por defecto a='Z'
begin
  bloque1 : process
  begin
    a <= '1';                   -- Se ejecuta el bloque process
                                --  En t=0 se planifica la transacción para t=\delta.
    wait;                       -- Se detiene la ejecución en t=0 del bloque process.
  end process bloque1;
end architecture drivers2;
#+end_src

| tiempo | a   |
|--------+-----|
| 0      | 'Z' |
| \delta | '1' |

- En el ejemplo anterior al avanzar el tiempo de la simulación a $t=\delta$ se asignatia al driver process de a el valor '1'.
      - Y se elimina la transacción de la cola del driver.

*** Ejemplo con dos drivers
- [[id:DACircDig]] pag 213
      - Tablas de evolución de la señal.

** Atributo de las Señales
- *Evento* : Cambio en el valor de la señal, Ocurre cuando se asigna un valor nuevo diferente al anterior.
- *Señal activa* : Cuando el valor de una señal es actualizado, independientemente de si es diferente al anterior.
- *Transacción* : asignar valor a una señal, sea igual o diferente.
- *Señal implícita* : señal que no está declarada en el código VHDL.
      - Se deduce del empleo de los atributos *'stable*, *'quiet*, *'delayed* y *'transaction*.
      - El simulador genera automáticamente una señal implícita.
- Clasificación atributos de las señales:
      - Los que representan una señal implícita.
      - Los que equivalen a una llamanda a una función.
- Atributos [[id:DACircDig]] pag 218:
      - *s'event* : Función booleana, devuelve true cuando se produce un evento en la señal.
      - *s'active* : Función booleana, devuelve true en el instante que se produce una transacción a la señal.
      - *s'transaction* : Señal implícita tipo bit, '0' o '1' cada vez que se produce una transacción a la señal s.
      - *s'delayed(T)* : Crea una señal implícita del mismo tipo que s, cuyo valor es igual a s retrasado T.
            - s'delayed(4 ns) en el instante 10 ns vale s en el instante 6 ns.
      - *s'stable(T)* : Creat una señal implícita tipo booleano, true si no se ha producido un evento en la señal s durante las anteriores T unidades de tiempo.
      - *s'quiet(T)* : Crea una señal implícita tipo booleano, true si no se ha producido ninguna transacción durante las T anteriores unidades de tiempo.
      - *s'last_event* : Función que devuelve un valor del tipo time, Tiempo transcurrido desde el último evento de s.
      - *s'last_active* : Función que devuelve tipo time, tiempo transcurrido desde que se produjo la última transacción a la señal s.
      - *s'last_value* : Función que devuelve un valor del mismo tipo que s, valor previo a la última transacción.

** El retardo Delta
- [[id:DACircDig]] pag 219
      - Hay un ejemplo bastante detallado.
- $\delta$ es una cantidad de tiempo infinitesimal, $\delta > 0$ pero vale 0 cuando se suma a una cantidad de tiempo no infinitesimal.
      - una asignación sin *after* se completa en $t+\delta$.
      - Si el cambio activa una sentencia *wait* (por ejemplo) donde hay una asignación con *after* *10 ns*. La resolución de esta transacción será $t + \delta + 10 = t+10$.
            - $\delta$ al sumarse con un valor no infinitesimal vale 0.

** Gestión de la cola de transacciones del dirver
- Las transacciones encoladas en un driver pueden eliminarse dependiendo del tipo de retardo, *inercial* o de *transporte*.
- Reglas, suponemos que en $t$ se añaden transacciones $(t_1, t_2, \dots)$ a una cola  planificada para insantes futuros:
      1. Se eliminan de la cola (transacciones antiguas) todas las transacciones para intantes $\geq t_1$
      2. Si las nuevas transacciones tienen retardo *inercial*, Se inspeccionan las transacciones que ya se encontraban en la cola. progresando hacia atrás en el tiempo (hacia la cabeza de la cola).
             1. Si la transacción inspeccionada asigna el mismo valor que que la planificada en $t_1$ esta se mantiene en la cola.
             2. Si asigna un valor diferente a la planificada para $t_1$ entonces se elimina de la cola de transacción y todas las planificadas para instantes anteriores a esta..

*** Ejemplo Simulación con retardo inercial
- [[id:DACircDig]] pag 222

* Glosario
- *flip-flop*, circuito biestable.
  # creo que era un Biestable-T (toggle)
- *VHDL*, lenguage para diseñar circuitos
- La notación $a'$ equivale a $\lnot a$.

* Recursos
- https://www.dia.uned.es/71012018/ página web de la asignatura.
- https://ghdl-rad.readthedocs.io/en/stable/using/QuickStartGuide.html, ghdl documentation.

* Notas
- *ModelSim*, software para editar y simular circuitos
- *Emacs + ghdl*, alternativa para simular

* GHDL
** Compile and run
#+begin_src sh
ghdl -a hello.vhd       # analysis, genera hello.o
ghdl -e hello_world     # elaborate
ghdl -r hello_world     # run
#+end_src

* Bibliografía

** Diseño y Análisis de Cicuitos Digitales con VHDL
:PROPERTIES:
:ID: DACircDig
:TYPE: Book
:TITLE: Diseño y Análisis de Cicuitos Digitales con VHDL
:AUTHOR: Alfonso Urquía Moraleda, Carla Martín Villalba
:EDITION: Septiembre 2011
:END:

