#+title: Teoría de los lenguajes de Programación
#+author: Jordi Amposta Pérez
#+LATEX_HEADER: \usepackage{tikz}

#+startup: latexpreview content

* Paradigmas de computación
- Generaciones Lenguajes Programación
      - Primera generación lenguajes máquina.
      - Segunda generación ensambladores (mnemotécnico del lenguaje máquina).
      - Tercera generación lenguajes de alto nivel como C
            - Lenguajes de propósito general.
            - Requieren compiladores o intérpretes.
      - Cuarta generación lenguajes de propósito específico como SQL.
      - Quinta generación, muy relacionada con el área de la Inteligencia Artificial.
            - Se especifica el problema y como se resuelve con una secuencia de acciones.
            - Prolog y Haskel.

** Abstracción en los lenguajes de rogramación
- Abstracción de datos y de control

| *Abstracción*  | *De Datos*                    | *De Control*                        |
|--------------+-----------------------------+-----------------------------------|
| *Básica*       | Tipos atómicos de variables | goto                              |
| *Estructurada* | tipos estructurados         | bucles condicionales subprogramas |
| *Unitaria*     | módulos paquetes            | módulos paquetes                  |

*** Abstracción de Datos
- Abstracciones de datos básicas
      - *Tipos atómicos*, tipos que no pueden dividirse en tipos más sencillos.
      - Nombres de variables son una abstracción.
- Abstracciones de datos estructuradas
      - Arrays
      - En C el typedef int MyTable[7]; Crea un tipo de dato estructurado.
- Abstracciones de datos unitarias
      - Agrupación de datos y operaciones sobre ellos.
      - Encapsulado de datos
      - Clases, Tipos abstractos, interfaces.

*** Abstracción de Control
- Abstracciones de Control básicas
      - Sentencias para modificar el flujo de ejecución.
      - goto
- Abstracciones de control estructuradas.
      - Bucles o sentencias condicionales (if)
      - Permiten anidamiento
      - Subprogramas (funciones, métodos, procedimientos)
- Abstracciones de control tipo unitario
      - Colección de subprogramas en una unidad en si misma independiente del programa.
        
** Introducción a los paradigmas de computación
- Inicialmente los lenguajes se basaron en el *modelo de computación Von Neumann*.
      1. Ejecución secuencial de instrucciones.
      2. Variables representan posiciones de memoria.
      3. Asignación para cambiar el valor de las variables.
- También se conocen como *Lenguajes Impertarivos*, paradigma imperativo.
- paradigmas
      - Imperativo
            - Programación oritendata a objetos.
      - Declarativo
            - Funcional, abstracción de funciones matemáticas.
            - Lógico

*** Programación orientada a objetos
- *Objeto*, conjunto de posiciones en memoria más las operaciones sobre los valores que almacenan dichas posiciones.

*** Programación funcional
- Evaluación de funciones.
      - Transferencia de valores como parámetros de las funciones que se evaluan.
      - Generación de resultados en forma de valores devueltos por las funciones.
- No involucra la asignación de una variable a una posición de memoria.
- Operaciones repetitivas mediante funciones recursivas.
      - Operaciones repetitivas NO se representan mediante ciclos.

#+caption: Ejemplo en Haskell        
#+begin_src haskell
gcd u v
    v == 0 -> u
    otherwise -> gcd v (mod u v)

gcd 18 8
#+end_src

*** Programación lógica
- Conjunto de sentencias que describen lo que es verdad o conocido.
- El control lo aporta el modelo de inferencia lógica.

#+begin_src prolog
gcd(U, 0 , U).
gcd(U, V, X) :- not (V=0),
                Y is U mod V,
                gcd(V, Y, X).
#+end_src

Busca el valor de X que hace cierta la siguiente pregunta.

#+begin_src prolog
?- gcd(18,8,X).
#+end_src

** Descripción de los lenguajes de programación
- Elementos fundamentales
      - *Léxico* o tokens (if, else)
      - *Sintáxis*, Estructura de los diferentes componentes del lenguaje y sus combinaciones.
            - Se pueden describir con el uso de gramaticas libres de contexto.
            - 
              #+caption: Sentencia if de C
              #+begin_example
              <sentencia if> ::= if (<expresion>) <sentencia> [else <sentencia>]
              #+end_example

      - *Semántica*, expresa los efectos de la ejecución en un contexto determinado.
            - Sistemas de notación de la semántica (no hay una forma aceptada).
                  - *Semántica operacional*
                  - *Denotacional*
                  - *Axiomática*

*** Traducción de los programas para su ejecución
- *Intérprete*, Un programa que acepta entradas del lenguaje y los ejecuta.
- *Compilador*, Programa que traduce el languaje a código máquina.
- El traductos (intérprete o compilador) debe seguír fielmente la definición del lenguaje.
- Pasos de un intérprete o compilador.
      - *Analizador léxico*
      - *Analizador sintáctico*
      - *Analizador semántico*
- Tipos de errores
      - *Errores léxicos*, Suele estar kimitado al uso de carácteres ilegibles.
      - *Errores sintácticos*, Tokens que faltan o expresiones malformadas.
      - *Errores semánticos*, Estáticos (uso de tipos incompatibles) o dinámicos (división por 0).
      - *Errores lógicos*, Comportamiento no deseado.

** Diseño de los lenguajes de programación
- Control de la complejidad.
- Legibilidad a la par que facil traducción a lenguaje máquina.

*** La eficiencia
- El diseño debe permitir al traductor la generación de código ejecutable eficiente.
- *Eficiencia de traducción*, El lenguaje debe permitir el desarrollo de un traductor eficiente y de tamaño razonable.
- *Eficiencia de implementación*, Eficiencia con la que puede escribirse un traductor.
- *Eficiencia de la programación*, Rapidez y facilidad para escribir programas.
      - Capacidad expresiva.
      - *Sintactic sugar*, estructuras que facilitan la escritura de un programa.
            - Por ejemplo las diferentes versiones de bucles.

*** La regularidad
- Comportamiento de las características del lenguaje.
- *La Generalidad*, uso y disponibilidad de constructores no están sujetas a casos especiales.
- *La Ortogonalidad*, Los constructores del lenguaje pueden admitir combinaciones significativas, sin restricciones ni comportamientos inesperados.
- *La uniformidad*, Consistencia entre la apariencia y el comportamiento de los constructores.

*** Principios Adicionales
**** Simplicidad
- Que cada concepto del lenguaje se presente de forma única y legible.
- Estructuras con reglas de combinación sencillas.

**** Expresividad
- Facilidad con la que un lenguaje de programación permite expresas procesos y estructuras complejas.

**** Extensibilidad
- Ampliar el lenguaje con nuevas funcionalidades (nuevos tipos, etc).
- *Modularidad*, disponer de bibliotecas.

**** Capacidad de restricción
- El uso suficiente de un subconjunto del lenguaje.

**** Consistencia entre la notación y las convenciones
- Notaciones y características que ya se hayan convertido en estándares.

**** Precisión
- Definición precisa del lenguaje, de forma que los programas sean predecibles.
      - El programa se comporta igual en cualquier máquina.

****  Portabilidad
- La definición del lenguaje de programación es independiente de una máquina en particular.
- Normalmente los lenguajes interpretados son portables.

**** Seguridad
- Este principio pretende evitar los errores de programación y permitir su descubrimiento.
- A veces compromete la expresividad.

**** Interoperabilidad
- La posibilidad de que un código escrito en un lenguaje interactue con el código escrito en otro lenguaje.

* Programación Funcional (Haskell)
- Diferente a la programación imperativa.
      - No tan cercano al hardware.
- *Currificación*, devolver una función desde otra función, aprovechando para reducir el número de parámetros.

**  Programas como funciones
- Un programa funcional contiene funciones definidas por el programador.
      - El programador no se preocupa cómo se realiza el cálculo.
- Las variables no hacen referencia a posiciones en memoria.
- No existe la asignación.
- Sentencias del tipo $x=x+2$ no son válidas.
- Una constante puede ser considerada una función sin parámetro.
- Desaparecen los bucles, en su lugar se hace uso de la *recursión*.
- No existe *estado del cómputo*.
- En programación funcional un programa consiste en la definición matemática de una seria de funciones que toman unos argumentos de entrada y realizan un cómputo sobre ellos.

Ejemplo función factorial en C y en Haskell  

#+begin_src C
int factorial(int n) {
    int f = 1;
    for (int x=1; x <=n; x++) {
        f = f*x;
    }
    return f;
}
#+end_src  

#+begin_src haskell
factorial n
  n <= 0 = 1                       -- definición si n <= 0
  otherwise = n * factorial(n-1)   -- definicinón en otro caso
#+end_src

- Las funciones son ciudadanos de primera clase.
      - Pueden devolverse desde otra función.
      - Pueden pasarse como parámetro.

#+begin_src haskell
suma3 x = x  3
funCuadrado f x = f x * f x

funCuadrado suma3 5
#+end_src

#+RESULTS:

** Evaluación Perezosa
- pag 38
- Se evalua el valor de un parámetro solo cuando se usa.
- función *no estricta*, no necesita conocer el valor de todos sus parámetros para devolver un resultado.
- *memoización*, permite guardar el valor de un parámetro la primera vez que se evaluó.

Ejemplo con listas de haskell.

#+begin_example
[1..]      -- Define una lista de todos los números Naturales desde el 1
1:[2..]    -- Se evalua el primer elemento (lista tipo cabeza cola)
1:2:[3..]
#+end_example

- Permite programar funciones *productoras* y funciones *consumidoras*.

#+begin_src haskell
-- los valores se irán calculando a medida que se acceden
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
#+end_src  

** Introducción a Haskell
- Case sensitive
  
*** Tipos de datos
- Los tipos se escriben en PascalCase
- *Tipos atómicos*
      - *Int*, enteros ligados a la arquitectura del ordenador (acotados).
      - *Integer*, conjunto de números enteros sin ningún límite.
      - *Float*, reales de precisión simple.
      - *Double*, reales de precisión doble.
      - *Char*, carácteres ACII-7.
      - *Bool*, booleanos, True o False.
- *Tipos estructurados*
      - *Tupla*,secuencia finita de valores, pueden tener tipos diferentes.
            - `(4,"vacio", False)`
      - *Lista*, una colección no necesariamente finita de valores del mismo tipo
            - Las cadenas de carácteres son listas de [Char].
            - Son estructuras recursivas cabeza:cola:..:[].
            - *Listas definidas por extensión*
                  - [1,2,3]
                  - [1,3..10]
                  - [1,3..]
            - *Listas definidas por comprensión*
                  - [p | p <- [1..], mod p 2 /=0 ]

*** Definición de Funciones
- Dos formas de definirse
      - *Identificador* una palabra que empiezan siempre en *minúscula*.
            - Puede contener ' _ entre otros símbolos.
            - Se usan de forma *prefija*
            - Se puede usar de forma *infija* usando `
                  - 3 `suma` 4
      - *Operadores*, secuencia de uno más de los siguientes carárcters
            - : ! # $ % * + . / < + > ? @ \ ^ | -
            - Las siguientes combinaciones tienen un uso especial.
                  - :: = .. @ \ | <- -> ~ =>
            - Se utilizan de forma *infija* (exactamente 2 parámetros de entrada).
            - Se pueden usar de forma *prefija* con el uso de ().
                  - (+) 3 4
- *precedencia* y *asociatividad*
      - Se asigna un valor de *precedencia* a cada función (más alto mejor).
      - funciones definidas con *identificador* tiene más precedencia que las definidas por *operador*.
            - f x + 1 sería (f x) + 1

Definir reglas de precendencia y asociatividad.

#+begin_src haskell
asociatividad precedencia lista_de_operadores
-- asociatividad: infixr (derecha), infixl (izquierda), infix (no asocian)
-- precedencia: entre 0 y 9
-- lista_de_operadores: símbolos de operador separados por ,

-- ejemplo de suma y resta

infixl 6 +,-      -- e.g 3 - 5 - 2 = (3 - 5) - 2
#+end_src              

**** Definición ecuacional y encaje de patrones
#+begin_example
identificador <patron1> <patron2> ... <patronN> = <expresión>
#+end_example

- *patron*, Como argumentos de entrada de cada función.
      - Más versatil que un simple argumento.
- Una función puede definirse con más de una ecuación.

***** Patrones Constantes
#+begin_src haskell
f 1 = True
f 2 = False
#+end_src

Cualquier otro valor de entrada generaría un error.

***** Patrones Variables
#+begin_src haskell
suma x y = x + y
#+end_src

***** Patrones anónimos
Se representan con _, no pueden ser referenciados.

#+begin_src haskell
siempre2 _ = 2
#+end_src

***** Patrones para listas
- [], lísta vacía (patrón constante).
- [x], lista con un único elemento referenciado como x.
- (x:xs), lista con un elemento de cabeza x y una cola xs.

#+begin_src haskell
suma [] = 0
suma (x:xs) = x + suma xs
#+end_src

***** Patrones para tuplas
Se referencian entre paréntesis, eg. (x,y,z).

***** Patrones con nombre
#+begin_src haskell
duplicaCabeza l@(x:xs) = x:l
#+end_src

***** Patron aritmético
La siguiente definición substrae 3 del valor de entrada. Están deprecados.
#+begin_src haskell
f (n + 3) = n
#+end_src

**** Expresiones case
#+begin_src haskell
case expresion of
  patron1 -> resultado1
  patron2 -> resultado2
  -- ...
  patronN -> resultadoN
#+end_src

**** Funciones definidas a trozos
#+begin_example
identificador <lista_de_patrones>
  | guarda1 = expresion1
  -- ...
  | guardaN = expresionN
#+end_example

- Las guardas son expresiones tipo *Bool*.
- Se devuelve el valor de la primera guarda con valor *True*.

#+begin_src haskell
abs x
  | x >= 0 = x
  | x < 0  = -x
#+end_src

Usando *otherwise*, si no se cumple ninguna guarda.

#+begin_src haskell
abs x
  | x >= 0 = x
  | otherwise = -x
#+end_src

**** Definiciones locales
#+begin_example
definición_de_la_funcion
  where
    subfuncion1
    ...
    subfuncionN
#+end_example

#+begin_src haskell
f x y = (a+1) * (c-1)
  where
    a = div (x+y) 2
    c = mod (x+y) 2
#+end_src

- Permite usar patrones en cualquier punto de una expresión.

#+begin_example
let definición in expresión
#+end_example

Por ejemplo

#+begin_src haskell
let a x = x + 1 in a 100
#+end_src

**** Funciones anónimas
- Expresiones lambda

#+begin_src haskell
esPar x = mod x 2 == 0
#+end_src

En expresión anónima sería.

#+begin_src haskell
(\x -> mod x 2 == 0) 4
#+end_src

**** La función error
- Detiene la ejecución y muestra un mensaje informativo

#+begin_src haskell
divide a 0 = error "No se puede dividir por 0"
divide a b = a / b  
#+end_src

*** El tipo de las funciones
#+begin_example
identificador :: expresionDeTipo
#+end_example

- Muy similar a la notación matemática $f: \mathbb{R} \to \mathbb{R}$

#+begin_src haskell
doble :: Float -> Float

doble x = 2*x
#+end_src  

**** Polimorfismo
- Funciones con una definición para varios tipos de datos.

**** Currificación de funciones y aplicación parcial
#+begin_src haskell
suma :: Float -> Float -> Float
suma x y = x + y  
#+end_src

El operador -> asocia a la derecha, por tanto.

#+begin_example
suma :: Float -> Float -> Float
-- realmente se aplica la currificación
suma :: Float -> (Float -> Float)
#+end_example  

- Función definida por *aplicación parcial*.

#+begin_src haskell
suma3 :: Float -> Float
suma3 = suma 3  
#+end_src

**** Funciones de orden superior
- Funciones que reciben como parámetro de entrada otras funciones.

#+begin_src haskell
aplica f x y = f x y
#+end_src  

*** Tipos de datos avanzados
**** El valor indefenido: Bottom
- /undefined/ representa un valor indefenido de cualquier tipo.

**** Sinónimos de tipos: type
- Definición de un nuevo nombre para un tipo que ya existe.

#+begin_src haskell
type Caracter = Char
type String = [Caracter]
#+end_src

#+begin_src haskell
type Complex = [Double, Double]
a :: Complex
a = (3.4, 2.5)
#+end_src

**** Definición de nuevos tipos de datos: data
***** Tipos enumerados
Deben empezar con mayúscula.

#+begin_src haskell
data Semaforo = Rojo | Amarillo | Verde
  deriving (Eq,Ord,Show,Read)   -- Deriva de estas clases
#+end_src

- Clases más usadas como deriving.
      - *Eq* : permite comparar elementos.
      - *Ord* : establece una relación de orden entre los elementos.
      - *Show* : permite que el intérprete pueda mostrar un valor de este tipo.
      - *Read* : permite convertir cadenas de texto en elementos del tipo.
            - read "Rojo"::Semaforo , crea el elemento rojo del tipo Semáforo.

***** Unión de tipos
:PROPERTIES:
:ID:       a8e2199b-13a0-421a-9c31-cdd5cac0feff
:END:

Permite agrupar en un único tipo elementos de dos tipos diferentes.

#+begin_src haskell
data BooleanoEntero = Booleano Bool | Entero Integer

listaMixta :: [BooleanoEntero]
listaMixta = [Entero 0, Booleano True, Booleano False, Entero -1]  
#+end_src

***** Producto Cartesiano

#+begin_src haskell
data Asignatura = Asig String Integer String
#+end_src

Más similar a un tipo registro.

#+begin_src haskell
data Asignatura = Asig { nombre :: String, curso :: Integer, web :: String }
#+end_src

Definición de una función constante.

#+begin_src haskell
tlp = Asig { nombre = "Nombre", curso=2, web="una web" }
#+end_src

Y para acceder a uno de los atributos podemos hacer.

#+begin_src haskell
esDePrimero x = curso x == 1
#+end_src

***** Tipo de datos recursivos

#+begin_src haskell
data Natural = Cero | Sucesor Natural
#+end_src

Parece similar a una [[id:a8e2199b-13a0-421a-9c31-cdd5cac0feff][Unión de tipos]].

Luego puede escribirse.

#+begin_src haskell
uno = Sucesor Cero
dos = Sucesor uno
tres = Sucesor dos
#+end_src

Función mayor que.

#+begin_src haskell
mayor (Sucesor _) Cero = True              -- Aquí (Sucesor _) acepta un elemento
                                           --  con una capa de (Sucesor )
mayor Cero _ = False
mayor (Sucesor x) (Sucesor y) = mayor x y  -- Los patrones de entrada eliminan
                                           --  una capa de (sucesor )
#+end_src

***** Tipos polimórficos
- Puede contener valores de cualquier tipo.
      - Como una lista genérica por ejemplo.

#+begin_src haskell
data TipoMixto a b = Tipo a | Tipo b
type BooleanoEntero = TipoMixto Bool Integer
#+end_src        

*** Ejemplos de funciones: trabajando con listas
**** Contar elementos de una lista
#+begin_src haskell
length [] = 0
length (x:xs) = 1 + length xs
#+end_src

**** Concatenar listas
- Listas del mismo tipo

#+begin_src haskell
[] ++ ys = ys
(x:xs) ++ ys = x : (xs ++ ys)
#+end_src  

- Aplanar una lista de listas

#+begin_src haskell
concat [] = []
concat (xs:yss) = xs ++ (concat yss)
#+end_src

**** Combinar listas
- Operación zip.

#+begin_src haskell
zip (x:xs) (y:ys) = (x,y):(zip xs ys)  -- El orden afecta a la evaluación
                                       --  la definición que aparece antes
                                       --  será seleccionada antes si se puede.
zip _ _ = []  
#+end_src

- Operación unzip.

#+begin_src haskell
unzip xs = unzipAux xs ([],[])
  where
    unzipAux [] acumulador = acumulador
    unzipAux ((a,b):xs) (as,bs) = unzipAux xs (as ++ [a], bs ++ [b])
#+end_src

**** Aplicar una función a los elementos de una lista
- función *map*.

#+begin_src haskell
map _ [] = []
map f (x:xs) = (f x) : (map f xs)
#+end_src

- Ejemplo de uso para calcular x*x de cada elemento de una lista.

#+begin_src haskell
map (\x -> x*x) [1..10]
#+end_src

- *zipWith*, como map pero con dos listas

#+begin_src haskell
-- El orden de declaración es importante
zipWith f (a:as) (b:bs) = (f a b) : (zipWith f as bs)
zipWith _ _ _ = []  
#+end_src  

- *iterate*, para crear listas infinitas

#+begin_src haskell
iterate f x = x : (iterate f (f x))  -- En este caso la memoización de haskell
                                     --  permite que sea eficiente

potencias2 = iterate (2*) 1
#+end_src  

**** Filtros sobre listas
- *take* y *drop*

#+begin_src haskell
take _ [] = []
take n (x:xs)
  | n <= 0 = []
  | otherwise = x : take (n-1) xs
#+end_src

#+begin_src haskell
drop _ [] = []
drop n (x:xs)
  | n <= 0 = (x:xs)
  | otherwise = drop (n-1) xs
#+end_src

- *filter*

#+begin_src haskell
filter _ [] = []
filter p (x:sx)
  | p x = x : (filter p xs)
  | otherwise = filter p xs
#+end_src  

- *takeWhile* y *dropWhile*

#+begin_src haskell
takeWhile _ [] = []
takeWhile p (x:xs)
  | p x = x : takeWhile p xs
  | otherwise = []
#+end_src

#+begin_src haskell
dropWhile _ [] = []
dropWhile p ys@(x:xs)  -- @ patrones con nombre
  | p x = dropWhile p xs
  | otherwise = ys
#+end_src

**** Listas por comprensión
#+begin_example
[ expresión | cualificador1, ... , cualificadorn ]
#+end_example

- Donde
      - *expresión*, define la forma de los elementos de la lista resultado.
      - *cualificadores*, definen propiedades de los elementos.
            - *generadores*, expresiones que permiten generar una lista.
            - *filtros*, expresiones booleanas para filtrar elementos.
            - *definiciones locales*, define elementos locales dentro de la definición de la lista.
                  - Se usa la palabra reservada *let*.

#+caption: Lista números impares                    
#+begin_src haskell
[p | p <- [2..], mod p 2 /= 0 ]  -- números impares, /= not equal
#+end_src                    

- Ejemplo de lista con números primos.
  
#+begin_src haskell
divisores n = [ d | d <- [1..n] , mod n d == 0 ]
primos  = [ p | p <- [2..] , divisores p == [1,p]]
#+end_src

**** Plegado de listas
- *foldr*  (right) y *foldl* (left)

#+begin_src haskell
-- z es el caso base
foldr f z [] = z
foldr f z (x:xs) = f x (foldr f z xs)
-- z es el caso base
foldl f z [] = z
foldl f z (x:xs) = foldl f (f z x) xs
#+end_src

#+begin_src haskell
suma = foldr (+) 0
concat = foldr (++) []
#+end_src

* Programación lógica (ProLog)
- [id:TeLenProg] pag 85
- Se usa *ProLog*
      - El Programador se orienta en describir el problema.
      - Los programas y datos se presentan bediante *cláusulas* definidas.
      - *Unificación* : equiparación incluida en el sistema (operaciones de sustitución lógica).
      - Incluye un mecanismo de inferencia automática basado en vualta atrás y búsqueda en profundidad.
      - Permite un estilo no determinista de programación.
      - Soporta la recursión y maneja estucturas de datos (lista).

** Especificación de programas
- Básado en el cálculo de predicados de la lógica clásica.
      - Símbolos lógicos : conectivasy cuantificadores.
      - Símbolos no lógicos : Datos.
- Elementos de formulación de problemas
      - *átomos* : representan propiedades o relaciones entre objetos.
            - También conocido como *literales afirmados*.
            - Símbolo no lógico de *predicado*.
                  - Un símbolo 0-ario representa un hecho simple, por ejemplo llueve.
      - *predicados* : Representan relaciones o propiedades que permiten clasificar y discriminar los diferentes tipos de objetos del problema.
            - entrante(X) : Se usa para luego establecer el atributo entrante.
      - *cláusulas* : Combinación de relaciones entre objetos y sus propiedades mediante símbolos lógicos que da lugar a fórmulas.
            - <cabeza> :- <cuerpo>
      - *Marco conceptual* : Descripción de los símbolos no lógicos necesarios para formular el problema.
      - *términos* : Los elementos que parecen en la formulación de un problema.
            - *Variables* :
            - *Constantes* : Objetos concretos y bien conocidos del dominio.
                  - camelCase, se pueden entrecomillar para contener espacios.
            - Símbolo de función con argumentos que son términos.

- Ejemplo de Prolog

#+begin_src prolog
% constantes
paella, gazpacho, potaje  % camelCase, constantes
#+end_src

#+begin_src prolog
entrante(X)               % sneaky_case y la variable en Mayus
plato_de_pescado(X)       % X es un plato de pescado
#+end_src

*** Reglas y programas
- No se utilizan tipos.
- *programa* : Secuencia de hechos y reglas que describen los conocimientos relativos a un problema.
- *reglas* : símbolos lógicos que permiten combinaciones de literales.
      - También se conocen como *Cáusulas de Horn*.
      - También se denomina *cláusulas definidas*.
      - formadas por *cabeza* y *cuerpo* separadas por el símbolo *:-* y acabado en punto.

#+begin_src prolog
Q :- P1, P2, ... , Pn.
#+end_src

- Se lee : si es cierto P1, P2, ..., Pn entonces es cierto Q.

- Reglas como "atributo".
  
#+begin_src prolog
% La carta
entrante(paella).   % la paella es un entrante
entrante(gazpacho).
plato_de_carne(filete).
postre(naranja).
#+end_src

- Reglas de relación de atributos.
      - /Para todo X si X es un plato de carne entonces X es un plato fuerte./
#+begin_src prolog
plato_fuerte(X) :- plato_de_carne(X)
plato_fuerte(X) :- plato_de_pescado(X)
#+end_src  

- , es la conectiva $\land$
      - /Cualquier tipo de valores X,Y,Z tal que X es entrante, Y es plato fuerte y Z es postre/, se escribe en prolog como:

#+begin_src prolog
menu(X,Y,Z) :- entrante(X), plato_fuerte(Y), postre(Z)
#+end_src

- ; es la conectiva $\lor$
      - $q \lor r \to p$, se escribe en prolog como:

#+begin_src prolog
p :- q ; r
#+end_src

#+begin_src prolog
meny(X,Y,Z) :- entrante(X),
               (plato_de_carne(Y); plato_de_pescado(Y),
               postre(Z)).
#+end_src

- , es prioritario sobre ;
      - $(q \land r) \lor s \to p$

#+begin_src prolog
p :- q , r ; s
#+end_src

*** Extracción de respuestas
- *Consulta* : extracción de respuestas de un programa.
- Las consultas empiezan con el símbolos ?-
- *Instancia de la regla* : Es el resultado de sustituir una variable X por un término cualquiera t.
      - La sustitución se denota por <X,t>

- $\exists X, mujer(X) \land ama(manuel,X)$, se escribe como:
  
#+begin_src prolog
% Existe alguna mujer a la que manuel ame?
?- mujer(X), ama(manuel, X).
#+end_src

- /Cuales son los menús contenidos en la carta?/, se escribe como:

#+begin_src prolog
?- menu(X,Y,Z).
#+end_src

- Para confirmar una relación se hace:

#+begin_src prolog
?- menu(paella, filete, naranja).
#+end_src  

- Consultas con algunas restricciones.

#+begin_src prolog
?- menu(paella, X, naranja).
#+end_src  

*** Guía metodológica para la especificación
**** 1 Descripción del Marco conceptual
- pag 97
- Descripción de los elementos u objetos del Dominio.
- Descripción de las pripiedades de los objetos.
- Descripción de las posibles relaciones entre los objetos.

**** 2 Formulación
- Afirmaciones
- Fórmulas que representan la interacción entre literales.

- Programación recursiva
#+begin_src prolog
antepasado(X,Y) :- hijo-ja(Y,X).  % Si Y es hijo-ja de X
                                  %  X es un antepasado de Y
antepasado(X,Y) :- hijo-ja(Y,Z), antepasado(X,Z).
#+end_src  

- Formulación aritmética
      - Se expresa mediante *is* con notación infija.
      - La aritmética en prolog también se entiende en forma predictiva.
      - Z is 4 + 7, asigna 7 a la variable Z

#+begin_src prolog
factorial(0,1).        % factorial de 0 es 1
factorial(N,M) :- I is N-1, factorial(I,A), M is N*A.
#+end_src

- La consulta se escribe como:

#+begin_src prolog
?- factorial(3,X)     % Cual es el factorial de 3?
#+end_src  

** Computación lógica
- [id:TeLenProg] pag 101
- Proceso que resuelve la consulta.
  
*** Unificación
**** Unificación Simple
- Dos objetivos se unifican si existe un unificador formado por pares de <Variable, término>.
      1. Dos literales u objetivos se unifican si tienen igual símbolo de predicado, igual número de argumentos y éstos son unificables uno a uno.
      2. Una variable se unifica con cualquier otro término pasando a tomar ese valor.
      3. Una constante solo se unifica con otra constante idéntica sintácticamente.
      4. Dos términos compuestos se unifican si tienen igual símbolo de función, igual número de argumentos y éstos son unificables.

**** Unificación General
- [id:TeLenProg] pag 103
- *Entrada* : A,B literales a unificar.
- *Algoritmo* :
#+begin_src pseudocode
Sea S<-{} la sustitución vacía
mientras S(A) no sea S(B) hacer
    Determinar símbolo más a la izquierda de S(A) que sea
      distinto del símbolo en igual posición en S(B).
    Calcular a partir de los símbolos anteriores, los términos
      o fórmulas u_1 y u_2 mínimos que comienzan por ellos.
      
    si ni u_1 ni u_2 son variables o uno es un variable contenida en el otro entonces
      dev "acabar, pues A y B no son unificables"
    sino
       Determinar una variable x en u_1 (o en u_2) y el subtérmino
         b en la misma posición en u_2 (resp. en u_1) y hacer S = S union (<x,b>).
    fsi
fmientras
#+end_src  
- *Salida :* S es el *unificador de máxima generalidad* (umg) de los literales A y B.

- Una regla o cláusula permite deducir un objetivo si existe una unificación (umg) que.
      - identifique este objetivo con la conclusión de la regla
      - o si existe una instancia de la regla del programa que infiere exactamente al objetivo.
        
*** Resolución
- [id:TeLenProg] pag 105
- Algoritmo de resolución controlada.
- *Inicio* : La lista de objetivos es la que forma la consulta.
- *Selección* ...
      1. ... de un objetivo a resolver: el primero más a la izquierda.
      2. ... de una regla o cláusula para resolver el objetivo seleccionado:
         La primera cuya conclusión o parte de la izquierda se unifica con el objetivo.
- Una vez realizada la selección
      - El modelo de computación recuerda todas las reglas que podrían haber sido seleccionadas en este momento.
      - El objetivo es reemplazado en la lista de objetivos por la parte derecha de la regla seleccionada.
      - Se aplica a la lista de objetivos resultante el unificador que hace posible unificar el objetivo resuelto con la parte izquierda de la regla.
- *Repetición* : Se continua el proceso de selección hasta que se cumple uno :
      - Se vacía la lista de objetivos (EXITO), Se devuelve el unificador como respuesta.
      - No puede ser resuelto un objetivo (FRACASO LÓGICO).
- Durante la resolución se selecciona el primer objetivo más a la izquierda y la primera cláusula que aparece en el programa.

*** Control de la ejecución
# TODO: repasar y dibujar los espacios de búsqueda.
**** Corte
- [id:TeLenProg] pag 112
- En Prolog el control de la ejecución es interno y no modificable.
- Existen algunos mecanismos no lógicos que permiten la variación de la forma de ejecución.
- *corte* : ! : permite reducir el espacio de búsqueda de un objetivo.
      - Elimina todas las opciones de la rama en que se encuentra a partir del nodo anterior al de su aparición (Solo se sigue una de las ramas).
      - Parecido a una excepción.
      - Depende de si se llega a ejecutar el corte durante la resolución, por tanto depende de la situación del token corte.
            - !,q (siempre corta) es diferente a q,!

#+begin_src prolog
% las reglas se resuelven en orden
p :- q,t.
p :- m,!.                      % ! indica el corte
p :- r.
q :- s,!.
s.
s :- m.
t.
r.
#+end_src

- Puede introducir errores colaterales, se recomienda su uso cuando se sepa que la solución es única.

#+begin_src prolog
%% Juan no tiene hermanos, pedro tiene 1 hermanos, cualquier otro tiene 2 hermanos.
numero_de_hermanos(juan,0) :- !.
numero_de_hermanos(pedro,1) :- !.
numero_de_hermanos(X,2) :- dif(X,juan), dif(X,pedro).
#+end_src

- Con el *corte* podemos escribir la negación por defecto.
      - *call(x)* : permite parametrizar la resolución Prolog del objetivo X.
      - *fallo* nunca se definiría en el programa.

#+begin_src prolog
no(X) :- call(X), !, fallo.
no(X).
#+end_src  

- *Corte rojo* : Corte que modifica el significado del programa.
      - Quita soluciones.
      - No tiene porque ser malo, a veces solo se quiere una solución.
- *Corte verde* : Corte que no modifica el significado del programa.

*** Estructura de datos: la lista
# TODO: repasar y dibujar los espacios de búsqueda.
- [[id:TeLenProg]] pag 119
- [] :lísta vacía.
- [1,2,3] : lista con 3 elementso.
- son del tipo [cabeza|cola]
- dos listas son unificables si son unificables sus cabezas y sus colas son unificables.

** Técnicas avanzadas de programación lógica
*** Indeterminismo
- [[id:TeLenProg]] pag 126
- Reglas mal planteadas pueden llevar a espacios de búsqueda infinitos.
- El orden de la declaración de las reglas afecta al funcinamiento del programa.
- Los cortes pueden modificar el significado del programa.

*** Eficiencia con la estructuras de datos
- [[id:TeLenProg]] pag 120
- Se ven funciones como argumentos de objetivos.
      - Representan un objeto o elemento.
- Problema del brazo robot y los bloques.

#+begin_src prolog
%% en(X,Y) X está sobre Y
%% libre(X) X no tiene nada encima
%% resultado(llevar(X,Y,Z),E) denota el resultado resultande de llevar X de Y a Z en el estado E

%% Condiciones en el estado 0 o inicial
cierto(en(bloque_A,bloque_B),0).
cierto(en(bloque_B,pos1),0).
cierto(en(bloque_C,pos3),0).
cierto(libre(pos2),0).
cierto(libre(bloque_A),0).
cierto(libre(bloque_C),0).

%% Condiciones para cambiar bloques de sitio
cierto(en(X,Z), resultado(llevar(X,Y,Z),W)).
cierto(libre(Y),resultado(llevar(X,Y,Z),W)).

%% Condición de invarianza
cierto(U, resultado(llevar(XY,Z),W)) :- cierto(U,W),
                                        dif(U,en(X,Y)),
                                        dif(U,libre(Z)).
posible(0).
posible(resultado(llevar(X,Y,Z), W)) :- posible(W),
                                        manipulable(X),
                                        dif(X,Y),
                                        cierto(libre(X),W),
                                        cierto(libre(Z),W),
                                        cierto(en(X,Y),W).
manipulable(bloque_A).
manipulable(bloque_B).
manipulable(bloque_C).
#+end_src

- la consulta es la descripción del estado final deseado, ha de ser posible alcanzar el estado inicial.

#+begin_src prolog
?- cierto(en(bloque_A,bloque_B),W),
   cierto(en(bloque_B,bloque_C),W),
   cierto(en(bloque_C,pos3),W),
   posible(W).
#+end_src

*** Gestión dinámica
- [[id:TeLenProg]] pag 135
- *lemas* : Permite guardar resultados intermedios para accelerar las búsquedas posteriores.

#+begin_src prolog
fib(X,Y):- lfib(X,Y),!.
fib(X,Y):- A is X-1, fib(A,M), B is X-2, fib(B,N),
           Y is M+N, assert(lfib(X,Y)).
initfib :- assert(lfib(0,1)), assert(lfib(l,1)).
#+end_src

*** Uso eficiente de la recursión
- [[id:TeLenProg]] pag 137
- Las técnicas recursivas son el pilar de la programación lógica.
- Aún así conviene retrasar lo máxima su resolución para no explorar caminos innecesarios.

*** Meta-programación
- [[id:TeLenProg]] pag 138
- En prolog se describe el programa y el meta-programa con reglas prolog.

* Sintaxis y Semántica Básica
** Sintaxis de los lenguajes de Programación
- Se describe con gramáticas libre de contexto en notación BNF.

*** Estructura léxica de los lenguajes de Programación
- *Análisis léxico* : Se encarga de identificar secuencias de *tokens*.
- *Análisis sintáctico* : Forma las estructuras sintácticas de un programa.
      - Combinaciones correctas de *tokens*.
- Tipos de Tokens:
      - *palabras reservadas* y *palabras clave*:
            - Las palabras reservadas no pueden redefinirse como identificadores.
            - Palabras clave tienen un significado especial en el lenguaje y forman parte de su sintaxis.
      - *literales* : números o una cadena de letras (variable1, 33, etc).
      - *símbolos* : ";" "+" y otros símbolos especiales.
      - *identificadores* : Cadenas definidas por el programador que no pueden ser palabras reservadas.
            - Su Longitud puede estar prefinida en algunos lenguajes.
            - *subcadena de mayor longitud* : Otra forma es que exista un símbolo de delimitador de nuevo *token* como un espacio en blanco.
- La forma habitual de identificar los tokens es mediante *expresiones regulares*

**** Formalización de las expresiones regulares
- El objetivo es representar a los lenguajes sobre un *alfabeto* $\Sigma$ basándose en lenguajes primitivos y operaciones de composición.
- Dado un alfabeto $\Sigma$.
      - Expresiones regulares primitivas:
            - $\emptyset$ : lenguaje vacío.
            - $\lambda$   : palabra vacía.
            - $a$, $a \in \Sigma$
      - Sean $\alpha$ y $\beta$ dos expresiones regulares, son expresiones regulares derivadas:
            - $\alpha + \beta$ : unión (como un or)
            - $\alpha \cdot \beta$ o $\alpha \beta$ : concatenación
            - $\alpha^*$ : cierre (cualquier cantidad), clausula de Kleene.
            - $(\alpha)$ : expresión regular entre paréntesis (agrupaciones)
- Precedencia de operadores:
      1. ()
      2. $*$
      3. $\cdot$
      4. $+$
- Sea *exp* una expresion regular sobre $\Sigma$.
      - $L(exp)$ es el lenguaje descrito por *exp*.
- Definidión recursiva de $L(exp)$:
      - Si exp = $\emptyset$ entonces $L(\emptyset) := \emptyset$
      - Si exp = $\lambda$ entonces $L(\lambda) := \{\lambda\}$
      - Si exp = $a$, con $a \in \Sigma$ entonces $L(a) := \{a\}$
      - Si exp = $\alpha + \beta$ entonces $L(\alpha  + \beta) := L(\alpha) \cup L(\beta)$
            - $\alpha$ y $\beta$ son expresiones regulares sobre $\Sigma$.
      - Si exp = $\alpha \cdot \beta$ entonces $L(\alpha \cdot \beta) := L(\aplha)L(\beta)$
      - Si exp = $\alpha^*$ entonces $L(\alpha^*) := L(\alpha)^*$
      - Si exp = $(\alpha)$ entonces $L((\alpha)) := L(\alpha)$
- Equivalencias en expresiones regulares (Dos expresiones regulares diferentes pueden definir el mismo lenguaje):
      1. $\alpha + (\beta + \gamma) = (\alpha + \beta) + \gamma$
      2. $\alpha \centerdot (\beta \centerdot \gamma) = (\alpha \centerdot \beta) \centerdot \gamma$
      3. $\alpha + \beta$ = \beta + \gamma$
      4. $\alpha \centerdot (\beta + \gamma) = \alpha \centerdot \beta + \alpha \centerdot \gamma$
      5. $(\alpha + \beta) \centerdot \gamma = \alpha \centerdot \gamma + \beta \centerdot \gamma$
      6. $\alpha \centerdot \lambda = \alpha$ y $\alpha + \emptyset = \alpha$
      7. $\alpha \centerdot \emptyset = \emptyset$
      8. Si $\lambda \in L(\alpha)$ entonces $\alpha + \lambda = \alpha$
      9. $\alpha^* = \lambda + \alpha \centerdot \alpha^*$
      10. $\lambda^* = \lambda$
      11. $\emptyset^* = \lambda$
      12. $\alpha^*\alpha^*=\alpha^*$
      13. $\alpha\alpha^*=\alpha^*\alpha$
      14. $(\alpha^*)^* = \alpha^*$
      15. $(\alpha^* + \beta^*)^* = (\alpha^*\beta^*)^* = (\alpha+\beta)^* = (\alpha^*\beta)^*\alpha^*$
      16. $(\alpha\beta)^*\alpha = \alpha(\beta\alpha)^*$
- Las expresiones regulares pueden representar *lenguajes regulares*.

**** Las expresiones regulares en la programación
- Patrones que permiten encontrar combinaciones de carácteres dentro de cadenas de texto.
- [[id:TeLenProg]] pag 166 tabla con símbolos de expresiones regulares (regex).

*** Gramáticas libres de contexto
- Formada por:
      - *V_NT* : símbolos no terminales.
      - *VY* : símbolos terminales o tokens.
      - *S* : *Símbolo Inicial* no terminal.
      - Un conjunto de *reglas*.
            - <símbolo no termibal> -> <símbolos terminales y no terminales>
            - | : puede agrupar reglas A -> C|B es igual a A->C A->B
- *Derivación* : Secuencia que empieza desde el *Símbolo inicial* y en la que cada paso se sustituye un símbolo no terminal por la parte derecha de una regla.
- *Derivación de una cadena* : todos los símbolos de la cadena en curso son terminales.
- $\Rightarrow$ : Se usa para indicar el paso de una derivación.
- Puede hacerse la derivación *marcha atras*.
      - Se dice que la cadena es *reconocida por la gramatica*.
      - Desde una cadena de *símbolos terminales* hasta el *símbolo inicial*.

*** Notación BNF
:PROPERTIES:
:ID: ec41e456-bcc4-497e-b93c-8cb549c25a31
:END:
- Permite definir las reglas sintácticas de las estructuras de un lenguaje de programación.
      - Se definen con el uso de *símbolos* y *metasímbolos*.
- *Metasímbolos*:
      - ::= separación entre la parte de la izquierda y derecha de una regla.
      - |   Alternativa (Se puede elegir uno de los elementos).
- *Símbolos*:
      - *terminales* y *no terminales*
            - Se diferencian por el estilo de letra.
            - los terminales se escriben entre "<>", por ejemplo <no_terminal>

- El siguiente ejemplo representa las reglas de los número enteros:
#+begin_example
<valor_entero> ::= <secuencia_dígitos> | - <secuencia_dígitos>
<secuencia_dígitos> ::= <dígito> | <dígito> <secuencia_dígitos>
<dígito> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 
#+end_example

*** Estructura sintáctica : árboles sintácticos
- *Semántica dirigida por sintaxis* : A cada estructura sintáctica se le puede asociar una semántica o significado.
      - Es necesario disponer de una representación de cada estructura sintáctica derivada por una gramática.
      - Y una forma de asociación de su semántica.
- *árbol sintáctico* : estándar de estructura sintáctica.
      - Se genera durante el *análisis sintáctico*
            - Representa el resultado de una derivación.
            - Hojas son los *símbolos terminales*.
            - Nodos interiores son los *símbolos no terminales*.

\begin{tikzpicture}[level distance=10mm,level/.style={sibling distance=20mm/#1}]
\node [PL] {F(R1)}
    child
    {
        node [PL] {GN(R3)} 
        child
        {
            node [PL] {NPROP(R10)} 
            child
            {
                node [PL] {Aránzazu}
            }
        }
     }
     child
     {
         node [PL] {GV(R4)}
         child {
             node [PL] {es}
         }
         child {
             node [PL] {ATR(R5)}
             child {
                 node [PL] {ADJ(R12)}
                 child {
                     node [PL] {buena}
                 } 
              }
         }
     };
\end{tikzpicture}    

- notación BNF que abstrae 1 + 2 * 3
      - Tiene implícito el orden de los operadores.

#+begin_example
<expresión> ::= <término> | <término> <op_aditivo> <expresión>
<término> ::= <factor> | <factor> <op_multiplicativo> <término>
<factor> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<op_aditivo> ::= + | -
<op_multiplicativo> ::= * | /
#+end_example

\begin{tikzpicture}[
  level distance=15mm,
  every node/.style={draw, rectangle, rounded corners, align=center},
  level 1/.style={sibling distance=45mm},
  level 2/.style={sibling distance=30mm},
  level 3/.style={sibling distance=25mm}
]
\node {expresion}
    child { node {termino} 
        child { node {factor} child { node {1} } }
    }
    child { node {op\_aditivo} child { node {+} }
    }
    child { node {expresion} 
        child { node {termino} 
            child { node {factor} child { node {2} } }
            child { node {op\_multiplicativo} child { node {*} } }
            child { node {termino} child { node {factor} child { node {3} } } }
        }
    };
\end{tikzpicture}

*** Ambigüedad, sociatividad y precedencia
- [[id:TeLenProg]] pag 173
- *Ambigüedad* : Dos derivaciones diferentes llevan a árboles sintácticos diferentes para una misma palabra.
      - Se pueden establecer *reglas* para el orden de las derivaciones.
      - *derivación por la izquierda* : se derivan primero los símbolos más a la izquierda.
            - Se consideraría ambigüa si aún así encontramos más de 1 derivación para una misma cadena.
- *Criterio para eliminar ambigüedades*:
      - Aportar reglas de derivación (derivación por la izquierda).
      - Además de las reglas se puede ajustar la gramática para eliminar las ambigüedades.

*** Diagramas sintácticos
- *EBNF* es una ampliación de la [[id:ec41e456-bcc4-497e-b93c-8cb549c25a31][Notación BNF]].
      - Se añaden más metasímbolos.
      - No añade expresividad.
- Metasímbolos *EBNF*
      - ::= Separación entre parte izquierda y parte derecha.
      - |   Alternativa
      - {}  Los elementos que se incluyen se pueden repetir 0 o más veces.
      - []  opción (pueden usarse o no)
      - ()  Agrupación
- No permite la recursión.
- *diagrama sintáctico* : forma estándar de representar las notaciones EBNF.
      - Terminales círculos.
      - No Terminales cuadrados.
      - [[id:TeLenProg]] pag 176 hay ejemplos.
- Los diagramas sintácticos y la notación EBNF son de especial utilidad a la hora de escribir un *analizador sintáctico*.
      - Que emplee *análisis sintáctico descendente*.

** La semántica de los lenguajes de programación
- [[id:TeLenProg]] pag 177
- La semántica no está estandarizada ni consensuada como en el caso de la sintaxis.
- *Métodos informales* de especificar la semántica.
      - Mediante un manual de referencia del lenguaje, aunque puede ser impreciso.
      - Mediante el uso de un traductor para definir la semántica. Habrá preguntas que no puedan ser contestadas hasta la ejecución del programa.
- Con los métodos informales es dificil depurar los errores del traductor.
- *Semántica denotacional* : Método formal de especificación de la semántica.

*** Atributos, vínculos y funciones semánticas
- La descripción semántica de un lenguaje tienen que estar incluidas las reglas que determinan el significado de cada uno  de los nombres o *identificadores* utilizados para las variables, procedimientos y constantes.
- El significado de un identificador queda determinado por las propiedades o atributos asociados al mismo.
- Atributos especialmente importantes:
      - *valores* : Representan cualquier cantidad almacenada.
      - *localizaciones* : Lugares donde se almacenan los valores (direcciones en memoria).

#+begin_src C
const int n=5;     // Asocia a n el atributo /tipo de datos/ constante entera
                   //  y el atributo /valor/ 5
int x;             // Asocia a x el atributo /variable/, atributo /tipo de datos/ entero
double f(int n) {  // Asocia el atributo /función/ a f.
                   //  Además de identificadores de los parámetros, tipos devueltos,
                   //  Y el cuerpo de código que devuelve la función.
    // ...
}
#+end_src

- *vínculo* : Es el proceso de asignación de un atributo a un identificador.

#+begin_src C
x=2;  // También es un vínculo,
      //  Se asocia el atributo /valor/ 2 al identificador x.
#+end_src

- *Tiempo de vinculación* : Tiempo que en el que se está calculando o vinculando un identificador.
- *Vínculo estático* : La vinculación se hace en tiempo de traducción.
- *Vínculo dinámico* : La vinculación se hace en tiempo de ejecución.
      - *atributo dinámico* : Atributo vinculado de forma dinámica.
- Los compiladores generan muchos más vínculos estáticos (más eficiente).
- Por convenio el tiempo de vinculación de un atributo es el tiempo más corto de los que las reglas del lenguaje permiten.
- Un *atributo estático* puede vincularse:
      - *En tiempo de traducción* (o compilación).
      - *En tiempo de linkado*, encadenamiento del programa con la bibliotecas.
      - *En tiempo de carga*, Durante la carga del programa para la ejecución.
      - *En tiempo de definición del lenguaje*.
            - Como por ejemplo los tipos de datos.
      - *En tiempo de implementación del lenguaje*.
            - Como por ejemplo tipos de datos cuyo tamaño depende de la implementación.
                  - int, valor de maxint, etc
- *Tabla de símbolos* : mecanismo para mantener la consistencia de los vínculos y los identificadores.
- Los compiladores generan código para conservar durante la ejecución del programa ciertos atributos.
      - La asignación de memoria para almacenar el vínculo de los identificadores con localizaciones de almacenamiento, se realiza por separado, en el *ambiente* o *entorno*.
      - *Estado del cómputo* : vínculos entre las localizaciones de almacenamiento y los valores.
- En un *compilador* se encuentran las siguientes funciones semánticas para relacionar identificadores con sus atributos:
      - *Tabla de símbolos* : la [[id:c05d9849-2e4d-45ad-a766-71109e308b53][Tabla De Símbolos]] almacena la asignación de identificadores a atributos estáticos.
      - El [[id:bccb71cd-1ae0-46a9-8f52-1989b118ae06][ambiente]] asigna identificadores a localizaciones de almacenamiento.
      - El *estado del computo* asigna localizaciones de almacenamiento a valores.
- En un *intérprete* se procesan tanto los atributos estáticos como los dinámicos.
      - Se combina la *tabla de símbolos* y el *ambiente*.

*** Declaraciones, bloques y alcance
- Las *declaraciones* pueden establecer vínculos de forma implícita o explícita.
      - vínculo implícito : no declarada literalmente.
      - vínculo explícito : declarada literalmente.
      - int x vincula explicitamente el tipo de datos, e implícitamente la localización de memoria exacta.
- en C y C++.
      - *Definición* : vincula todos los atributos potenciales.
      - *Declaración* : vinculo sólo algunos atributos.
- *bloque* : constructor específico de un lenguaje.
      - Las declaraciones suelen estar asociadas a los bloques.
      - Secuencia de declaraciones junto a secuencia de de sentencias rodeadas por *marcadores*.
      - En C los bloques se denominan *sentencias compuestas*.
- *registros* : constructores del lenguaje diferente a los bloques.
      - structs de C.
- *clase* : constructor básico.
      - como en Java, que no necesita estar dentro de otra declaración.
- En algunos lenguajes las declaraciones pueden elgobarse en grupos más grandes.
      - paquetes, módulos, espacios de nombres, etc...
- *alcance* o *ámbito* del vínculo : región del programa en la que se conserva dicho vínculo.
      - Debe evitarse el uso del concepto *alcance* referido a los identificadores.
            - Pueden haber varias variables i en diferentes puntos del programa.
- *Alcance léxico* : En la mayoría de lenguajes estructurados por bloques, el alcánce de un vínculo queda limitado al bloque en que aparece su declaración.
      - *Declaración antes de uso* : el alcance de una declaración comienza en la propia declaración.
            - Como en C
- En lenguajes por bloques las declaraciones en bloques anidados toman preferencia sobre declaraciones anteriores.
      - *visibilidad de una declaración* : como en el caso siguiente de C, algunos vínculos quedan ocultos.
            - *ocultamiento del alcance* o *agujeros* o *hucos* : Es el proceso de ocultar un vínculo.
- *operador de resolución de alcance* :  En el caso de C podemos usar el operador "::" para acceder a la variable ocultada.
      - También se usa en los *namespace* y *clases* de C++ por ejemplo

#+begin_src C
int x;

void p (void) {
    char x;  // ocultamiento por alcance
    //...
    ::x = 7; // operador de resolución de alcance
}

main() {
    x = 2;
}
#+end_src

- En C la palabra *extern* permite acceder a la declaración de otro archivo ".c".
      - Permite compilar por separado e identificarse en la vinculación.
- *static* en un archivo ".c" o ".cpp" es solo visible desde el interior.
      - Una restricción del alcance.
- Las reglas de alcance deben tener en cuenta la recursividad.
      - En Haskell es a tope.
- Generalmente las declaraciones locales en el interior de una clase tienen a toda la clase como alcance.

*** Tabla de símbolos
:PROPERTIES:
:ID:       c05d9849-2e4d-45ad-a766-71109e308b53
:END:
- [[id:TeLenProg]] pag 188
- La tabla de símbolos contiene un conjunto de identificadores y para cada uno de ellos una pila con las declaraciones asociadas a él.
      - Las declaraciones en la cima de la pila son las visibles en cada momento.
      - Así se asegura que al salir de bloque el anterior vínculo se restrablezca.
- Ejemplos de la tabla de símbolos (en el libro hay más).

| Identificador | Pila (cima)                               |             |
|---------------+-------------------------------------------+-------------|
| x             | double local de p                         | int global  |
| y             | int array local de un bloque anidado en p | char global |
| p             | void función                              |             |

- Tabla de símbolos según aparece durante la ejecución, *alcande dinámico*.
      - [[id:TeLenProg]] pag 191 un ejemplo
      - Es dificil de implementar y produce problemas.
            - La semántica de una función puede cambiar según avanza la ejecución.
            - No pueden definirse el tipo de datos de las variables.
      - Puede ser válido para lenguajes muy dinámicos en los que no se hagan programas grandes.
- Ejemplo del alcance dinámico en elisp.

#+begin_src elisp
(defun A ()
  (setq-local a "soy a"))

(defun B ()
  (A)
  (message "Desde B : %s" a))

(B)
#+end_src

#+RESULTS:
: Desde B : soy a

- Mantener una sola tabla única para todo el programa con inserciones es propia de lenguajes simpres como C o Pascal.
      - Aún así existen excepciones en C.
      - los estructs contienen subtablas con las declaraciones de sus miembros.
      - Estas subtablas no pueden eliminarse hasta que que la "variable" struct sea eliminada.
            - Esto es al final del programa.

#+begin_src C
struct {
    int a;
    char b;
    double c;
} x = {1, 'a', 2.2};

void p () {
    struct {  // aunque no accesible esta definición queda almacenada
                //  hasta el final del programa.
        double a;
        int b;
        char c;
    } y={1.2, 3, 'b'};
}

void q () {
    /* struct B var = {0.0, 3, 'q'}; */
    /* struct A var = {0, 'q', 0.2}; */
}

void main() {
}
#+end_src

*** Asignación, tiempo de vida y ambiente
:PROPERTIES:
:ID:       bccb71cd-1ae0-46a9-8f52-1989b118ae06
:END:
- [id:TeLenProg] pag 196
- *El ambiente* se encarga de mantener los vínculos de los identificadores con las localizaciones de memoria.
- En general en un lenguaje con estructura de bloques:
      - Los identificadores de las variables globales se asignan estáticamente porque su significado es fijo en el programa.
      - Los identificadores de las variables locales se asignan dinámicamente cuando la ejecución llega al bloque.
- _En el ambiente se mantiene una estructura de pila para vincular las localizaciones a las variables_.
      - Cada posición en la pila es una dirección en memoria para el bloque.
            - Memoria contigua dentro del bloque no contigua con otros bloques.
- *objeto* : Área de almacenamiento asignada en el ambiente tras el procesamiento de una declaración.
      - El *tiempo de vida* o *extensión* de un objeto es la duración de su asignación en el ambiente.
- Lenguajes con *punteros* es necesaria una extensión del ambiente.
      - Y mecanismos para la asginación de memoria.

#+begin_src C
#include <stdlib.h>
#include <stdio.h>

int main(void) {
    int * x = NULL;

    x = (int*) malloc(sizeof(int));
    
    free(x);

    printf("end example");

    return 0;
}
#+end_src

#+RESULTS:
: end example

- Para permitir la asignación arbitraria de memoria el ambiente debe tener un área enla memoria para ello (*montículo*, heap), se conoce como *asignación dinámica*.
      - *Asignación automática* cuando no es en el heap (stack).
- *clases de almacenamiento* : en un lenguaje con estructura por bloques ser refiere a la correspondencia con los tipos de asignación de localizaciones en el ambiente.
      - Estático (variables globales), automático (variables locales), dinámico (para asignación de montículos).

#+begin_src C :results output
#include <stdlib.h>
#include <stdio.h>

int p(void) {
    static int p_count=0; // Se inicia una sola vez, aunque el alcanze es local.
    p_count +=1;
    int x=0;

    // cuidado con las asignaciones en bloques if
    if (x=p_count) {
        printf("Destruction, x=%d\n", x);
    }

    return p_count;
}

int q(int a) {

    const int b = 7 + 2 * 2;
    const int c = a+b;

    int arr[a];

    printf("Value b : %d\n", b);
    printf("Value c : %d\n", c);
    
}

int main(void) {
    p();
    q(10);
    q(20);
    return 0;
}
#+end_src

#+RESULTS:
: Destruction, x=1
: Value b : 11
: Value c : 21
: Value b : 11
: Value c : 31

*** Variables y constantes
- [id:TeLenProg] pag 201
- atributos de una variable
      - identificador
      - localización
      - valor
      - otros
- *valor r* : Valor almacenado (esto en c++ es muy usado para las operaciones de std::move)
- *valor l* : Localización de una variable
- *Asignación por compartición* : copia las localizaciones no los valores.
- *Asignación por clonación* : Copia el valor en una localización nueva.
- *Semántica de puntero* : no la entiendo muy bien
      - Dice que lo usa Lisp e imagino que se refiere a la de C.
- *Semántica de almacenamiento* : La más habitual
- Las *constantes* tienen semántica de valor, porque nunca cambian.
      - 77 o "a" se reconocen como constantes pero se denominal *literales*.
            - Para distinguirlas de las constantes declaradas en el programa.
- Clasificiación de las constantes:
      - *Constantes estáticas* : Cuyo valor se puede calcular antes de la ejecución (constexpr en C++).
            - *Constantes en tiempo de compilación*.
                  - Mejoran la eficiencia y no consumen memoria.
            - *Constatnes estáticas* : se calculan en la carga del programa.
      - *Constantes dinámicas* : Cuyo valor solo se puede computar en tiempo de ejecución.
- En java *final* es la palabra clave para definir constantes.
- En casi todos los lenguajes las definiciones de *funciones* son definiciones de constantes, cuyos valores son funciones.

#+begin_src C :results output
#include <stdlib.h>
#include <stdio.h>

int gcd (int u, int v) {
    if (v==0) return u;
    else return gcd(v, u % v);
}

typedef int(*FuncType)(int,int);

int main(void) {
    // asignación de una función a una variable.
    FuncType fun_var = gcd;

    printf("gcd %d\n", fun_var(15,10));
    return 0;
}
#+end_src

#+RESULTS:
: gcd 5

* Tipos de Datos
- [id:TeLenProg] pag 215
- *Tipos de datos* : Clases diferentes de información que el ordenador puede almacenar.
- La información que maneja un programa representa una abstracción de la realidad.
- *Lenguajes fuertemente tipados* : lenguajes donde es necesario expresar de forma explícita los datos y además realiza una estricta verificación de los tipos en tiempo de traducción.
      - Los compiladores puede optimizar la gestión de memoria. *Mejora la eficiencia de ejecución*.
      - Se puede reducir el código que necesita ser compilado. *Mejora la eficiencia de traducción*.
      - Evita errores debidos al mal uso de los datos.
            - Mejora capacidad de escritura.
            - Mejora la seguridad y la confiabilidad.
            - Elimina ambigüedades.
      - Mejora la legibilidad.

** Tipos de datos
- Conceptos necesarios:
      - *Tipo abstracto de datos* : Comportamiento semántico que se puede realizar sobre los datos que representa. Sin llegar a la implementación.
      - *Estructura de datos* : Representación computacional concreta de la organización de los datos del tipo abstracto. En términos de los *tipos de datos primitivos* del lenguaje.
      - *Tipo de datos* : Dotar a una *estructura de datos* de la operaciones definidas en el *tipo de datos abstracto*.

- Elementos susceptibles de ser tipados llevan una declaración de tipo.

#+begin_src java
int x;    // int es el identificador del tipo.
int x=66; // lo mismo con una asociación del valor inicial.
#+end_src

- El *tipo abstracto de dato* permite discernir el tipo real de unos bytes.
      - Las operaciones que se pueden realizar sobre esos datos.
- *Veridicación de tipos* : Llamada que comprueba que los tipos se están usando correctamente.
      - Permite resolver la sobrecarga.
- *Lenguajes débilmente tipados* : Se permiten operaciones que no pertenencen al *tipo abstracto de datos*. Ejemplo C sumando variables char.
- *Lenguaje no tipado* : Lenguaje que no posee ninguna información sobre los tipos. Ejemplo Prolog.
- *Inferencia de tipos* : deducir el tipo en función en función a la información de tipos que se haya indicado (como en la sobrecarga).
      - Haskell presenta un complejo sistema de inferencia de tipos (además creo que es fuertemente tipado).

#+begin_src C
int x = 5 / 2;  // Se deduce la operación división sobre enteros.
float y = 5/2;  // Se deduce la operación división sobre reales.
#+end_src

- *Tipos definidos por el usuario* : Tipos más complejos en base a los tipos básicos.
      - *Constructores de tipos* : Permite la creación de tipos *definidos por el usuario*.
      - Se complica el proceso de verificación de datos.
            - *Equivalencia de tipos* : Comprobar si dos tipos provenientes de diferentes declaraciones de tipo son o no equivalentes.

#+begin_src C
int x[10];  // definición de una array de 10 elementos
            //  Como no tiene nombre es un tipo anónimo.
#+end_src

- *Tipo anónimo* : Definición de un *tipo definido por el usuario* sin nombre.
- *Definición de tipo* : Definir un nuevo *tipo definido por el usuario* con nombre.

#+begin_src java
public class ArrayEnteros {
    private int[] x;

    // con constructor
    public ArrayEnteros(int tam) {
        x = new int[tam];
    }

    public int getElemento(int idx) {
        return x[idx];
    }
}
#+end_src

- *Programas peligrosos* : programas que contienen errores de tipos que pueden corromper los datos (accesos a componentes inexistentes o división por 0).
- *Programas seguros* : No contienen los errores anteriores.
- *Programas correctos* : Programas que pueden ser aceptados por un intérprete o compilador fuertemente tipado.
      - Es un subconjunto de los *programas seguros*.

- *Sistema de tipos* : Mecanismos para la creación de nuevos tipos más los algoritmos de verificación, inferencia y equivalencia.
      - Los lenguajes fuertemente tipados poseen un sistema de tipos estático.
            - Garantiza que los *programas peligrosos* son rechazados en tiempo de compilación.
      - Pueden rechazar algunos *programas seguros* (programas no peligrosos).

- *Lenguajes con tipado dinámico* : No usa el sistema de tipos estáticos.
      - Una variable es tipada según el flujo del programa.
      - El tipo depende del valor.

#+begin_src scheme
(define x valor)
#+end_src

*** Tipos de datos atómicos
- [id:TeLenProg] pag 221
- *Tipo atómico* : no es posible separarlo en elementos más sencillos.
- *Tipos discretos* : Dado un valor es posible definir su sucesor o predecesor.
      - Salvo los números reales.

**** Enteros
- java ofrece *byte* (1B), *short* (2B), *int* (4B) y *long* (8B). La diferencia es el tamaño de memoria.
- Haskell ofrece *Int* acotados, *Integer* sin acotar (consume más memoria).
- Operaciones comunes:
      - suma
      - resta
      - producto
      - división entera
      - módulo

**** Reales
- Se suelen representar utilizando el estándar IEEE-754.
      - mantisa * 10^{exponente}.
- Java y Haskell ofrecen el float, Float y el double, Doueble.
- Operaciones comunes :
      - suma
      - resta
      - producto
      - división
      - módulo
      - Raiz cuadrada
      - Logaritmo neperiano
      - Exponenciación

**** Carácteres
- En Java *char* ocupa 2 bytes.
      - Estándar UNICODE^8
- En Haskell *Char* sigue el estándar ASCII-7.
- Operaciones en [id:TeLenProg] pag 223

**** Booleanos
- Java se denomina Boolean
- Haskell se denomina bool
- Operaciones comunes en el *Álgebra de Boole*.

**** Tipos Enunerados
- Atómicos definidos por el usuario junto con las operaciones que se definan.
- Conjunto de posibles valores es finito.
- Por ejemplo los días de la semana.

**** Rangos
- Tipos definidos por el usuario.
- Toman valores de un subconjunto contiguo de un tipo discreto
- Ada y Pascal lo permiten.

*** Tipos de datos estructurados
- Pueden descomponerse en otros más simples.

**** Arrays
- Estructura matricial de 1 o varias dimensiones.
- Es posible acceder a uno de los elementos indicando los índices.
- Normalmente los índices empiezan en 0.
- En Haskell no existe el concepto array como tabla.

**** Funciones
- Muy útil en general.
- Muy importante para lenguajes con funciones como *ciudadanos de primera clase* (haskell).
- Se pueden considerar clases porque representan un *conjunto* de operaciones (cada operación es el valor). con su dominio y su codominio.

**** Producto Cartesiano
- Producto cartesiano de dos conjuntos, tuplas en Haskell (sin nombre).
      - Haskell también puede hacer tipos con nombre.
- registros o structs en C (con nombre).
- record en Pascal.

**** Tipos Recursivos
- El tipo definido aparece en su propia definición.
      - Por ejemplo un árbol.
- En Java se implementa mediante clases.
- En Haskell con *data* de una forma muy sencilla.

**** Unión de tipos
- Unión de dos conjuntos (Toma el valor de un conjunto o del otro).
- Si todos los tipos participantes son *atómicos* la unión también es *atómica*.
- *Unión Indiscriminada*
#+begin_src C
typedef union {
    int i;      // Ambos valores residen en la misma dirección.
    char c;
} IntOrChar;
IntOrChar x;
#+end_src

- *Unión Discriminada* : un discriminante indica al tipo al que pertenencen. 
#+begin_src haskell
data IntOrChar = Entero Int | Caracter Char
#+end_src

** Equivalencia de Tipos de Datos
- [id:TeLenProg] pag 230.
- *Equivalencia de tipos* : Responsable de decir si dos tipos son iguales o no (o compatibles).
- *Equivalencia estructural* : Representan el mismo conjunto de valores.
      - Se puede comprobar sustituyendo el nombre del tipo por su definición.
      - Problemático con tipos recursivos.
      - Problemático con tipos anónimos.
- *Equivalencia en nombre* : Dos tipos son equivalentes si tienen el mismo nombre.
      - Problemático con los alias de tipos.
      - Problemático con tipos anónimos.

** Conversión de Tipos de Datos
- Por ejemplo la necesidad trabajar con *enteros* y *reales*.
- *Conversión implícita de tipos* : Conversión automática cuando es posible.
      - Puede dar lugar a comportamientos inesperados.
      - Java permite.
#+begin_src java
byte b;
short s;
int i;
long l;
s=b; i=b; l=b;

// b=i  // no es posible
#+end_src

- *Conversión explícita* (o forzada) : La conversión de tipo se delega al programador.
      - Carga la tarea en el programador.
      - Una variante son las *funciones específicas* como *truncate*.

#+begin_src C
double x = (double)(3+2);
#+end_src

- Algunas *funciones específicas* son:
#+begin_src java
// Convertir una cadena de carácteres que contiene un valor.
String s = Integer.toString(34);    // "34"
Integer i = Integer.parseInt("34"); // 34
#+end_src

* Control de la Ejecución
- [id:TeLenProg] pag 241

** Evaluación de expresiones
- *Expresión* : estructura que representa un valor concreto de uno de los tipos de datos del lengueje.
- Expresiones básicas:
      - *constantes*
      - *identificadores*
- Expresiones complejas se elaboran mediante *funciones* y *operadores* a otras expresiones más símples.
- Operadores:
      - *unarios* : Se aplican a un único operando.
      - *binarios* : Se aplican a 2 operandos.
- *funciones* : reciben varios parámetros y devuelven un valor de salida.

*** Notaciones infija, prefija y postfija
- *Notación infija* : situa los operadores entros los operandos
      - A * B
      - La más común
- *Notación prefija* : Situa el operando delante de los operadores
      - * A B
      - No existe ambigüedad.
- *Notación postfija* : operandos preceden al operador.
      - A B *
      - No existe ambigüedad.
      - Muy util para resolver las operaciones con una pila.
            - operandos se apilan, operadores sacan de la pila y meten el resultado.
            - Calculadora de emacs.

*** Evaluación de una expresión
- *Evaluación impaciente* o *Evaluación estricta* : operandos o parámetros han de ser evaluados antes de los operadores o funciones.
- *Efecto colateral* : Problemas que surgen del orden de resolución de llamadas aparentemente no conectadas.

#+begin_src java
static int x;

static int colateral () {
    x++;
    return x;
}

public static void main(String[] args) {
    x=1;
    int y = x + colateral();
    System.out.println(y);

    x=1;
    int z = colateral() + x;
    System.out.println(z);
}
#+end_src

#+RESULTS:
: 3
: 4

- Si el lenguaje establece el orden de resolución el programador puede tenerlo en cuenta para evitar efectos colaterales.

- *Evaluación no estricta* o *evaluación diferida* : La evaluación de los parámetros de una función se difieren hasta que sea necesarios.
- *Transparencia referencial* : El valor de una expresión o parámetro no varía según cuando sea resuelto.
      - *Evaluación normal* : Si se cumple la transparencia referencial una función puede empezar a ser evaluada antes que sus operandos.
- *Evaluación perezosa* : lo de Haskell. Se retrasa hasta tener toda la información suficiente par la evaluación de la función.
- *Evaluación en cortocircuito* o *evalueción McCarthy* :
      - false AND x : no es necesario evaluar x
      - true or x : no es necesario evaluar x
      - Permite proteger de realizar accesos a componentes inexistentes. 
- *Operadores ansiosos* : Lenguajes como Fortran sin evaluación en cortocircuito.
- *if-then-else* : operador ternario también se puede evaluar en cortocircuito.
      - c ? t : e
- Expresiones *case* : extensión de las expresiones *if* con más de dos opciones posibles.
      - Primero se evalue la expresión de control
      - Luego se comprueba en que patrón encaja.

** Sentencias Condicionales
- Restringir la ejecución de una serie de sentencias si se cumple una serie de condiciones.
- Forma general de una sentencia if (Dijkstra 1975)
      - Semántica:
            - Gi son guardas, todas se evaluan. Si secuencia de sentencias.
            - Gi es verdadero se ejecuta Si
            - Más de una guarda verdadera solo se ejecuta una de ellas.
            - Ninguna guarda verdadera se produce un error.

#+begin_example
if G1 -> S1
   ...
   Gn -> Sn
fi
#+end_example

- En su forma más pura no es determinista, pero en la realidad se evaluan en orden y se ejecuta la primera que tiene una guarda verdadera.

*** Sentencias if-then-else
- if (e) then s1 [else s2]
- Muchos lenguajes omiten la palabra then.
- Primero se evalua *e*
      - Si resulta verdadero se ejecuta s1
      - Sino si existe un bloque else se ejecutará s2.
- *Problema del else ambiguo* : Aparece con anidamientos de ifs
      - if (e1) then if (e2) then s1 else s2  // A que if pertenece el else?
      - Algunos lenguajes optan por asociar el else al if más cercano.

#+begin_src java :results output
if (true) System.out.println("IF 1");
    if (false) System.out.println( "IF 2");
    else System.out.println("Sentencia Else");
#+end_src

#+RESULTS:
: IF 1

- *elseif* : Permite trabajar con múltiples alternativas al mismo nivel.
      - Se evalua $e_i$, si resulta falsa se evalua $e_{i+1}$.
      - Si ningún $e_i$ resulta verdadero se evalua el *else*.
#+begin_example
if (e1) {}
elsif (e2) {}
...
else {}
#+end_example

- Una expresión siembre debe devolver un valor, una sentencia no es necesario.

*** Sentencias case

#+begin_src java
switch (e) {
    case valor1 : s1; break;
    // ...
    case valorn : sn; break;
    default sd;
}
#+end_src

- Semántica
      - Se evalua e, que no tiene porque ser booleana.
      - Se evalua la sentencia con valori coincidente con el valor de e.
      - Si no coincide se evalue sd.

- En el libro dice que azucar sintático, que es lo mismo que if elseif ... else.
      - En casos de opciones densas (0,1,2,...) el compilador puede hacer optimizaciones mucho más agresivas.

** Bucles
- Dijkstra forma general de un bucle.

#+begin_example
do G1 -> S1
   ...
   Gn -> Sn
od
#+end_example  

- Semántica
      - Se evalúan las guardas y se selecciona una con resultado verdadero para evaluar el bloque Si (de forma no determinista).
      - El proceso se repite hasta que todas las guardas se evalúan como falso.
- La forma más común de bucle es el *while*, con solo una guarda.
      - while (e) s
      - *condición de terminación* o *condición de salida*: sentencia e.
      - *cuerpo del bucle* : las sentencias s
      - do s while (e); : Fuerza la ejecución del cuerpo almenos una vez.

- el bucle *for* es similar.
      - for (si; e; sa) s;
      - Es equivalente a
            - si;
              while (e) {
                s;
                sa;
              }
      - Donde:
            - si es la sentencia de iniciación.
            - e es la condición de terminación.
            - sa es la sentencia de actualización.
            - s es el cuerpo del bucle.
- Algunos lenguajes permiten interrumpir la ejecución del bucle (break), pero dificulta la semántica del bucle.

** Excepciones
- *Estructuras de control explícitas* : las estructuras de control anteriores.
- *excepciones* : controlan aquellos eventos que violen las restricciones semánticas del lenguaje.
      - Generando un error de ejecución.
- *manejador de excepciones* : código del programa encargado de capturar las excepciones lanzadas.
- Permite que el diseño de *confiabilidad* sea más fácil de alcanzar.
      - Permite al programa recuperarse después de un error.
- *Execepciones asíncronas* : hay errores más bajos que la propia ejecución del programa.
      - Pueden suceder en cualquier punto de la ejecución del programa con independencia del código del mismo.
- *Excepciones síncronas* : Pueden surgir como respuesta a la ejecución de los programas.

*** Definición de excepciones
- *Excepciones comprobadas* : Error del cual el programa puede recuperarse.
      - Clase Excepción y subclases.
- *Excepciones no comprobadas* : Errores de programación.
      - Clase Error y subclases.
- Se pueden crear nuevas clases de excepciones heredando de *Exception* (comprobada por el compilador).
      - heredando de *RuntimeException* no es necesario que su captura sea comprobada por el compilador. 

*** Definición de manejadores de excepciones y control de flujo
- En java mediante bloques *try-catch-finally*
      - Se elevan excepciones con *throw new ExceptionType();*
      - Se indica que un subprograma puede elevar excepciones con:
            - public static void sprograma(params...) *throws* (tiposExcepción,...)

- *finally* se ejecuta siempre, haya o no excepción.
- Tienen un impacto con la eficiencia respecto a la ejecución, no se recomienda abusar de estos bloques de control.

** Subprogramas
- *subrutina* : código autocontenido.
- *procedimiento* : No devuelve valor.
      - Podría producir un efecto colateral.
      - Tipo sentencia.
      - *métodos* : como en java (forman parte de una clase).
- *funciones* : devuelve valor.
      - No debería producir un efecto colateral.
      - Tipo expresión.
- *declaración* :
      - *intefaz* : identificador del subprograma, parámetros de entrada, valor devuelto.
      - *cuerpo* : Sentencias que ejecuta el subprograma cuando sea invocado.
- Cuando se llama a un subprograma se le transmite el control de la ejecución.
      - Cuando el subprograma finaliza devuelve el control de la ejecución al programa o subprograma que lo invocó.

*** Semántica
- El significado de los identificadores viene determinado por el ambiente (o entorno).
- *Registro de activación* : Los subprogramas pueden contener identificadores locales.
      - Memoria donde se almacenan los identificadores locales de un subprograma.
- *forma cerrada* : subprogramas sin referencias no locales.

*** Paso de parámetros
**** Paso por valor
- El más utilizado.
- Las expresiones son evaluadas previo a la ejecución del subprograma.

**** Paso por referencia
- Requirere que los parámetros sean variables con un adirección dentro de la memoria.

**** Paso por valor-resultado
- *Paso por copia-restauración* o *paso por copia de entrada salida*.
- Requiere que los parámetros sean variables.
- El valor del parámetro es copiado en el parámetro, puede ser modificado en el cuerpo, y al acabar vuelve a ser copiado de vuelta en la dirección original de la variable.

**** Paso por nombre
- [id:TeLenProg] pag 268
- No se evalua la expresión.
- Evaluación no estricta.
- Si un parámetro no se utiliza no se pierde tiempo evaluándolo.

*** Ambientes de ejecución
- El ambiente de cada subprograma en un Lenguaje con alcance léxico se puede gestionar con una pila.
      - Registros de activación.

**** Ambientes totalmente estáticos
- [id:TeLenProg] pag 270
- fortran77 no permite definiciones de subprogramas anidadas ni recursión.
      - Referencias no locales son siempre variables globales.

**** Ambientes basados en pilas I : lenguajes con recursión sin anidamiento
- Si hay recursión no es posible asignar memoria estática para los registros de activación.
      - Se almacenande forma dinámica.
- *Pila de registros de activación* : Se estructura la pila de activación en registros de activación.
      - Cada registro de activación tiene los datos estáticos de la llamada.
            - *Enlace de control* : También la dirección del registro llamante.
            - La dirección de cada subprograma está en la tabla de símbolos en tiempo de compilación.
      - *Puntero de ambiente* : Almacena donde comienza el registro de ejecución del ambiente actual.

**** Ambientes basados en pilas II : lenguajes con recursión y anidamiento
- Lenguajes que además permiten definir subprogramas anidados.
- *Enlace de acceso* : Un subprograma debe almacenar informaciónde cuál es su ambiente de definición.
      - Para resolver el valor de variables no locales.
- *Encadenamiento de accesos* : Proceso de resolver el valor de una variable no local dentro del anidamiento de funciones.
      - *Profundidad de anidamiento* : número de accesos que se debe seguir hasta encontrar el valor de una variable.
- La *pila de registros de activación* es similar a la anterior.
      - Se añade el enlade de acceso.

**** Ambientes totalmente dinámicos
- Un subprograma puede ser capaz de devolver otro subprograma.
- Se debe guardar en el ambiente el registro de activación del subprograma generador mientras haya referencias al subprograma generado.
- Precisa de *conteos de referencias* y *recolección de basura*.

* Glosario
- *Evaluación impaciente* : /factorial(4*5)/ primero evalua el resultado de 4*5.
- *mónadas* : indivisibles

* Tools
** Haskell compiler and interpreter
#+begin_src sh
ghci       # Open the haskell interpreter
#+end_src

* Bibliografía

** Teoría de los lenguajes de programación
:PROPERTIES:
:ID: TeLenProg
:TIPE: book
:TITLE: Teoría de los lenguajes de programación
:EDITORIAL: Ramón Areces
:AUTHOR: Fernando López Ostenero, Ana María García Serrano
:END:

** Webs de interés
http://aprendehaskell.es/main.html
https://learnyouahaskell.github.io/introduction.html
