#+title: Teoría de los lenguajes de Programación
#+author: Jordi Amposta Pérez
#+LATEX_HEADER: \usepackage{tikz}

#+startup: latexpreview content

* Paradigmas de computación
- Generaciones Lenguajes Programación
      - Primera generación lenguajes máquina.
      - Segunda generación ensambladores (mnemotécnico del lenguaje máquina).
      - Tercera generación lenguajes de alto nivel como C
            - Lenguajes de propósito general.
            - Requieren compiladores o intérpretes.
      - Cuarta generación lenguajes de propósito específico como SQL.
      - Quinta generación, muy relacionada con el área de la Inteligencia Artificial.
            - Se especifica el problema y como se resuelve con una secuencia de acciones.
            - Prolog y Haskel.

** Abstracción en los lenguajes de rogramación
- Abstracción de datos y de control

| *Abstracción*  | *De Datos*                    | *De Control*                        |
|--------------+-----------------------------+-----------------------------------|
| *Básica*       | Tipos atómicos de variables | goto                              |
| *Estructurada* | tipos estructurados         | bucles condicionales subprogramas |
| *Unitaria*     | módulos paquetes            | módulos paquetes                  |

*** Abstracción de Datos
- Abstracciones de datos básicas
      - *Tipos atómicos*, tipos que no pueden dividirse en tipos más sencillos.
      - Nombres de variables son una abstracción.
- Abstracciones de datos estructuradas
      - Arrays
      - En C el typedef int MyTable[7]; Crea un tipo de dato estructurado.
- Abstracciones de datos unitarias
      - Agrupación de datos y operaciones sobre ellos.
      - Encapsulado de datos
      - Clases, Tipos abstractos, interfaces.

*** Abstracción de Control
- Abstracciones de Control básicas
      - Sentencias para modificar el flujo de ejecución.
      - goto
- Abstracciones de control estructuradas.
      - Bucles o sentencias condicionales (if)
      - Permiten anidamiento
      - Subprogramas (funciones, métodos, procedimientos)
- Abstracciones de control tipo unitario
      - Colección de subprogramas en una unidad en si misma independiente del programa.
        
** Introducción a los paradigmas de computación
- Inicialmente los lenguajes se basaron en el *modelo de computación Von Neumann*.
      1. Ejecución secuencial de instrucciones.
      2. Variables representan posiciones de memoria.
      3. Asignación para cambiar el valor de las variables.
- También se conocen como *Lenguajes Impertarivos*, paradigma imperativo.
- paradigmas
      - Imperativo
            - Programación oritendata a objetos.
      - Declarativo
            - Funcional, abstracción de funciones matemáticas.
            - Lógico

*** Programación orientada a objetos
- *Objeto*, conjunto de posiciones en memoria más las operaciones sobre los valores que almacenan dichas posiciones.

*** Programación funcional
- Evaluación de funciones.
      - Transferencia de valores como parámetros de las funciones que se evaluan.
      - Generación de resultados en forma de valores devueltos por las funciones.
- No involucra la asignación de una variable a una posición de memoria.
- Operaciones repetitivas mediante funciones recursivas.
      - Operaciones repetitivas NO se representan mediante ciclos.

#+caption: Ejemplo en Haskell        
#+begin_src haskell
gcd u v
    v == 0 -> u
    otherwise -> gcd v (mod u v)

gcd 18 8
#+end_src

*** Programación lógica
- Conjunto de sentencias que describen lo que es verdad o conocido.
- El control lo aporta el modelo de inferencia lógica.

#+begin_src prolog
gcd(U, 0 , U).
gcd(U, V, X) :- not (V=0),
                Y is U mod V,
                gcd(V, Y, X).
#+end_src

Busca el valor de X que hace cierta la siguiente pregunta.

#+begin_src prolog
?- gcd(18,8,X).
#+end_src

** Descripción de los lenguajes de programación
- Elementos fundamentales
      - *Léxico* o tokens (if, else)
      - *Sintáxis*, Estructura de los diferentes componentes del lenguaje y sus combinaciones.
            - Se pueden describir con el uso de gramaticas libres de contexto.
            - 
              #+caption: Sentencia if de C
              #+begin_example
              <sentencia if> ::= if (<expresion>) <sentencia> [else <sentencia>]
              #+end_example

      - *Semántica*, expresa los efectos de la ejecución en un contexto determinado.
            - Sistemas de notación de la semántica (no hay una forma aceptada).
                  - *Semántica operacional*
                  - *Denotacional*
                  - *Axiomática*

*** Traducción de los programas para su ejecución
- *Intérprete*, Un programa que acepta entradas del lenguaje y los ejecuta.
- *Compilador*, Programa que traduce el languaje a código máquina.
- El traductos (intérprete o compilador) debe seguír fielmente la definición del lenguaje.
- Pasos de un intérprete o compilador.
      - *Analizador léxico*
      - *Analizador sintáctico*
      - *Analizador semántico*
- Tipos de errores
      - *Errores léxicos*, Suele estar kimitado al uso de carácteres ilegibles.
      - *Errores sintácticos*, Tokens que faltan o expresiones malformadas.
      - *Errores semánticos*, Estáticos (uso de tipos incompatibles) o dinámicos (división por 0).
      - *Errores lógicos*, Comportamiento no deseado.

** Diseño de los lenguajes de programación
- Control de la complejidad.
- Legibilidad a la par que facil traducción a lenguaje máquina.

*** La eficiencia
- El diseño debe permitir al traductor la generación de código ejecutable eficiente.
- *Eficiencia de traducción*, El lenguaje debe permitir el desarrollo de un traductor eficiente y de tamaño razonable.
- *Eficiencia de implementación*, Eficiencia con la que puede escribirse un traductor.
- *Eficiencia de la programación*, Rapidez y facilidad para escribir programas.
      - Capacidad expresiva.
      - *Sintactic sugar*, estructuras que facilitan la escritura de un programa.
            - Por ejemplo las diferentes versiones de bucles.

*** La regularidad
- Comportamiento de las características del lenguaje.
- *La Generalidad*, uso y disponibilidad de constructores no están sujetas a casos especiales.
- *La Ortogonalidad*, Los constructores del lenguaje pueden admitir combinaciones significativas, sin restricciones ni comportamientos inesperados.
- *La uniformidad*, Consistencia entre la apariencia y el comportamiento de los constructores.

*** Principios Adicionales
**** Simplicidad
- Que cada concepto del lenguaje se presente de forma única y legible.
- Estructuras con reglas de combinación sencillas.

**** Expresividad
- Facilidad con la que un lenguaje de programación permite expresas procesos y estructuras complejas.

**** Extensibilidad
- Ampliar el lenguaje con nuevas funcionalidades (nuevos tipos, etc).
- *Modularidad*, disponer de bibliotecas.

**** Capacidad de restricción
- El uso suficiente de un subconjunto del lenguaje.

**** Consistencia entre la notación y las convenciones
- Notaciones y características que ya se hayan convertido en estándares.

**** Precisión
- Definición precisa del lenguaje, de forma que los programas sean predecibles.
      - El programa se comporta igual en cualquier máquina.

****  Portabilidad
- La definición del lenguaje de programación es independiente de una máquina en particular.
- Normalmente los lenguajes interpretados son portables.

**** Seguridad
- Este principio pretende evitar los errores de programación y permitir su descubrimiento.
- A veces compromete la expresividad.

**** Interoperabilidad
- La posibilidad de que un código escrito en un lenguaje interactue con el código escrito en otro lenguaje.

* Programación Funcional (Haskell)
- Diferente a la programación imperativa.
      - No tan cercano al hardware.
- *Currificación*, devolver una función desde otra función, aprovechando para reducir el número de parámetros.

**  Programas como funciones
- Un programa funcional contiene funciones definidas por el programador.
      - El programador no se preocupa cómo se realiza el cálculo.
- Las variables no hacen referencia a posiciones en memoria.
- No existe la asignación.
- Sentencias del tipo $x=x+2$ no son válidas.
- Una constante puede ser considerada una función sin parámetro.
- Desaparecen los bucles, en su lugar se hace uso de la *recursión*.
- No existe *estado del cómputo*.
- En programación funcional un programa consiste en la definición matemática de una seria de funciones que toman unos argumentos de entrada y realizan un cómputo sobre ellos.

Ejemplo función factorial en C y en Haskell  

#+begin_src c
int factorial(int n) {
    int f = 1;
    for (int x=1; x <=n; x++) {
        f = f*x;
    }
    return f;
}
#+end_src  

#+begin_src haskell
factorial n
  n <= 0 = 1                       -- definición si n <= 0
  otherwise = n * factorial(n-1)   -- definicinón en otro caso
#+end_src

- Las funciones son ciudadanos de primera clase.
      - Pueden devolverse desde otra función.
      - Pueden pasarse como parámetro.

#+begin_src haskell
suma3 x = x  3
funCuadrado f x = f x * f x

funCuadrado suma3 5
#+end_src

#+RESULTS:

** Evaluación Perezosa
- pag 38
- Se evalua el valor de un parámetro solo cuando se usa.
- función *no estricta*, no necesita conocer el valor de todos sus parámetros para devolver un resultado.
- *memoización*, permite guardar el valor de un parámetro la primera vez que se evaluó.

Ejemplo con listas de haskell.

#+begin_example
[1..]      -- Define una lista de todos los números Naturales desde el 1
1:[2..]    -- Se evalua el primer elemento (lista tipo cabeza cola)
1:2:[3..]
#+end_example

- Permite programar funciones *productoras* y funciones *consumidoras*.

#+begin_src haskell
-- los valores se irán calculando a medida que se acceden
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
#+end_src  

** Introducción a Haskell
- Case sensitive
  
*** Tipos de datos
- Los tipos se escriben en PascalCase
- *Tipos atómicos*
      - *Int*, enteros ligados a la arquitectura del ordenador (acotados).
      - *Integer*, conjunto de números enteros sin ningún límite.
      - *Float*, reales de precisión simple.
      - *Double*, reales de precisión doble.
      - *Char*, carácteres ACII-7.
      - *Bool*, booleanos, True o False.
- *Tipos estructurados*
      - *Tupla*,secuencia finita de valores, pueden tener tipos diferentes.
            - `(4,"vacio", False)`
      - *Lista*, una colección no necesariamente finita de valores del mismo tipo
            - Las cadenas de carácteres son listas de [Char].
            - Son estructuras recursivas cabeza:cola:..:[].
            - *Listas definidas por extensión*
                  - [1,2,3]
                  - [1,3..10]
                  - [1,3..]
            - *Listas definidas por comprensión*
                  - [p | p <- [1..], mod p 2 /=0 ]

*** Definición de Funciones
- Dos formas de definirse
      - *Identificador* una palabra que empiezan siempre en *minúscula*.
            - Puede contener ' _ entre otros símbolos.
            - Se usan de forma *prefija*
            - Se puede usar de forma *infija* usando `
                  - 3 `suma` 4
      - *Operadores*, secuencia de uno más de los siguientes carárcters
            - : ! # $ % * + . / < + > ? @ \ ^ | -
            - Las siguientes combinaciones tienen un uso especial.
                  - :: = .. @ \ | <- -> ~ =>
            - Se utilizan de forma *infija* (exactamente 2 parámetros de entrada).
            - Se pueden usar de forma *prefija* con el uso de ().
                  - (+) 3 4
- *precedencia* y *asociatividad*
      - Se asigna un valor de *precedencia* a cada función (más alto mejor).
      - funciones definidas con *identificador* tiene más precedencia que las definidas por *operador*.
            - f x + 1 sería (f x) + 1

Definir reglas de precendencia y asociatividad.

#+begin_src haskell
asociatividad precedencia lista_de_operadores
-- asociatividad: infixr (derecha), infixl (izquierda), infix (no asocian)
-- precedencia: entre 0 y 9
-- lista_de_operadores: símbolos de operador separados por ,

-- ejemplo de suma y resta

infixl 6 +,-      -- e.g 3 - 5 - 2 = (3 - 5) - 2
#+end_src              

**** Definición ecuacional y encaje de patrones
#+begin_example
identificador <patron1> <patron2> ... <patronN> = <expresión>
#+end_example

- *patron*, Como argumentos de entrada de cada función.
      - Más versatil que un simple argumento.
- Una función puede definirse con más de una ecuación.

***** Patrones Constantes
#+begin_src haskell
f 1 = True
f 2 = False
#+end_src

Cualquier otro valor de entrada generaría un error.

***** Patrones Variables
#+begin_src haskell
suma x y = x + y
#+end_src

***** Patrones anónimos
Se representan con _, no pueden ser referenciados.

#+begin_src haskell
siempre2 _ = 2
#+end_src

***** Patrones para listas
- [], lísta vacía (patrón constante).
- [x], lista con un único elemento referenciado como x.
- (x:xs), lista con un elemento de cabeza x y una cola xs.

#+begin_src haskell
suma [] = 0
suma (x:xs) = x + suma xs
#+end_src

***** Patrones para tuplas
Se referencian entre paréntesis, eg. (x,y,z).

***** Patrones con nombre
#+begin_src haskell
duplicaCabeza l@(x:xs) = x:l
#+end_src

***** Patron aritmético
La siguiente definición substrae 3 del valor de entrada. Están deprecados.
#+begin_src haskell
f (n + 3) = n
#+end_src

**** Expresiones case
#+begin_src haskell
case expresion of
  patron1 -> resultado1
  patron2 -> resultado2
  -- ...
  patronN -> resultadoN
#+end_src

**** Funciones definidas a trozos
#+begin_example
identificador <lista_de_patrones>
  | guarda1 = expresion1
  -- ...
  | guardaN = expresionN
#+end_example

- Las guardas son expresiones tipo *Bool*.
- Se devuelve el valor de la primera guarda con valor *True*.

#+begin_src haskell
abs x
  | x >= 0 = x
  | x < 0  = -x
#+end_src

Usando *otherwise*, si no se cumple ninguna guarda.

#+begin_src haskell
abs x
  | x >= 0 = x
  | otherwise = -x
#+end_src

**** Definiciones locales
#+begin_example
definición_de_la_funcion
  where
    subfuncion1
    ...
    subfuncionN
#+end_example

#+begin_src haskell
f x y = (a+1) * (c-1)
  where
    a = div (x+y) 2
    c = mod (x+y) 2
#+end_src

- Permite usar patrones en cualquier punto de una expresión.

#+begin_example
let definición in expresión
#+end_example

Por ejemplo

#+begin_src haskell
let a x = x + 1 in a 100
#+end_src

**** Funciones anónimas
- Expresiones lambda

#+begin_src haskell
esPar x = mod x 2 == 0
#+end_src

En expresión anónima sería.

#+begin_src haskell
(\x -> mod x 2 == 0) 4
#+end_src

**** La función error
- Detiene la ejecución y muestra un mensaje informativo

#+begin_src haskell
divide a 0 = error "No se puede dividir por 0"
divide a b = a / b  
#+end_src

*** El tipo de las funciones
#+begin_example
identificador :: expresionDeTipo
#+end_example

- Muy similar a la notación matemática $f: \mathbb{R} \to \mathbb{R}$

#+begin_src haskell
doble :: Float -> Float

doble x = 2*x
#+end_src  

**** Polimorfismo
- Funciones con una definición para varios tipos de datos.

**** Currificación de funciones y aplicación parcial
#+begin_src haskell
suma :: Float -> Float -> Float
suma x y = x + y  
#+end_src

El operador -> asocia a la derecha, por tanto.

#+begin_example
suma :: Float -> Float -> Float
-- realmente se aplica la currificación
suma :: Float -> (Float -> Float)
#+end_example  

- Función definida por *aplicación parcial*.

#+begin_src haskell
suma3 :: Float -> Float
suma3 = suma 3  
#+end_src

**** Funciones de orden superior
- Funciones que reciben como parámetro de entrada otras funciones.

#+begin_src haskell
aplica f x y = f x y
#+end_src  

*** Tipos de datos avanzados
**** El valor indefenido: Bottom
- /undefined/ representa un valor indefenido de cualquier tipo.

**** Sinónimos de tipos: type
- Definición de un nuevo nombre para un tipo que ya existe.

#+begin_src haskell
type Caracter = Char
type String = [Caracter]
#+end_src

#+begin_src haskell
type Complex = [Double, Double]
a :: Complex
a = (3.4, 2.5)
#+end_src

**** Definición de nuevos tipos de datos: data
***** Tipos enumerados
Deben empezar con mayúscula.

#+begin_src haskell
data Semaforo = Rojo | Amarillo | Verde
  deriving (Eq,Ord,Show,Read)   -- Deriva de estas clases
#+end_src

- Clases más usadas como deriving.
      - *Eq* : permite comparar elementos.
      - *Ord* : establece una relación de orden entre los elementos.
      - *Show* : permite que el intérprete pueda mostrar un valor de este tipo.
      - *Read* : permite convertir cadenas de texto en elementos del tipo.
            - read "Rojo"::Semaforo , crea el elemento rojo del tipo Semáforo.

***** Unión de tipos
:PROPERTIES:
:ID:       a8e2199b-13a0-421a-9c31-cdd5cac0feff
:END:

Permite agrupar en un único tipo elementos de dos tipos diferentes.

#+begin_src haskell
data BooleanoEntero = Booleano Bool | Entero Integer

listaMixta :: [BooleanoEntero]
listaMixta = [Entero 0, Booleano True, Booleano False, Entero -1]  
#+end_src

***** Producto Cartesiano

#+begin_src haskell
data Asignatura = Asig String Integer String
#+end_src

Más similar a un tipo registro.

#+begin_src haskell
data Asignatura = Asig { nombre :: String, curso :: Integer, web :: String }
#+end_src

Definición de una función constante.

#+begin_src haskell
tlp = Asig { nombre = "Nombre", curso=2, web="una web" }
#+end_src

Y para acceder a uno de los atributos podemos hacer.

#+begin_src haskell
esDePrimero x = curso x == 1
#+end_src

***** Tipo de datos recursivos

#+begin_src haskell
data Natural = Cero | Sucesor Natural
#+end_src

Parece similar a una [[id:a8e2199b-13a0-421a-9c31-cdd5cac0feff][Unión de tipos]].

Luego puede escribirse.

#+begin_src haskell
uno = Sucesor Cero
dos = Sucesor uno
tres = Sucesor dos
#+end_src

Función mayor que.

#+begin_src haskell
mayor (Sucesor _) Cero = True              -- Aquí (Sucesor _) acepta un elemento
                                           --  con una capa de (Sucesor )
mayor Cero _ = False
mayor (Sucesor x) (Sucesor y) = mayor x y  -- Los patrones de entrada eliminan
                                           --  una capa de (sucesor )
#+end_src

***** Tipos polimórficos
- Puede contener valores de cualquier tipo.
      - Como una lista genérica por ejemplo.

#+begin_src haskell
data TipoMixto a b = Tipo a | Tipo b
type BooleanoEntero = TipoMixto Bool Integer
#+end_src        

*** Ejemplos de funciones: trabajando con listas
**** Contar elementos de una lista
#+begin_src haskell
length [] = 0
length (x:xs) = 1 + length xs
#+end_src

**** Concatenar listas
- Listas del mismo tipo

#+begin_src haskell
[] ++ ys = ys
(x:xs) ++ ys = x : (xs ++ ys)
#+end_src  

- Aplanar una lista de listas

#+begin_src haskell
concat [] = []
concat (xs:yss) = xs ++ (concat yss)
#+end_src

**** Combinar listas
- Operación zip.

#+begin_src haskell
zip (x:xs) (y:ys) = (x,y):(zip xs ys)  -- El orden afecta a la evaluación
                                       --  la definición que aparece antes
                                       --  será seleccionada antes si se puede.
zip _ _ = []  
#+end_src

- Operación unzip.

#+begin_src haskell
unzip xs = unzipAux xs ([],[])
  where
    unzipAux [] acumulador = acumulador
    unzipAux ((a,b):xs) (as,bs) = unzipAux xs (as ++ [a], bs ++ [b])
#+end_src

**** Aplicar una función a los elementos de una lista
- función *map*.

#+begin_src haskell
map _ [] = []
map f (x:xs) = (f x) : (map f xs)
#+end_src

- Ejemplo de uso para calcular x*x de cada elemento de una lista.

#+begin_src haskell
map (\x -> x*x) [1..10]
#+end_src

- *zipWith*, como map pero con dos listas

#+begin_src haskell
-- El orden de declaración es importante
zipWith f (a:as) (b:bs) = (f a b) : (zipWith f as bs)
zipWith _ _ _ = []  
#+end_src  

- *iterate*, para crear listas infinitas

#+begin_src haskell
iterate f x = x : (iterate f (f x))  -- En este caso la memoización de haskell
                                     --  permite que sea eficiente

potencias2 = iterate (2*) 1
#+end_src  

**** Filtros sobre listas
- *take* y *drop*

#+begin_src haskell
take _ [] = []
take n (x:xs)
  | n <= 0 = []
  | otherwise = x : take (n-1) xs
#+end_src

#+begin_src haskell
drop _ [] = []
drop n (x:xs)
  | n <= 0 = (x:xs)
  | otherwise = drop (n-1) xs
#+end_src

- *filter*

#+begin_src haskell
filter _ [] = []
filter p (x:sx)
  | p x = x : (filter p xs)
  | otherwise = filter p xs
#+end_src  

- *takeWhile* y *dropWhile*

#+begin_src haskell
takeWhile _ [] = []
takeWhile p (x:xs)
  | p x = x : takeWhile p xs
  | otherwise = []
#+end_src

#+begin_src haskell
dropWhile _ [] = []
dropWhile p ys@(x:xs)  -- @ patrones con nombre
  | p x = dropWhile p xs
  | otherwise = ys
#+end_src

**** Listas por comprensión
#+begin_example
[ expresión | cualificador1, ... , cualificadorn ]
#+end_example

- Donde
      - *expresión*, define la forma de los elementos de la lista resultado.
      - *cualificadores*, definen propiedades de los elementos.
            - *generadores*, expresiones que permiten generar una lista.
            - *filtros*, expresiones booleanas para filtrar elementos.
            - *definiciones locales*, define elementos locales dentro de la definición de la lista.
                  - Se usa la palabra reservada *let*.

#+caption: Lista números impares                    
#+begin_src haskell
[p | p <- [2..], mod p 2 /= 0 ]  -- números impares, /= not equal
#+end_src                    

- Ejemplo de lista con números primos.
  
#+begin_src haskell
divisores n = [ d | d <- [1..n] , mod n d == 0 ]
primos  = [ p | p <- [2..] , divisores p == [1,p]]
#+end_src

**** Plegado de listas
- *foldr*  (right) y *foldl* (left)

#+begin_src haskell
-- z es el caso base
foldr f z [] = z
foldr f z (x:xs) = f x (foldr f z xs)
-- z es el caso base
foldl f z [] = z
foldl f z (x:xs) = foldl f (f z x) xs
#+end_src

#+begin_src haskell
suma = foldr (+) 0
concat = foldr (++) []
#+end_src

* Programación lógica (ProLog)
- pag 85
- Se usa *ProLog*
      - El Programados se orienta en describir el problema.
      - Los programas y datos se presentan bediante *cláusulas* definidas.
      - *Unificación* : equiparación incluida en el sistema (operaciones de sustitución lógica).
      - Incluye un mecanismo de inferencia automática basado en vualta atrás y búsqueda en profundidad.
      - Permite un estilo no determinista de programación.
      - Soporta la recursión y maneja estucturas de datos (lista).

** Especificación de programas
- Básado en el cálculo de predicados de la lógica clásica.
      - Símbolos lógicos : conectivasy cuantificadores.
      - Símbolos no lógicos : Datos.
- Elementos de formulación de problemas
      - *átomos* : representan propiedades o relaciones entre objetos.
            - También conocido como *literales afirmados*.
            - Símbolo no lógico de *predicado*.
                  - Un símbolo 0-ario representa un hecho simple, por ejemplo llueve.
      - *predicados* : Representan relaciones o propiedades que permiten clasificar y discriminar los diferentes tipos de objetos del problema.
            - entrante(X) : Se usa para luego establecer el atributo entrante.
      - *cláusulas* : Combinación de relaciones entre objetos y sus propiedades mediante símbolos lógicos que da lugar a fórmulas.
            - <cabeza> :- <cuerpo>
      - *Marco conceptual* : Descripción de los símbolos no lógicos necesarios para formular el problema.
      - *términos* : Los elementos que parecen en la formulación de un problema.
            - *Variables* :
            - *Constantes* : Objetos concretos y bien conocidos del dominio.
                  - camelCase, se pueden entrecomillar para contener espacios.
            - Símbolo de función con argumentos que son términos.

- Ejemplo de Prolog

#+begin_src prolog
% constantes
paella, gazpacho, potaje  % camelCase, constantes
#+end_src

#+begin_src prolog
entrante(X)               % sneaky_case y la variable en Mayus
plato_de_pescado(X)       % X es un plato de pescado
#+end_src

*** Reglas y programas
- No se utilizan tipos.
- *programa* : Secuencia de hechos y reglas que describen los conocimientos relativos a un problema.
- *reglas* : símbolos lógicos que permiten combinaciones de literales.
      - También se conocen como *Cáusulas de Horn*.
      - También se denomina *cláusulas definidas*.
      - formadas por *cabeza* y *cuerpo* separadas por el símbolo *:-* y acabado en punto.

#+begin_src prolog
Q :- P1, P2, ... , Pn.
#+end_src

- Se lee : si es cierto P1, P2, ..., Pn entonces es cierto Q.

- Reglas como "atributo".
  
#+begin_src prolog
% La carta
entrante(paella).   % la paella es un entrante
entrante(gazpacho).
plato_de_carne(filete).
postre(naranja).
#+end_src

- Reglas de relación de atributos.
      - /Para todo X si X es un plato de carne entonces X es un plato fuerte./
#+begin_src prolog
plato_fuerte(X) :- plato_de_carne(X)
plato_fuerte(X) :- plato_de_pescado(X)
#+end_src  

- , es la conectiva $\land$
      - /Cualquier tipo de valores X,Y,Z tal que X es entrante, Y es plato fuerte y Z es postre/, se escribe en prolog como:

#+begin_src prolog
menu(X,Y,Z) :- entrante(X), plato_fuerte(Y), postre(Z)
#+end_src

- ; es la conectiva $\lor$
      - $q \lor r \to p$, se escribe en prolog como:

#+begin_src prolog
p :- q ; r
#+end_src

#+begin_src prolog
meny(X,Y,Z) :- entrante(X),
               (plato_de_carne(Y); plato_de_pescado(Y),
               postre(Z)).
#+end_src

- , es prioritario sobre ;
      - $(q \land r) \lor s \to p$

#+begin_src prolog
p :- q , r ; s
#+end_src

*** Extracción de respuestas
- *Consulta* : extracción de respuestas de un programa.
- Las consultas empiezan con el símbolos ?-
- *Instancia de la regla* : Es el resultado de sustituir una variable X por un término cualquiera t.
      - La sustitución se denota por <X,t>

- $\exists X, mujer(X) \land ama(manuel,X)$, se escribe como:
  
#+begin_src prolog
% Existe alguna mujer a la que manuel ame?
?- mujer(X), ama(manuel, X).
#+end_src

- /Cuales son los menús contenidos en la carta?/, se escribe como:

#+begin_src prolog
?- menu(X,Y,Z).
#+end_src

- Para confirmar una relación se hace:

#+begin_src prolog
?- menu(paella, filete, naranja).
#+end_src  

- Consultas con algunas restricciones.

#+begin_src prolog
?- menu(paella, X, naranja).
#+end_src  

*** Guía metodológica para la especificación
**** 1 Descripción del Marco conceptual
- pag 97
- Descripción de los elementos u objetos del Dominio.
- Descripción de las pripiedades de los objetos.
- Descripción de las posibles relaciones entre los objetos.

**** 2 Formulación
- Afirmaciones
- Fórmulas que representan la interacción entre literales.

- Programación recursiva
#+begin_src prolog
antepasado(X,Y) :- hijo-ja(Y,X).  % Si Y es hijo-ja de X
                                  %  X es un antepasado de Y
antepasado(X,Y) :- hijo-ja(Y,Z), antepasado(X,Z).
#+end_src  

- Formulación aritmética
      - Se expresa mediante *is* con notación infija.
      - La aritmética en prolog también se entiende en forma predictiva.
      - Z is 4 + 7, asigna 7 a la variable Z

#+begin_src prolog
factorial(0,1).        % factorial de 0 es 1
factorial(N,M) :- I is N-1, factorial(I,A), M is N*A.
#+end_src

- La consulta se escribe como:

#+begin_src prolog
?- factorial(3,X)     % Cual es el factorial de 3?
#+end_src  

** Computación lógica
- Proceso que resuelve la consulta.
  
*** Unificación
**** Unificación Simple
- Dos objetivos se unifican si existe un unificador formado por pares de <Variable, término>.
      1. Dos literales u objetivos se unifican si tienen igual símbolo de predicado, igual número de argumentos y éstos son unificables uno a uno.
      2. Una variable se unifica con cualquier otro término pasando a tomar ese valor.
      3. Una constante solo se unifica con otra constante idéntica sintácticamente.
      4. Dos términos compuestos se unifican si tienen igual símbolo de función, igual número de argumentos y éstos son unificables.

**** Unificación General
- *Entrada* : A,B literales a unificar.
- *Algoritmo* :
#+begin_src pseudocode
Sea S<-{} la sustitución vacía
mientras S(A) no sea S(B) hacer
    Determinar símbolo más a la izquierda de S(A) que sea
      distinto del símbolo en igual posición en S(B).
    Calcular a partir de los símbolos anteriores, los términos
      o fórmulas u_1 y u_2 mínimos que comienzan por ellos.
      
    si ni u_1 ni u_2 son variables o uno es un variable contenida en el otro entonces
      dev "acabar, pues A y B no son unificables"
    sino
       Determinar una variable x en u_1 (o en u_2) y el subtérmino
         b en la misma posición en u_2 (resp. en u_1) y hacer S = S union (<x,b>).
    fsi
fmientras
#+end_src  
- *Salida :* S es el *unificador de máxima generalidad* (umg) de los literales A y B.

- Una regla o cláusula permite deducir un objetivo si existe una unificación (umg) que.
      - identifique este objetivo con la conclusión de la regla
      - o si existe una instancia de la regla del programa que infiere exactamente al objetivo.

*** Resolución
- Algoritmo de resolución controlada.
- *Inicio* : La lista de objetivos es la que forma la consulta.
- *Selección* ...
      1. ... de un objetivo a resolver: el primero más a la izquierda.
      2. ... de una regla o cláusula para resolver el objetivo seleccionado:
         La primera cuya conclusión o parte de la izquierda se unifica con el objetivo.
- Una vez realizada la selección
      - El modelo de computación recuerda todas las reglas que podrían haber sido seleccionadas en este momento.
      - El objetivo es reemplazado en la lista de objetivos por la parte derecha de la regla seleccionada.
      - Se aplica a la lista de objetivos resultante el unificador que hace posible unificar el objetivo resuelto con la parte izquierda de la regla.
- *Repetición* : Se continua el proceso de selección hasta que se cumple uno :
      - Se vacía la lista de objetivos (EXITO), Se devuelve el unificador como respuesta.
      - No puede ser resuelto un objetivo (FRACASO LÓGICO).
- Durante la resolución se selecciona el primer objetivo más a la izquierda y la primera cláusula que aparece en el programa.

*** Control de la ejecución
# TODO: repasar y dibujar los espacios de búsqueda.
**** Corte
- [[id:TeLenProg]] pag 112
- En Prolog el control de la ejecución es interno y no modificable.
- Existen algunos mecanismos no lógicos que permiten la variación de la forma de ejecución.
- *corte* : ! : permite reducir el espacio de búsqueda de un objetivo.
      - Elimina todas las opciones de la rama en que se encuentra a partir del nodo anterior al de su aparición (Solo se sigue una de las ramas).

#+begin_src prolog
p :- q,t.
p :- m, !.                      % ! indica el corte
p :- r.
q :- s,!.
s.
s :- m.
t.
r.
#+end_src

- Puede introducir errores colaterales, se recomienda su uso cuando se sepa que la solución es única.

#+begin_src prolog
%% Juan no tiene hermanos, pedro tiene 1 hermanos, cualquier otro tiene 2 hermanos.
numero_de_hermanos(juan,0) :- !.
numero_de_hermanos(pedro,1) :- !.
numero_de_hermanos(X,2) :- dif(X,juan), dif(X,pedro).
#+end_src

- Con el *corte* podemos escribir la negación por defecto.
      - *call(x)* : permite parametrizar la resolución Prolog del objetivo X.
      - *fallo* nunca se definiría en el programa.

#+begin_src prolog
no(X) :- call(X), !, fallo.
no(X).
#+end_src  

- *Corte rojo* : Corte que modifica el significado del programa.
- *Corte verde* : Corte que no modifica el significado del programa.

*** Estructura de datos: la lista
# TODO: repasar y dibujar los espacios de búsqueda.
- [[id:TeLenProg]] pag 119
- [] :lísta vacía.
- [1,2,3] : lista con 3 elementso.
- son del tipo [cabeza|cola]
- dos listas son unificables si son unificables sus cabezas y sus colas son unificables.

** Técnicas avanzadas de programación lógica
*** Indeterminismo
- [[id:TeLenProg]] pag 126
- Reglas mal planteadas pueden llevar a espacios de búsqueda infinitos.
- El orden de la declaración de las reglas afecta al funcinamiento del programa.
- Los cortes pueden modificar el significado del programa.

*** Eficiencia con la estructuras de datos
- [[id:TeLenProg]] pag 120
- Se ven funciones como argumentos de objetivos.
      - Representan un objeto o elemento.
- Problema del brazo robot y los bloques.

#+begin_src prolog
%% en(X,Y) X está sobre Y
%% libre(X) X no tiene nada encima
%% resultado(llevar(X,Y,Z),E) denota el resultado resultande de llevar X de Y a Z en el estado E

%% Condiciones en el estado 0 o inicial
cierto(en(bloque_A,bloque_B),0).
cierto(en(bloque_B,pos1),0).
cierto(en(bloque_C,pos3),0).
cierto(libre(pos2),0).
cierto(libre(bloque_A),0).
cierto(libre(bloque_C),0).

%% Condiciones para cambiar bloques de sitio
cierto(en(X,Z), resultado(llevar(X,Y,Z),W)).
cierto(libre(Y),resultado(llevar(X,Y,Z),W)).

%% Condición de invarianza
cierto(U, resultado(llevar(XY,Z),W)) :- cierto(U,W),
                                        dif(U,en(X,Y)),
                                        dif(U,libre(Z)).
posible(0).
posible(resultado(llevar(X,Y,Z), W)) :- posible(W),
                                        manipulable(X),
                                        dif(X,Y),
                                        cierto(libre(X),W),
                                        cierto(libre(Z),W),
                                        cierto(en(X,Y),W).
manipulable(bloque_A).
manipulable(bloque_B).
manipulable(bloque_C).
#+end_src

- la consulta es la descripción del estado final deseado, ha de ser posible alcanzar el estado inicial.

#+begin_src prolog
?- cierto(en(bloque_A,bloque_B),W),
   cierto(en(bloque_B,bloque_C),W),
   cierto(en(bloque_C,pos3),W),
   posible(W).
#+end_src

*** Gestión dinámica
- [[id:TeLenProg]] pag 135
- *lemas* : Permite guardar resultados intermedios para accelerar las búsquedas posteriores.

#+begin_src prolog
fib(X,Y):- lfib(X,Y),!.
fib(X,Y):- A is X-1, fib(A,M), B is X-2, fib(B,N),
           Y is M+N, assert(lfib(X,Y)).
initfib :- assert(lfib(0,1)), assert(lfib(l,1)).
#+end_src

*** Uso eficiente de la recursión
- [[id:TeLenProg]] pag 137
- Las técnicas recursivas son el pilar de la programación lógica.
- Aún así conviene retrasar lo máxima su resolución para no explorar caminos innecesarios.

*** Meta-programación
- [[id:TeLenProg]] pag 138
- En prolog se describe el programa y el meta-programa con reglas prolog.

* Sintaxis y Semántica Básica
** Sintaxis de los lenguajes de Programación
- Se describe con gramáticas libre de contexto en notación BNF.

*** Estructura léxica de los lenguajes de Programación
- *Análisis léxico* : Se encarga de identificar secuencias de *tokens*.
- *Análisis sintáctico* : Forma las estructuras sintácticas de un programa.
      - Combinaciones correctas de *tokens*.
- Tipos de Tokens:
      - *palabras reservadas* y *palabras clave*:
            - Las palabras reservadas no pueden redefinirse como identificadores.
            - Palabras clave tienen un significado especial en el lenguaje y forman parte de su sintaxis.
      - *literales* : números o una cadena de letras (variable1, 33, etc).
      - *símbolos* : ";" "+" y otros símbolos especiales.
      - *identificadores* : Cadenas definidas por el programador que no pueden ser palabras reservadas.
            - Su Longitud puede estar prefinida en algunos lenguajes.
            - *subcadena de mayor longitud* : Otra forma es que exista un símbolo de delimitador de nuevo *token* como un espacio en blanco.
- La forma habitual de identificar los tokens es mediante *expresiones regulares*

**** Formalización de las expresiones regulares
- El objetivo es representar a los lenguajes sobre un *alfabeto* $\Sigma$ basándose en lenguajes primitivos y operaciones de composición.
- Dado un alfabeto $\Sigma$.
      - Expresiones regulares primitivas:
            - $\emptyset$ : lenguaje vacío.
            - $\lambda$   : palabra vacía.
            - $a$, $a \in \Sigma$
      - Sean $\alpha$ y $\beta$ dos expresiones regulares, son expresiones regulares derivadas:
            - $\alpha + \beta$ : unión (como un or)
            - $\alpha \cdot \beta$ o $\alpha \beta$ : concatenación
            - $\alpha^*$ : cierre (cualquier cantidad), clausula de Kleene.
            - $(\alpha)$ : expresión regular entre paréntesis (agrupaciones)
- Precedencia de operadores:
      1. ()
      2. $*$
      3. $\cdot$
      4. $+$
- Sea *exp* una expresion regular sobre $\Sigma$.
      - $L(exp)$ es el lenguaje descrito por *exp*.
- Definidión recursiva de $L(exp)$:
      - Si exp = $\emptyset$ entonces $L(\emptyset) := \emptyset$
      - Si exp = $\lambda$ entonces $L(\lambda) := \{\lambda\}$
      - Si exp = $a$, con $a \in \Sigma$ entonces $L(a) := \{a\}$
      - Si exp = $\alpha + \beta$ entonces $L(\alpha  + \beta) := L(\alpha) \cup L(\beta)$
            - $\alpha$ y $\beta$ son expresiones regulares sobre $\Sigma$.
      - Si exp = $\alpha \cdot \beta$ entonces $L(\alpha \cdot \beta) := L(\aplha)L(\beta)$
      - Si exp = $\alpha^*$ entonces $L(\alpha^*) := L(\alpha)^*$
      - Si exp = $(\alpha)$ entonces $L((\alpha)) := L(\alpha)$
- Equivalencias en expresiones regulares (Dos expresiones regulares diferentes pueden definir el mismo lenguaje):
      1. $\alpha + (\beta + \gamma) = (\alpha + \beta) + \gamma$
      2. $\alpha \centerdot (\beta \centerdot \gamma) = (\alpha \centerdot \beta) \centerdot \gamma$
      3. $\alpha + \beta$ = \beta + \gamma$
      4. $\alpha \centerdot (\beta + \gamma) = \alpha \centerdot \beta + \alpha \centerdot \gamma$
      5. $(\alpha + \beta) \centerdot \gamma = \alpha \centerdot \gamma + \beta \centerdot \gamma$
      6. $\alpha \centerdot \lambda = \alpha$ y $\alpha + \emptyset = \alpha$
      7. $\alpha \centerdot \emptyset = \emptyset$
      8. Si $\lambda \in L(\alpha)$ entonces $\alpha + \lambda = \alpha$
      9. $\alpha^* = \lambda + \alpha \centerdot \alpha^*$
      10. $\lambda^* = \lambda$
      11. $\emptyset^* = \lambda$
      12. $\alpha^*\alpha^*=\alpha^*$
      13. $\alpha\alpha^*=\alpha^*\alpha$
      14. $(\alpha^*)^* = \alpha^*$
      15. $(\alpha^* + \beta^*)^* = (\alpha^*\beta^*)^* = (\alpha+\beta)^* = (\alpha^*\beta)^*\alpha^*$
      16. $(\alpha\beta)^*\alpha = \alpha(\beta\alpha)^*$
- Las expresiones regulares pueden representar *lenguajes regulares*.

**** Las expresiones regulares en la programación
- Patrones que permiten encontrar combinaciones de carácteres dentro de cadenas de texto.
- [[id:TeLenProg]] pag 166 tabla con símbolos de expresiones regulares (regex).

*** Gramáticas libres de contexto
- Formada por:
      - *V_NT* : símbolos no terminales.
      - *VY* : símbolos terminales o tokens.
      - *S* : *Símbolo Inicial* no terminal.
      - Un conjunto de *reglas*.
            - <símbolo no termibal> -> <símbolos terminales y no terminales>
            - | : puede agrupar reglas A -> C|B es igual a A->C A->B
- *Derivación* : Secuencia que empieza desde el *Símbolo inicial* y en la que cada paso se sustituye un símbolo no terminal por la parte derecha de una regla.
- *Derivación de una cadena* : todos los símbolos de la cadena en curso son terminales.
- $\Rightarrow$ : Se usa para indicar el paso de una derivación.
- Puede hacerse la derivación *marcha atras*.
      - Se dice que la cadena es *reconocida por la gramatica*.
      - Desde una cadena de *símbolos terminales* hasta el *símbolo inicial*.

*** Notación BNF
:PROPERTIES:
:ID: ec41e456-bcc4-497e-b93c-8cb549c25a31
:END:
- Permite definir las reglas sintácticas de las estructuras de un lenguaje de programación.
      - Se definen con el uso de *símbolos* y *metasímbolos*.
- *Metasímbolos*:
      - ::= separación entre la parte de la izquierda y derecha de una regla.
      - |   Alternativa (Se puede elegir uno de los elementos).
- *Símbolos*:
      - *terminales* y *no terminales*
            - Se diferencian por el estilo de letra.
            - los terminales se escriben entre "<>", por ejemplo <no_terminal>

- El siguiente ejemplo representa las reglas de los número enteros:
#+begin_example
<valor_entero> ::= <secuencia_dígitos> | - <secuencia_dígitos>
<secuencia_dígitos> ::= <dígito> | <dígito> <secuencia_dígitos>
<dígito> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 
#+end_example

*** Estructura sintáctica : árboles sintácticos
- *Semántica dirigida por sintaxis* : A cada estructura sintáctica se le puede asociar una semántica o significado.
      - Es necesario disponer de una representación de cada estructura sintáctica derivada por una gramática.
      - Y una forma de asociación de su semántica.
- *árbol sintáctico* : estándar de estructura sintáctica.
      - Se genera durante el *análisis sintáctico*
            - Representa el resultado de una derivación.
            - Hojas son los *símbolos terminales*.
            - Nodos interiores son los *símbolos no terminales*.

\begin{tikzpicture}[level distance=10mm,level/.style={sibling distance=20mm/#1}]
\node [PL] {F(R1)}
    child
    {
        node [PL] {GN(R3)} 
        child
        {
            node [PL] {NPROP(R10)} 
            child
            {
                node [PL] {Aránzazu}
            }
        }
     }
     child
     {
         node [PL] {GV(R4)}
         child {
             node [PL] {es}
         }
         child {
             node [PL] {ATR(R5)}
             child {
                 node [PL] {ADJ(R12)}
                 child {
                     node [PL] {buena}
                 } 
              }
         }
     };
\end{tikzpicture}    

- notación BNF que abstrae 1 + 2 * 3
      - Tiene implícito el orden de los operadores.

#+begin_example
<expresión> ::= <término> | <término> <op_aditivo> <expresión>
<término> ::= <factor> | <factor> <op_multiplicativo> <término>
<factor> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<op_aditivo> ::= + | -
<op_multiplicativo> ::= * | /
#+end_example

\begin{tikzpicture}[
  level distance=15mm,
  every node/.style={draw, rectangle, rounded corners, align=center},
  level 1/.style={sibling distance=45mm},
  level 2/.style={sibling distance=30mm},
  level 3/.style={sibling distance=25mm}
]
\node {expresion}
    child { node {termino} 
        child { node {factor} child { node {1} } }
    }
    child { node {op\_aditivo} child { node {+} }
    }
    child { node {expresion} 
        child { node {termino} 
            child { node {factor} child { node {2} } }
            child { node {op\_multiplicativo} child { node {*} } }
            child { node {termino} child { node {factor} child { node {3} } } }
        }
    };
\end{tikzpicture}

*** Ambigüedad, sociatividad y precedencia
- [[id:TeLenProg]] pag 173
- *Ambigüedad* : Dos derivaciones diferentes llevan a árboles sintácticos diferentes para una misma palabra.
      - Se pueden establecer *reglas* para el orden de las derivaciones.
      - *derivación por la izquierda* : se derivan primero los símbolos más a la izquierda.
            - Se consideraría ambigüa si aún así encontramos más de 1 derivación para una misma cadena.
- *Criterio para eliminar ambigüedades*:
      - Aportar reglas de derivación (derivación por la izquierda).
      - Además de las reglas se puede ajustar la gramática para eliminar las ambigüedades.

*** Diagramas sintácticos
- EBNF es una ampliación de la [[id:ec41e456-bcc4-497e-b93c-8cb549c25a31][Notación BNF]].
      - Se añaden más metasímbolos.
      - No añade expresividad.
- Metasímbolos EBNF
      - ::= Separación entre parte izquierda y parte derecha.
      - |   Alternativa
      - {}  Los elementos que se incluyen se pueden repetir 0 o más veces.
      - []  opción (pueden usarse o no)
      - ()  Agrupación
- No permite la recursión.
- *diagrama sintáctico* : forma estándar de representar las notaciones EBNF.
      - Terminales círculos.
      - No Terminales cuadrados.
      - [[id:TeLenProg]] pag 176 hay ejemplos.
- Los diagramas sintácticos y la notación EBNF son de especial utilidad a la hora de escribir un *analizador sintáctico*.
      - Que emplee *análisis sintáctico descendente*.

** La semántica de los lenguajes de programación


* Glosario
- *Evaluación impaciente* : /factorial(4*5)/ primero evalua el resultado de 4*5.
- *mónadas* : indivisibles

* Tools
** Haskell compiler and interpreter
#+begin_src sh
ghci       # Open the haskell interpreter
#+end_src

* Bibliografía

** Teoría de los lenguajes de programación
:PROPERTIES:
:ID: TeLenProg
:TIPE: book
:TITLE: Teoría de los lenguajes de programación
:EDITORIAL: Ramón Areces
:AUTHOR: Fernando López Ostenero, Ana María García Serrano
:END:

** Webs de interés
http://aprendehaskell.es/main.html
https://learnyouahaskell.github.io/introduction.html
